ALTER TABLE REG_RESOURCE_COMMENT ADD ID INTEGER NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (ID);

ALTER TABLE REG_RESOURCE_RATING ADD ID INTEGER NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (ID);

ALTER TABLE REG_RESOURCE_TAG ADD ID INTEGER NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (ID);

ALTER TABLE REG_RESOURCE_PROPERTY ADD ID INTEGER NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (ID);
