ALTER TABLE CM_PII_CATEGORY ADD COLUMN UUID CHAR(36)
/
ALTER TABLE CM_RECEIPT ADD COLUMN EXPIRY_TIME TIMESTAMP
/
CREATE OR REPLACE PROCEDURE ADD_CM_RECEIPT_CURSOR_KEY
BEGIN ATOMIC
-- Add CURSOR_KEY column to CM_RECEIPT
IF NOT EXISTS(SELECT *
FROM SYSCAT.COLUMNS
WHERE TABNAME = 'CM_RECEIPT' AND COLNAME = 'CURSOR_KEY' AND TABSCHEMA = CURRENT_SCHEMA)
    THEN
EXECUTE IMMEDIATE 'ALTER TABLE CM_RECEIPT ADD COLUMN CURSOR_KEY INTEGER NOT NULL DEFAULT 0';
END
IF;

-- Add unique constraint on CURSOR_KEY
IF NOT EXISTS(SELECT *
FROM SYSCAT.TABCONST
WHERE TABNAME = 'CM_RECEIPT' AND CONSTNAME = 'CM_RECEIPT_CURSOR_KEY_UNQ' AND TABSCHEMA = CURRENT_SCHEMA)
    THEN
EXECUTE IMMEDIATE 'ALTER TABLE CM_RECEIPT ADD CONSTRAINT CM_RECEIPT_CURSOR_KEY_UNQ UNIQUE (CURSOR_KEY)';
END
IF;
END
/
CALL ADD_CM_RECEIPT_CURSOR_KEY
/
DROP PROCEDURE ADD_CM_RECEIPT_CURSOR_KEY
/
CREATE SEQUENCE CM_RECEIPT_SEQ
  START WITH 1
  INCREMENT BY 1 NOCACHE
/
CREATE TRIGGER CM_RECEIPT_TRIGGER NO CASCADE BEFORE INSERT ON CM_RECEIPT
REFERENCING NEW AS NEW FOR EACH ROW MODE DB2SQL

BEGIN ATOMIC

    SET (NEW.CURSOR_KEY)
       = (NEXTVAL FOR CM_RECEIPT_SEQ);

END
/
CREATE TABLE CM_CONSENT_AUTHORIZATION (
  CONSENT_RECEIPT_ID VARCHAR(255) NOT NULL,
  USER_ID            VARCHAR(255) NOT NULL,
  STATUS             VARCHAR(50)  NOT NULL,
  UPDATED_TIME       BIGINT       NOT NULL,
  TYPE               VARCHAR(255),
  PRIMARY KEY (CONSENT_RECEIPT_ID, USER_ID)
)
/
ALTER TABLE CM_PURPOSE ADD COLUMN UUID CHAR(36)
/
ALTER TABLE CM_PURPOSE ADD COLUMN LATEST_VERSION_ID CHAR(36)
/
ALTER TABLE CM_SP_PURPOSE_ASSOC ADD COLUMN PURPOSE_VERSION_ID CHAR(36)
/
CREATE TABLE CM_PURPOSE_VERSION (
  UUID CHAR(36) NOT NULL,
  PURPOSE_ID  INTEGER NOT NULL,
  VERSION     VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(1023),
  TENANT_ID   INTEGER DEFAULT -1234 NOT NULL,
  CONSTRAINT PURPOSE_VERSION_CONSTRAINT UNIQUE (PURPOSE_ID, VERSION),
  UNIQUE (PURPOSE_ID, UUID),
  PRIMARY KEY (TENANT_ID, UUID)
)
/
CREATE TABLE CM_PURPOSE_VERSION_PII_CAT_ASSOC (
  PURPOSE_VERSION_ID CHAR(36) NOT NULL,
  CM_PII_CATEGORY_ID INTEGER NOT NULL,
  IS_MANDATORY       INTEGER NOT NULL,
  TENANT_ID          INTEGER NOT NULL DEFAULT -1234,
  PRIMARY KEY (PURPOSE_VERSION_ID, CM_PII_CATEGORY_ID)
)
/
CREATE TABLE CM_PURPOSE_VERSION_PROPERTY (
  VERSION_ID     CHAR(36)      NOT NULL,
  PROPERTY_KEY   VARCHAR(255)  NOT NULL,
  PROPERTY_VALUE VARCHAR(1023) NOT NULL,
  TENANT_ID      INTEGER       NOT NULL DEFAULT -1234,
  PRIMARY KEY (VERSION_ID, PROPERTY_KEY)
)
/
CREATE TABLE CM_PII_CATEGORY_PROPERTY (
  PII_CATEGORY_ID  INTEGER       NOT NULL,
  PROPERTY_KEY     VARCHAR(255)  NOT NULL,
  PROPERTY_VALUE   VARCHAR(1023) NOT NULL,
  TENANT_ID        INTEGER       NOT NULL DEFAULT -1234,
  PRIMARY KEY (PII_CATEGORY_ID, PROPERTY_KEY)
)
/
ALTER TABLE CM_CONSENT_AUTHORIZATION
  ADD CONSTRAINT CM_CONSENT_AUTH_fk0 FOREIGN KEY (CONSENT_RECEIPT_ID) REFERENCES CM_RECEIPT (CONSENT_RECEIPT_ID) ON DELETE CASCADE
/
ALTER TABLE CM_SP_PURPOSE_ASSOC
  DROP CONSTRAINT CM_SP_PURPOSE_ASSOC_fk1
/
ALTER TABLE CM_SP_PURPOSE_ASSOC
  ADD CONSTRAINT CM_SP_PURPOSE_ASSOC_fk1 FOREIGN KEY (PURPOSE_ID) REFERENCES CM_PURPOSE (ID) ON DELETE CASCADE
/
ALTER TABLE CM_SP_PURPOSE_ASSOC
  ADD CONSTRAINT CM_SP_PURPOSE_ASSOC_fk2 FOREIGN KEY (PURPOSE_ID, PURPOSE_VERSION_ID) REFERENCES CM_PURPOSE_VERSION (PURPOSE_ID, UUID) ON DELETE CASCADE
/
ALTER TABLE CM_PURPOSE_VERSION
  ADD CONSTRAINT CM_PURPOSE_VERSION_fk0 FOREIGN KEY (PURPOSE_ID) REFERENCES CM_PURPOSE (ID) ON DELETE CASCADE
/
ALTER TABLE CM_PURPOSE
  ADD CONSTRAINT CM_PURPOSE_LATEST_VER_fk FOREIGN KEY (ID, LATEST_VERSION_ID) REFERENCES CM_PURPOSE_VERSION (PURPOSE_ID, UUID)
/
ALTER TABLE CM_PURPOSE_VERSION_PII_CAT_ASSOC
  ADD CONSTRAINT CM_PV_PII_CAT_ASSOC_fk0 FOREIGN KEY (TENANT_ID, PURPOSE_VERSION_ID) REFERENCES CM_PURPOSE_VERSION (TENANT_ID, UUID) ON DELETE CASCADE
/
ALTER TABLE CM_PURPOSE_VERSION_PII_CAT_ASSOC
  ADD CONSTRAINT CM_PV_PII_CAT_ASSOC_fk1 FOREIGN KEY (CM_PII_CATEGORY_ID) REFERENCES CM_PII_CATEGORY (ID) ON DELETE CASCADE
/
ALTER TABLE CM_PURPOSE_VERSION_PROPERTY
  ADD CONSTRAINT CM_PV_PROPERTY_fk0 FOREIGN KEY (TENANT_ID, VERSION_ID) REFERENCES CM_PURPOSE_VERSION (TENANT_ID, UUID) ON DELETE CASCADE
/
ALTER TABLE CM_PII_CATEGORY_PROPERTY
  ADD CONSTRAINT CM_PII_CAT_PROP_fk0 FOREIGN KEY (PII_CATEGORY_ID) REFERENCES CM_PII_CATEGORY (ID) ON DELETE CASCADE
/
CREATE INDEX CM_PII_CATEGORY_UUID_IDX ON CM_PII_CATEGORY (UUID)
/
CREATE INDEX CM_PURPOSE_UUID_IDX ON CM_PURPOSE (UUID)
/
