ALTER TABLE CM_PII_CATEGORY ADD COLUMN IF NOT EXISTS UUID CHAR(36);

ALTER TABLE CM_RECEIPT ADD COLUMN IF NOT EXISTS CURSOR_KEY INTEGER NOT NULL AUTO_INCREMENT;
ALTER TABLE CM_RECEIPT ADD CONSTRAINT IF NOT EXISTS CM_RECEIPT_CURSOR_KEY_UNQ UNIQUE (CURSOR_KEY);
ALTER TABLE CM_RECEIPT ADD COLUMN IF NOT EXISTS EXPIRY_TIME TIMESTAMP NULL;

CREATE TABLE IF NOT EXISTS CM_CONSENT_AUTHORIZATION (
  CONSENT_RECEIPT_ID VARCHAR(255) NOT NULL,
  USER_ID            VARCHAR(255) NOT NULL,
  STATUS             VARCHAR(50)  NOT NULL,
  UPDATED_TIME       BIGINT       NOT NULL,
  TYPE               VARCHAR(255),
  PRIMARY KEY (CONSENT_RECEIPT_ID, USER_ID)
);

ALTER TABLE CM_PURPOSE ADD COLUMN IF NOT EXISTS UUID CHAR(36);
ALTER TABLE CM_PURPOSE ADD COLUMN IF NOT EXISTS LATEST_VERSION_ID CHAR(36);

ALTER TABLE CM_SP_PURPOSE_ASSOC ADD COLUMN IF NOT EXISTS PURPOSE_VERSION_ID CHAR(36);

CREATE TABLE IF NOT EXISTS CM_PURPOSE_VERSION (
  UUID CHAR(36) NOT NULL,
  PURPOSE_ID  INTEGER NOT NULL,
  VERSION     VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(1023),
  TENANT_ID   INTEGER DEFAULT '-1234',
  UNIQUE (PURPOSE_ID, VERSION),
  UNIQUE (PURPOSE_ID, UUID),
  PRIMARY KEY (TENANT_ID, UUID)
);

CREATE TABLE IF NOT EXISTS CM_PURPOSE_VERSION_PII_CAT_ASSOC (
  PURPOSE_VERSION_ID CHAR(36) NOT NULL,
  CM_PII_CATEGORY_ID INTEGER NOT NULL,
  IS_MANDATORY       INTEGER NOT NULL,
  TENANT_ID          INTEGER NOT NULL DEFAULT -1234,
  PRIMARY KEY (PURPOSE_VERSION_ID, CM_PII_CATEGORY_ID)
);

CREATE TABLE IF NOT EXISTS CM_PURPOSE_VERSION_PROPERTY (
  VERSION_ID     CHAR(36)      NOT NULL,
  PROPERTY_KEY   VARCHAR(255)  NOT NULL,
  PROPERTY_VALUE VARCHAR(1023) NOT NULL,
  TENANT_ID      INTEGER       NOT NULL DEFAULT -1234,
  PRIMARY KEY (VERSION_ID, PROPERTY_KEY)
);

CREATE TABLE IF NOT EXISTS CM_PII_CATEGORY_PROPERTY (
  PII_CATEGORY_ID  INTEGER       NOT NULL,
  PROPERTY_KEY     VARCHAR(255)  NOT NULL,
  PROPERTY_VALUE   VARCHAR(1023) NOT NULL,
  TENANT_ID        INTEGER       NOT NULL DEFAULT -1234,
  PRIMARY KEY (PII_CATEGORY_ID, PROPERTY_KEY),
  FOREIGN KEY (PII_CATEGORY_ID) REFERENCES CM_PII_CATEGORY(ID) ON DELETE CASCADE
);

ALTER TABLE CM_CONSENT_AUTHORIZATION ADD CONSTRAINT IF NOT EXISTS CM_CONSENT_AUTH_fk0
  FOREIGN KEY (CONSENT_RECEIPT_ID) REFERENCES CM_RECEIPT (CONSENT_RECEIPT_ID) ON DELETE CASCADE;

ALTER TABLE CM_SP_PURPOSE_ASSOC ADD CONSTRAINT IF NOT EXISTS CM_SP_PURPOSE_ASSOC_fk2
  FOREIGN KEY (PURPOSE_ID, PURPOSE_VERSION_ID) REFERENCES CM_PURPOSE_VERSION (PURPOSE_ID, UUID) ON DELETE CASCADE;

ALTER TABLE CM_PURPOSE_VERSION ADD CONSTRAINT IF NOT EXISTS CM_PURPOSE_VERSION_fk0
  FOREIGN KEY (PURPOSE_ID) REFERENCES CM_PURPOSE (ID) ON DELETE CASCADE;

ALTER TABLE CM_PURPOSE ADD CONSTRAINT IF NOT EXISTS CM_PURPOSE_LATEST_VER_fk
  FOREIGN KEY (ID, LATEST_VERSION_ID) REFERENCES CM_PURPOSE_VERSION (PURPOSE_ID, UUID);

ALTER TABLE CM_PURPOSE_VERSION_PII_CAT_ASSOC ADD CONSTRAINT IF NOT EXISTS CM_PV_PII_CAT_ASSOC_fk0
  FOREIGN KEY (TENANT_ID, PURPOSE_VERSION_ID) REFERENCES CM_PURPOSE_VERSION (TENANT_ID, UUID) ON DELETE CASCADE;

ALTER TABLE CM_PURPOSE_VERSION_PII_CAT_ASSOC ADD CONSTRAINT IF NOT EXISTS CM_PV_PII_CAT_ASSOC_fk1
  FOREIGN KEY (CM_PII_CATEGORY_ID) REFERENCES CM_PII_CATEGORY (ID) ON DELETE CASCADE;

ALTER TABLE CM_PURPOSE_VERSION_PROPERTY ADD CONSTRAINT IF NOT EXISTS CM_PV_PROPERTY_fk0
  FOREIGN KEY (TENANT_ID, VERSION_ID) REFERENCES CM_PURPOSE_VERSION (TENANT_ID, UUID) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS CM_PII_CATEGORY_UUID_IDX ON CM_PII_CATEGORY (UUID);
CREATE INDEX IF NOT EXISTS CM_PURPOSE_UUID_IDX ON CM_PURPOSE (UUID);
