ALTER TABLE CM_PII_CATEGORY ADD UUID CHAR(36);

ALTER TABLE CM_RECEIPT ADD CURSOR_KEY INTEGER NOT NULL IDENTITY;
ALTER TABLE CM_RECEIPT ADD CONSTRAINT CM_RECEIPT_CURSOR_KEY_UNQ UNIQUE (CURSOR_KEY);
ALTER TABLE CM_RECEIPT ADD EXPIRY_TIME DATETIME NULL;

IF NOT EXISTS ( SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[CM_CONSENT_AUTHORIZATION]') AND TYPE IN (N'U'))
CREATE TABLE CM_CONSENT_AUTHORIZATION (
  CONSENT_RECEIPT_ID VARCHAR(255) NOT NULL,
  USER_ID            VARCHAR(255) NOT NULL,
  STATUS             VARCHAR(50)  NOT NULL,
  UPDATED_TIME       BIGINT       NOT NULL,
  TYPE               VARCHAR(255),
  FOREIGN KEY (CONSENT_RECEIPT_ID) REFERENCES CM_RECEIPT (CONSENT_RECEIPT_ID) ON DELETE CASCADE,
  PRIMARY KEY (CONSENT_RECEIPT_ID, USER_ID)
);

ALTER TABLE CM_PURPOSE ADD UUID CHAR(36);
ALTER TABLE CM_PURPOSE ADD LATEST_VERSION_ID CHAR(36);

ALTER TABLE CM_SP_PURPOSE_ASSOC ADD PURPOSE_VERSION_ID CHAR(36);

IF NOT EXISTS ( SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[CM_PURPOSE_VERSION]') AND TYPE IN (N'U'))
CREATE TABLE CM_PURPOSE_VERSION (
  UUID CHAR(36) NOT NULL,
  PURPOSE_ID  INTEGER NOT NULL,
  VERSION     VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(1023),
  TENANT_ID   INTEGER DEFAULT '-1234',
  CONSTRAINT CM_PURPOSE_VERSION_CNT UNIQUE (PURPOSE_ID, VERSION),
  UNIQUE (PURPOSE_ID, UUID),
  FOREIGN KEY (PURPOSE_ID) REFERENCES CM_PURPOSE (ID) ON DELETE CASCADE,
  PRIMARY KEY (TENANT_ID, UUID)
);

IF NOT EXISTS ( SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[CM_PURPOSE_VERSION_PII_CAT_ASSOC]') AND TYPE IN (N'U'))
CREATE TABLE CM_PURPOSE_VERSION_PII_CAT_ASSOC (
  PURPOSE_VERSION_ID CHAR(36) NOT NULL,
  CM_PII_CATEGORY_ID INTEGER NOT NULL,
  IS_MANDATORY       INTEGER NOT NULL,
  TENANT_ID          INTEGER NOT NULL DEFAULT -1234,
  FOREIGN KEY (TENANT_ID, PURPOSE_VERSION_ID) REFERENCES CM_PURPOSE_VERSION (TENANT_ID, UUID) ON DELETE CASCADE,
  FOREIGN KEY (CM_PII_CATEGORY_ID) REFERENCES CM_PII_CATEGORY (ID) ON DELETE CASCADE,
  PRIMARY KEY (PURPOSE_VERSION_ID, CM_PII_CATEGORY_ID)
);

IF NOT EXISTS ( SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[CM_PURPOSE_VERSION_PROPERTY]') AND TYPE IN (N'U'))
CREATE TABLE CM_PURPOSE_VERSION_PROPERTY (
  VERSION_ID     CHAR(36)       NOT NULL,
  PROPERTY_KEY   VARCHAR(255)   NOT NULL,
  PROPERTY_VALUE VARCHAR(1023)  NOT NULL,
  TENANT_ID      INTEGER        NOT NULL DEFAULT -1234,
  FOREIGN KEY (TENANT_ID, VERSION_ID) REFERENCES CM_PURPOSE_VERSION (TENANT_ID, UUID) ON DELETE CASCADE,
  PRIMARY KEY (VERSION_ID, PROPERTY_KEY)
);

IF NOT EXISTS ( SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[CM_PII_CATEGORY_PROPERTY]') AND TYPE IN (N'U'))
CREATE TABLE CM_PII_CATEGORY_PROPERTY (
  PII_CATEGORY_ID  INTEGER       NOT NULL,
  PROPERTY_KEY     VARCHAR(255)  NOT NULL,
  PROPERTY_VALUE   VARCHAR(1023) NOT NULL,
  TENANT_ID        INTEGER       NOT NULL DEFAULT -1234,
  FOREIGN KEY (PII_CATEGORY_ID) REFERENCES CM_PII_CATEGORY(ID) ON DELETE CASCADE,
  PRIMARY KEY (PII_CATEGORY_ID, PROPERTY_KEY)
);

ALTER TABLE CM_SP_PURPOSE_ASSOC
  ADD CONSTRAINT CM_SP_PURPOSE_ASSOC_fk2 FOREIGN KEY (PURPOSE_ID, PURPOSE_VERSION_ID) REFERENCES CM_PURPOSE_VERSION (PURPOSE_ID, UUID) ON DELETE CASCADE;

ALTER TABLE CM_PURPOSE
  ADD CONSTRAINT CM_PURPOSE_LATEST_VER_fk FOREIGN KEY (ID, LATEST_VERSION_ID) REFERENCES CM_PURPOSE_VERSION (PURPOSE_ID, UUID);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'CM_PII_CATEGORY_UUID_IDX')
  CREATE INDEX CM_PII_CATEGORY_UUID_IDX ON CM_PII_CATEGORY (UUID);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'CM_PURPOSE_UUID_IDX')
  CREATE INDEX CM_PURPOSE_UUID_IDX ON CM_PURPOSE (UUID);
