-- Disable foreign key checks temporarily to avoid issues during DDL operations,
-- especially when adding columns or indexes that might interact with existing data.
-- Re-enable them at the end of the script.
SET FOREIGN_KEY_CHECKS = 0;

-- --- Table Creation ---

CREATE TABLE IF NOT EXISTS UM_RESOURCE_SHARING_POLICY (
    UM_ID INTEGER NOT NULL AUTO_INCREMENT,
    UM_RESOURCE_TYPE VARCHAR(255) NOT NULL,
    UM_RESOURCE_ID VARCHAR(36) NOT NULL,
    UM_INITIATING_ORG_ID VARCHAR(36) NOT NULL,
    UM_POLICY_HOLDING_ORG_ID VARCHAR(36) NOT NULL,
    UM_SHARING_POLICY VARCHAR(255) NOT NULL,
    PRIMARY KEY (UM_ID),
    FOREIGN KEY (UM_INITIATING_ORG_ID) REFERENCES UM_ORG(UM_ID) ON DELETE CASCADE,
    FOREIGN KEY (UM_POLICY_HOLDING_ORG_ID) REFERENCES UM_ORG(UM_ID) ON DELETE CASCADE
)ENGINE NDB;

CREATE TABLE IF NOT EXISTS UM_SHARED_RESOURCE_ATTRIBUTES (
    UM_ID INTEGER NOT NULL AUTO_INCREMENT,
    UM_RESOURCE_SHARING_POLICY_ID INTEGER NOT NULL,
    UM_SHARED_ATTRIBUTE_TYPE VARCHAR(255) NOT NULL,
    UM_SHARED_ATTRIBUTE_ID VARCHAR(36) NOT NULL,
    PRIMARY KEY (UM_ID),
    FOREIGN KEY (UM_RESOURCE_SHARING_POLICY_ID)
        REFERENCES UM_RESOURCE_SHARING_POLICY(UM_ID) ON DELETE CASCADE
)ENGINE NDB;

CREATE TABLE IF NOT EXISTS UM_HYBRID_USER_ROLE_RESTRICTED_EDIT_PERMISSIONS (
    UM_ID INTEGER AUTO_INCREMENT NOT NULL,
    UM_HYBRID_USER_ROLE_ID INTEGER NOT NULL,
    UM_HYBRID_USER_ROLE_TENANT_ID INTEGER NOT NULL,
    UM_EDIT_OPERATION VARCHAR(255) NOT NULL,
    UM_PERMITTED_ORG_ID VARCHAR(36) NOT NULL,
    PRIMARY KEY (UM_ID),
    FOREIGN KEY (UM_HYBRID_USER_ROLE_ID, UM_HYBRID_USER_ROLE_TENANT_ID)
        REFERENCES UM_HYBRID_USER_ROLE (UM_ID, UM_TENANT_ID)
        ON DELETE CASCADE
)ENGINE NDB;

CREATE TABLE IF NOT EXISTS KEY_STORE(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    TYPE VARCHAR(36) NOT NULL,
    PROVIDER VARCHAR(255),
    PASSWORD VARCHAR(1000),
    PRIVATE_KEY_ALIAS VARCHAR(255),
    PRIVATE_KEY_PASS VARCHAR(1000),
    CONTENT LONGBLOB NOT NULL,
    PUB_CERT_ID VARCHAR(36),
    TENANT_ID INTEGER NOT NULL,
    VERSION VARCHAR(15) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (NAME, TENANT_ID)
)ENGINE NDB;

-- --- Column Additions ---

-- Alter table UM_ORG_USER_ASSOCIATION to add UM_SHARED_TYPE
DROP PROCEDURE IF EXISTS ADD_UM_SHARED_TYPE_TO_UM_ORG_USER_ASSOCIATION;
DELIMITER $$
CREATE PROCEDURE ADD_UM_SHARED_TYPE_TO_UM_ORG_USER_ASSOCIATION()
BEGIN
    IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='UM_ORG_USER_ASSOCIATION' AND COLUMN_NAME='UM_SHARED_TYPE' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE `UM_ORG_USER_ASSOCIATION` ADD COLUMN `UM_SHARED_TYPE` VARCHAR(255) DEFAULT 'NOT SPECIFIED' NOT NULL;
    END IF;
END $$
DELIMITER ;
CALL ADD_UM_SHARED_TYPE_TO_UM_ORG_USER_ASSOCIATION();
DROP PROCEDURE IF EXISTS ADD_UM_SHARED_TYPE_TO_UM_ORG_USER_ASSOCIATION;

-- Alter table UM_ORG_USER_ASSOCIATION to add unique auto-incrementing UM_ID
DROP PROCEDURE IF EXISTS ADD_UM_ID_TO_UM_ORG_USER_ASSOCIATION;
DELIMITER $$
CREATE PROCEDURE ADD_UM_ID_TO_UM_ORG_USER_ASSOCIATION()
BEGIN
    -- Add UM_ID column if it doesn't exist
    IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='UM_ORG_USER_ASSOCIATION' AND COLUMN_NAME='UM_ID' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE `UM_ORG_USER_ASSOCIATION` ADD COLUMN `UM_ID` INTEGER AUTO_INCREMENT UNIQUE;
    ELSE
        IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'UM_ORG_USER_ASSOCIATION' AND INDEX_NAME = 'UM_ID' AND NON_UNIQUE = 0) THEN
            ALTER TABLE `UM_ORG_USER_ASSOCIATION` ADD UNIQUE (`UM_ID`);
        END IF;
    END IF;
END $$
DELIMITER ;
CALL ADD_UM_ID_TO_UM_ORG_USER_ASSOCIATION();
DROP PROCEDURE IF EXISTS ADD_UM_ID_TO_UM_ORG_USER_ASSOCIATION;


-- --- Index Creation ---

DROP PROCEDURE IF EXISTS CREATE_INDEX_IF_NOT_EXISTS;
DELIMITER $$
CREATE PROCEDURE CREATE_INDEX_IF_NOT_EXISTS(
    IN p_table_name VARCHAR(64),
    IN p_index_name VARCHAR(64),
    IN p_index_columns VARCHAR(1000)
)
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM INFORMATION_SCHEMA.STATISTICS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = p_table_name
          AND INDEX_NAME = p_index_name
    ) THEN
        SET @create_sql = CONCAT('CREATE INDEX ', p_index_name, ' ON ', p_table_name, ' ', p_index_columns);
        PREPARE stmt FROM @create_sql;
        EXECUTE stmt;
        DEALLOCATE PREPARE stmt;
    END IF;
END $$
DELIMITER ;

-- Call the helper procedure for each index
CALL CREATE_INDEX_IF_NOT_EXISTS('UM_RESOURCE_SHARING_POLICY', 'IDX_POLICY_HOLDING_ORG_ID', '(UM_POLICY_HOLDING_ORG_ID)');
CALL CREATE_INDEX_IF_NOT_EXISTS('UM_SHARED_RESOURCE_ATTRIBUTES', 'IDX_RESOURCE_SHARING_POLICY_ID', '(UM_RESOURCE_SHARING_POLICY_ID)');

-- Drop the helper procedure after all index creations are done.
DROP PROCEDURE IF EXISTS CREATE_INDEX_IF_NOT_EXISTS;

-- Re-enable foreign key checks now that all DDL operations are complete.
SET FOREIGN_KEY_CHECKS = 1;
