SET @index_exists := (
  SELECT COUNT(*) FROM (
    SELECT 1
    FROM INFORMATION_SCHEMA.STATISTICS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'REG_RESOURCE_PROPERTY'
    GROUP BY INDEX_NAME
    HAVING GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) = 'REG_TENANT_ID,REG_PROPERTY_ID'
  ) AS idx
);

SET @create_sql := IF(
  @index_exists = 0,
  'CREATE INDEX REG_RESC_PROP_BY_PROP_ID_TI USING HASH ON REG_RESOURCE_PROPERTY (REG_TENANT_ID, REG_PROPERTY_ID)',
  'SELECT "Index exists, skipping creation"'
);

PREPARE stmt FROM @create_sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
