IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_VC_TEMPLATE]') AND TYPE IN (N'U'))
CREATE TABLE IDN_VC_TEMPLATE (
    ID CHAR(36) NOT NULL,
    CURSOR_KEY INTEGER IDENTITY,
    TENANT_ID INTEGER NOT NULL,
    IDENTIFIER VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    FORMAT VARCHAR(64) NOT NULL,
    SIGNING_ALG VARCHAR(64) NOT NULL,
    OFFER_ID CHAR(36),
    EXPIRES_IN BIGINT,
    PRIMARY KEY (ID),
    CONSTRAINT IDN_VC_TEMPLATE_TENANT_IDENTIFIER_UNQ UNIQUE (TENANT_ID, IDENTIFIER)
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_VC_CLAIMS]') AND TYPE IN (N'U'))
CREATE TABLE IDN_VC_CLAIMS (
    ID INTEGER IDENTITY,
    NAME VARCHAR(255) NOT NULL,
    TYPE VARCHAR(32) NOT NULL,
    TEMPLATE_ID CHAR(36) NOT NULL,
    CLAIM_URI VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT IDN_VC_CLAIMS_UNQ UNIQUE (TEMPLATE_ID, NAME),
    FOREIGN KEY (TEMPLATE_ID) REFERENCES IDN_VC_TEMPLATE (ID) ON DELETE CASCADE
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_VC_NONCE]') AND TYPE IN (N'U'))
CREATE TABLE IDN_VC_NONCE (
    TENANT_ID    INTEGER       NOT NULL,
    NONCE        VARCHAR(255)  NOT NULL,
    EXPIRY_TIME  DATETIME      NOT NULL,
    PRIMARY KEY (TENANT_ID, NONCE)
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_OAUTH2_REFRESH_TOKEN]') AND TYPE IN (N'U'))
CREATE TABLE IDN_OAUTH2_REFRESH_TOKEN (
    REFRESH_TOKEN_ID VARCHAR (255),
    REFRESH_TOKEN VARCHAR(2048),
    CONSUMER_KEY_ID INTEGER,
    AUTHZ_USER VARCHAR (100),
    TENANT_ID INTEGER,
    USER_DOMAIN VARCHAR(50),
    GRANT_TYPE VARCHAR (50),
    REFRESH_TOKEN_TIME_CREATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    REFRESH_TOKEN_VALIDITY_PERIOD BIGINT,
    TOKEN_SCOPE_HASH VARCHAR(32),
    TOKEN_STATE VARCHAR(25) DEFAULT 'ACTIVE',
    SUBJECT_IDENTIFIER VARCHAR(255),
    REFRESH_TOKEN_HASH VARCHAR(512),
    IDP_ID INTEGER DEFAULT -1 NOT NULL,
    CONSENTED_TOKEN VARCHAR(6),
    AUTHORIZED_ORGANIZATION VARCHAR(36) DEFAULT 'NONE' NOT NULL,
    PRIMARY KEY (REFRESH_TOKEN_ID),
    FOREIGN KEY (CONSUMER_KEY_ID) REFERENCES IDN_OAUTH_CONSUMER_APPS(ID) ON DELETE CASCADE
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_OAUTH2_REFRESH_TOKEN_SCOPE]') AND TYPE IN (N'U'))
CREATE TABLE IDN_OAUTH2_REFRESH_TOKEN_SCOPE (
    REFRESH_TOKEN_ID VARCHAR (255),
    TOKEN_SCOPE VARCHAR (255),
    TENANT_ID INTEGER DEFAULT -1,
    PRIMARY KEY (REFRESH_TOKEN_ID, TOKEN_SCOPE),
    FOREIGN KEY (REFRESH_TOKEN_ID) REFERENCES IDN_OAUTH2_REFRESH_TOKEN(REFRESH_TOKEN_ID) ON DELETE CASCADE
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_OAUTH2_REVOKED_TOKENS]') AND TYPE IN (N'U'))
CREATE TABLE IDN_OAUTH2_REVOKED_TOKENS (
    UUID VARCHAR(255) NOT NULL,
    TOKEN_IDENTIFIER VARCHAR(2048) NOT NULL,
    CONSUMER_KEY VARCHAR(255) NOT NULL,
    TIME_CREATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EXPIRY_TIMESTAMP DATETIME NOT NULL,
    PRIMARY KEY (UUID)
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_SUBJECT_ENTITY_REVOKED_EVENT]') AND TYPE IN (N'U'))
CREATE TABLE IDN_SUBJECT_ENTITY_REVOKED_EVENT (
    EVENT_ID VARCHAR(255) NOT NULL,
    ENTITY_ID VARCHAR(255) NOT NULL,
    ENTITY_TYPE VARCHAR(100) NOT NULL,
    TIME_REVOKED DATETIME NOT NULL,
    TENANT_ID INTEGER DEFAULT -1,
    PRIMARY KEY (EVENT_ID),
    CONSTRAINT IDN_SUBJECT_ENTITY_REVOKED_EVENT_CONSTRAINT UNIQUE (ENTITY_ID, ENTITY_TYPE, TENANT_ID)
);

IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'IDX_IDN_VC_NONCE_EXPIRY_TIME')
    DROP INDEX [dbo].[IDN_VC_NONCE].[IDX_IDN_VC_NONCE_EXPIRY_TIME];
CREATE INDEX [IDX_IDN_VC_NONCE_EXPIRY_TIME] ON [dbo].[IDN_VC_NONCE] ([EXPIRY_TIME]);

-- IDN_AUTH_SESSION_STORE --
IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'IDX_IDN_AUTH_SSTR_TID_SID')
    DROP INDEX [dbo].[IDN_AUTH_SESSION_STORE].[IDX_IDN_AUTH_SSTR_TID_SID];
CREATE INDEX [IDX_IDN_AUTH_SSTR_TID_SID] ON [dbo].[IDN_AUTH_SESSION_STORE] ([TENANT_ID], [SESSION_ID]);

-- IDN_AUTH_SESSION_META_DATA --
IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'IDX_IDN_AUTH_SMD_PT_VAL_SID')
    DROP INDEX [dbo].[IDN_AUTH_SESSION_META_DATA].[IDX_IDN_AUTH_SMD_PT_VAL_SID];
CREATE INDEX [IDX_IDN_AUTH_SMD_PT_VAL_SID] ON [dbo].[IDN_AUTH_SESSION_META_DATA] ([PROPERTY_TYPE], [VALUE], [SESSION_ID]);

-- NON PERSISTENT ACCESS TOKEN INDEXES --
IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'IDX_TOKEN_CONSUMER')
    DROP INDEX [dbo].[IDN_OAUTH2_REVOKED_TOKENS].[IDX_TOKEN_CONSUMER];
CREATE INDEX [IDX_TOKEN_CONSUMER] ON [dbo].[IDN_OAUTH2_REVOKED_TOKENS] ([TOKEN_IDENTIFIER], [CONSUMER_KEY]);

IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'IDX_ENTITY_TIME_REVOKED')
    DROP INDEX [dbo].[IDN_SUBJECT_ENTITY_REVOKED_EVENT].[IDX_ENTITY_TIME_REVOKED];
CREATE INDEX [IDX_ENTITY_TIME_REVOKED] ON [dbo].[IDN_SUBJECT_ENTITY_REVOKED_EVENT] ([ENTITY_ID], [TIME_REVOKED]);

IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'IDX_REFRESH_TOKEN_HASH')
    DROP INDEX [dbo].[IDN_OAUTH2_REFRESH_TOKEN].[IDX_REFRESH_TOKEN_HASH];
CREATE INDEX [IDX_REFRESH_TOKEN_HASH] ON [dbo].[IDN_OAUTH2_REFRESH_TOKEN] ([REFRESH_TOKEN_HASH]);

IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'IDX_AUTHZ_USER_TENANT_DOMAIN_STATE')
    DROP INDEX [dbo].[IDN_OAUTH2_REFRESH_TOKEN].[IDX_AUTHZ_USER_TENANT_DOMAIN_STATE];
CREATE INDEX [IDX_AUTHZ_USER_TENANT_DOMAIN_STATE] ON [dbo].[IDN_OAUTH2_REFRESH_TOKEN] ([AUTHZ_USER], [TENANT_ID], [USER_DOMAIN], [TOKEN_STATE]);

IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'IDX_CONSUMER_KEY_STATE')
    DROP INDEX [dbo].[IDN_OAUTH2_REFRESH_TOKEN].[IDX_CONSUMER_KEY_STATE];
CREATE INDEX [IDX_CONSUMER_KEY_STATE] ON [dbo].[IDN_OAUTH2_REFRESH_TOKEN] ([CONSUMER_KEY_ID], [TOKEN_STATE]);

IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'IDX_CONSUMER_USER_SCOPE_IDP')
    DROP INDEX [dbo].[IDN_OAUTH2_REFRESH_TOKEN].[IDX_CONSUMER_USER_SCOPE_IDP];
CREATE INDEX [IDX_CONSUMER_USER_SCOPE_IDP] ON [dbo].[IDN_OAUTH2_REFRESH_TOKEN] ([CONSUMER_KEY_ID], [AUTHZ_USER], [TENANT_ID], [USER_DOMAIN], [TOKEN_SCOPE_HASH], [TOKEN_STATE], [IDP_ID]);

-- IDN_OAUTH2_CIBA_AUTH_CODE --
IF NOT EXISTS (
    SELECT * FROM sys.columns
    WHERE object_id = OBJECT_ID(N'[dbo].[IDN_OAUTH2_CIBA_AUTH_CODE]')
    AND name = N'RESOLVED_USER_ID'
)
BEGIN
    ALTER TABLE [DBO].[IDN_OAUTH2_CIBA_AUTH_CODE] ADD [RESOLVED_USER_ID] CHAR(36)
END;

IF NOT EXISTS (
    SELECT * FROM sys.columns
    WHERE object_id = OBJECT_ID(N'[dbo].[IDN_OAUTH2_CIBA_AUTH_CODE]')
    AND name = N'REQUESTED_ACTOR'
)
BEGIN
    ALTER TABLE [DBO].[IDN_OAUTH2_CIBA_AUTH_CODE] ADD [REQUESTED_ACTOR] VARCHAR(255) DEFAULT NULL
END;

INSERT INTO IDN_CONFIG_TYPE (ID, NAME, DESCRIPTION)
SELECT T.ID, T.NAME, T.DESCRIPTION
FROM (
    VALUES
    ('08fbc096-56c5-4ae6-9edc-54198a07e0dc', 'ISSUER_USAGE_SCOPE', 'A resource type to store issuer usage scope for organizations.')
) AS T (ID, NAME, DESCRIPTION)
WHERE NOT EXISTS (SELECT 1 FROM IDN_CONFIG_TYPE S WHERE S.ID = T.ID);

UPDATE SCOPE
SET NAME = CASE NAME
    WHEN 'internal_user_mgt_view' THEN 'internal_user_credential_mgt_view'
    WHEN 'internal_user_mgt_delete' THEN 'internal_user_credential_mgt_delete'
    WHEN 'internal_org_user_mgt_view' THEN 'internal_org_user_credential_mgt_view'
    WHEN 'internal_org_user_mgt_delete' THEN 'internal_org_user_credential_mgt_delete'
END
WHERE NAME IN (
    'internal_user_mgt_view',
    'internal_user_mgt_delete',
    'internal_org_user_mgt_view',
    'internal_org_user_mgt_delete'
)
AND API_ID IN (
    SELECT ID FROM API_RESOURCE WHERE IDENTIFIER IN (
        '/api/server/v1/users/(.*)/credentials',
        '/o/api/server/v1/users/(.*)/credentials'
    )
);

IF NOT EXISTS (SELECT * FROM IDN_SECRET_TYPE WHERE id = 'f47bce92-3d81-4a06-b7e5-29c1d830f5a2')
BEGIN
  INSERT INTO IDN_SECRET_TYPE (ID, NAME, DESCRIPTION)
  VALUES ('f47bce92-3d81-4a06-b7e5-29c1d830f5a2', 'SMS_PROVIDER_SECRET_PROPERTIES', 'Secret type to uniquely identify secrets relevant to SMS provider properties')
END;
