CREATE TABLE IF NOT EXISTS IDN_VC_TEMPLATE (
    ID CHAR(36) NOT NULL,
    CURSOR_KEY INTEGER NOT NULL AUTO_INCREMENT,
    TENANT_ID INTEGER NOT NULL,
    IDENTIFIER VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    FORMAT VARCHAR(64) NOT NULL,
    SIGNING_ALG VARCHAR(64) NOT NULL,
    OFFER_ID CHAR(36),
    EXPIRES_IN BIGINT,
    PRIMARY KEY (ID),
    CONSTRAINT IDN_VC_TEMPLATE_TENANT_IDENTIFIER_UNQ UNIQUE (TENANT_ID, IDENTIFIER),
    UNIQUE KEY IDN_VC_TEMPLATE_CURSOR_KEY_UNQ (CURSOR_KEY)
)DEFAULT CHARACTER SET latin1 ENGINE INNODB;

CREATE TABLE IF NOT EXISTS IDN_VC_CLAIMS (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    TYPE VARCHAR(32) NOT NULL,
    TEMPLATE_ID CHAR(36) NOT NULL,
    CLAIM_URI VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT IDN_VC_CLAIMS_UNQ UNIQUE (TEMPLATE_ID, NAME),
    FOREIGN KEY (TEMPLATE_ID) REFERENCES IDN_VC_TEMPLATE (ID) ON DELETE CASCADE
)DEFAULT CHARACTER SET latin1 ENGINE INNODB;

CREATE TABLE IF NOT EXISTS IDN_VC_NONCE (
    TENANT_ID    INTEGER       NOT NULL,
    NONCE        VARCHAR(255)  NOT NULL,
    EXPIRY_TIME  TIMESTAMP     NOT NULL,
    PRIMARY KEY (TENANT_ID, NONCE)
)DEFAULT CHARACTER SET latin1 ENGINE INNODB;

CREATE TABLE IF NOT EXISTS IDN_OAUTH2_REFRESH_TOKEN (
    REFRESH_TOKEN_ID VARCHAR (255),
    REFRESH_TOKEN VARCHAR(2048),
    CONSUMER_KEY_ID INTEGER,
    AUTHZ_USER VARCHAR (100),
    TENANT_ID INTEGER,
    USER_DOMAIN VARCHAR(50),
    GRANT_TYPE VARCHAR (50),
    REFRESH_TOKEN_TIME_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    REFRESH_TOKEN_VALIDITY_PERIOD BIGINT,
    TOKEN_SCOPE_HASH VARCHAR(32),
    TOKEN_STATE VARCHAR(25) DEFAULT 'ACTIVE',
    SUBJECT_IDENTIFIER VARCHAR(255),
    REFRESH_TOKEN_HASH VARCHAR(512),
    IDP_ID INTEGER DEFAULT -1 NOT NULL,
    CONSENTED_TOKEN VARCHAR(6),
    AUTHORIZED_ORGANIZATION VARCHAR(36) DEFAULT 'NONE' NOT NULL,
    PRIMARY KEY (REFRESH_TOKEN_ID),
    FOREIGN KEY (CONSUMER_KEY_ID) REFERENCES IDN_OAUTH_CONSUMER_APPS(ID) ON DELETE CASCADE
)ENGINE INNODB;

CREATE TABLE IF NOT EXISTS IDN_OAUTH2_REFRESH_TOKEN_SCOPE (
    REFRESH_TOKEN_ID VARCHAR (255),
    TOKEN_SCOPE VARCHAR (255),
    TENANT_ID INTEGER DEFAULT -1,
    PRIMARY KEY (REFRESH_TOKEN_ID, TOKEN_SCOPE),
    FOREIGN KEY (REFRESH_TOKEN_ID) REFERENCES IDN_OAUTH2_REFRESH_TOKEN(REFRESH_TOKEN_ID) ON DELETE CASCADE
)ENGINE INNODB;

CREATE TABLE IF NOT EXISTS IDN_OAUTH2_REVOKED_TOKENS (
    UUID VARCHAR(255) NOT NULL,
    TOKEN_IDENTIFIER VARCHAR(2048) NOT NULL,
    CONSUMER_KEY VARCHAR(255) NOT NULL,
    TIME_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EXPIRY_TIMESTAMP TIMESTAMP NOT NULL,
    PRIMARY KEY (UUID)
)ENGINE INNODB;

CREATE TABLE IF NOT EXISTS IDN_SUBJECT_ENTITY_REVOKED_EVENT (
    EVENT_ID VARCHAR(255) NOT NULL,
    ENTITY_ID VARCHAR(255) NOT NULL,
    ENTITY_TYPE VARCHAR(100) NOT NULL,
    TIME_REVOKED TIMESTAMP NOT NULL,
    TENANT_ID INTEGER DEFAULT -1,
    PRIMARY KEY (EVENT_ID),
    CONSTRAINT IDN_SUBJECT_ENTITY_REVOKED_EVENT_CONSTRAINT UNIQUE (ENTITY_ID, ENTITY_TYPE, TENANT_ID)
)ENGINE INNODB;

DROP PROCEDURE IF EXISTS CREATE_INDEX_IF_NOT_EXISTS;
DELIMITER $$
CREATE PROCEDURE CREATE_INDEX_IF_NOT_EXISTS(
    IN p_table_name VARCHAR(64),
    IN p_index_name VARCHAR(64),
    IN p_index_columns VARCHAR(1000)
)
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM INFORMATION_SCHEMA.STATISTICS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = p_table_name
          AND INDEX_NAME = p_index_name
    ) THEN
        SET @create_sql = CONCAT('CREATE INDEX ', p_index_name, ' ON ', p_table_name, ' ', p_index_columns);
        PREPARE stmt FROM @create_sql;
        EXECUTE stmt;
        DEALLOCATE PREPARE stmt;
    END IF;
END $$
DELIMITER ;

CALL CREATE_INDEX_IF_NOT_EXISTS('IDN_VC_NONCE', 'IDX_IDN_VC_NONCE_EXPIRY_TIME', '(EXPIRY_TIME)');

-- IDN_AUTH_SESSION_STORE --
CALL CREATE_INDEX_IF_NOT_EXISTS('IDN_AUTH_SESSION_STORE', 'IDX_IDN_AUTH_SSTR_TID_SID', '(TENANT_ID, SESSION_ID)');

-- IDN_AUTH_SESSION_META_DATA --
CALL CREATE_INDEX_IF_NOT_EXISTS('IDN_AUTH_SESSION_META_DATA', 'IDX_IDN_AUTH_SMD_PT_VAL_SID', '(PROPERTY_TYPE, VALUE, SESSION_ID)');

-- NON PERSISTENT ACCESS TOKEN INDEXES --
CALL CREATE_INDEX_IF_NOT_EXISTS('IDN_OAUTH2_REVOKED_TOKENS', 'IDX_TOKEN_CONSUMER', '(TOKEN_IDENTIFIER(255), CONSUMER_KEY)');
CALL CREATE_INDEX_IF_NOT_EXISTS('IDN_SUBJECT_ENTITY_REVOKED_EVENT', 'IDX_ENTITY_TIME_REVOKED', '(ENTITY_ID, TIME_REVOKED)');
CALL CREATE_INDEX_IF_NOT_EXISTS('IDN_OAUTH2_REFRESH_TOKEN', 'IDX_REFRESH_TOKEN_HASH', '(REFRESH_TOKEN_HASH)');
CALL CREATE_INDEX_IF_NOT_EXISTS('IDN_OAUTH2_REFRESH_TOKEN', 'IDX_AUTHZ_USER_TENANT_DOMAIN_STATE', '(AUTHZ_USER, TENANT_ID, USER_DOMAIN, TOKEN_STATE)');
CALL CREATE_INDEX_IF_NOT_EXISTS('IDN_OAUTH2_REFRESH_TOKEN', 'IDX_CONSUMER_KEY_STATE', '(CONSUMER_KEY_ID, TOKEN_STATE)');
CALL CREATE_INDEX_IF_NOT_EXISTS('IDN_OAUTH2_REFRESH_TOKEN', 'IDX_CONSUMER_USER_SCOPE_IDP', '(CONSUMER_KEY_ID, AUTHZ_USER, TENANT_ID, USER_DOMAIN, TOKEN_SCOPE_HASH, TOKEN_STATE, IDP_ID)');

DROP PROCEDURE IF EXISTS CREATE_INDEX_IF_NOT_EXISTS;

-- IDN_OAUTH2_CIBA_AUTH_CODE --
DROP PROCEDURE IF EXISTS ALTER_IDN_OAUTH2_CIBA_AUTH_CODE;
DELIMITER $$
CREATE PROCEDURE ALTER_IDN_OAUTH2_CIBA_AUTH_CODE()
BEGIN
    IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='IDN_OAUTH2_CIBA_AUTH_CODE' AND COLUMN_NAME='RESOLVED_USER_ID' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE `IDN_OAUTH2_CIBA_AUTH_CODE` ADD COLUMN `RESOLVED_USER_ID` CHAR(36);
    END IF;
    IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='IDN_OAUTH2_CIBA_AUTH_CODE' AND COLUMN_NAME='REQUESTED_ACTOR' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE `IDN_OAUTH2_CIBA_AUTH_CODE` ADD COLUMN `REQUESTED_ACTOR` VARCHAR(255) DEFAULT NULL;
    END IF;
END $$
DELIMITER ;
CALL ALTER_IDN_OAUTH2_CIBA_AUTH_CODE();
DROP PROCEDURE IF EXISTS ALTER_IDN_OAUTH2_CIBA_AUTH_CODE;

INSERT IGNORE INTO IDN_CONFIG_TYPE (ID, NAME, DESCRIPTION) VALUES
('08fbc096-56c5-4ae6-9edc-54198a07e0dc', 'ISSUER_USAGE_SCOPE', 'A resource type to store issuer usage scope for organizations.');

UPDATE SCOPE
SET NAME = CASE NAME
    WHEN 'internal_user_mgt_view' THEN 'internal_user_credential_mgt_view'
    WHEN 'internal_user_mgt_delete' THEN 'internal_user_credential_mgt_delete'
    WHEN 'internal_org_user_mgt_view' THEN 'internal_org_user_credential_mgt_view'
    WHEN 'internal_org_user_mgt_delete' THEN 'internal_org_user_credential_mgt_delete'
END
WHERE NAME IN (
    'internal_user_mgt_view',
    'internal_user_mgt_delete',
    'internal_org_user_mgt_view',
    'internal_org_user_mgt_delete'
)
AND API_ID IN (
    SELECT ID FROM API_RESOURCE WHERE IDENTIFIER IN (
        '/api/server/v1/users/(.*)/credentials',
        '/o/api/server/v1/users/(.*)/credentials'
    )
);

INSERT IGNORE INTO IDN_SECRET_TYPE (ID, NAME, DESCRIPTION) VALUES
('f47bce92-3d81-4a06-b7e5-29c1d830f5a2', 'SMS_PROVIDER_SECRET_PROPERTIES', 'Secret type to uniquely identify secrets relevant to SMS provider properties');
