DECLARE
    table_exists NUMBER;
    sequence_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_VC_TEMPLATE';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_VC_TEMPLATE (
            ID CHAR(36) NOT NULL,
            CURSOR_KEY INTEGER NOT NULL,
            TENANT_ID INTEGER NOT NULL,
            IDENTIFIER VARCHAR(255) NOT NULL,
            DISPLAY_NAME VARCHAR(255) NOT NULL,
            DESCRIPTION VARCHAR(255),
            FORMAT VARCHAR(64) NOT NULL,
            SIGNING_ALG VARCHAR(64) NOT NULL,
            OFFER_ID CHAR(36),
            EXPIRES_IN NUMBER(19),
            PRIMARY KEY (ID),
            CONSTRAINT IDN_VC_TEMPLATE_UNIQUE_CONSTRAINT UNIQUE (TENANT_ID, IDENTIFIER)
        )';
    END IF;
    SELECT COUNT(*) INTO sequence_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_VC_TEMPLATE_CURSOR_KEY_SEQ';
    IF sequence_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_VC_TEMPLATE_CURSOR_KEY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/
DECLARE
    trig_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO trig_exists FROM ALL_TRIGGERS WHERE TRIGGER_NAME = 'IDN_VC_TEMPLATE_CURSOR_KEY_TRIG';
    IF trig_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE OR REPLACE TRIGGER IDN_VC_TEMPLATE_CURSOR_KEY_TRIG
        BEFORE INSERT ON IDN_VC_TEMPLATE
        REFERENCING NEW AS NEW
        FOR EACH ROW
        BEGIN
            SELECT IDN_VC_TEMPLATE_CURSOR_KEY_SEQ.nextval INTO :NEW.CURSOR_KEY FROM dual;
        END;';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
    sequence_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_VC_CLAIMS';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_VC_CLAIMS (
            ID INTEGER NOT NULL,
            NAME VARCHAR(255) NOT NULL,
            TYPE VARCHAR(32) NOT NULL,
            TEMPLATE_ID CHAR(36) NOT NULL,
            CLAIM_URI VARCHAR(255) NOT NULL,
            PRIMARY KEY (ID),
            CONSTRAINT IDN_VC_CLAIMS_UNIQUE_CONSTRAINT UNIQUE (TEMPLATE_ID, NAME),
            FOREIGN KEY (TEMPLATE_ID) REFERENCES IDN_VC_TEMPLATE (ID) ON DELETE CASCADE
        )';
    END IF;
    SELECT COUNT(*) INTO sequence_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_VC_CLAIMS_SEQ';
    IF sequence_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_VC_CLAIMS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/
DECLARE
    trig_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO trig_exists FROM ALL_TRIGGERS WHERE TRIGGER_NAME = 'IDN_VC_CLAIMS_TRIG';
    IF trig_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE OR REPLACE TRIGGER IDN_VC_CLAIMS_TRIG
        BEFORE INSERT ON IDN_VC_CLAIMS
        REFERENCING NEW AS NEW
        FOR EACH ROW
        BEGIN
            SELECT IDN_VC_CLAIMS_SEQ.nextval INTO :NEW.ID FROM dual;
        END;';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_VC_NONCE';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_VC_NONCE (
            TENANT_ID    INTEGER       NOT NULL,
            NONCE        VARCHAR2(255) NOT NULL,
            EXPIRY_TIME  TIMESTAMP     NOT NULL,
            PRIMARY KEY (TENANT_ID, NONCE)
        )';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_OAUTH2_REFRESH_TOKEN';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_OAUTH2_REFRESH_TOKEN (
            REFRESH_TOKEN_ID VARCHAR2(255),
            REFRESH_TOKEN VARCHAR2(2048),
            CONSUMER_KEY_ID INTEGER,
            AUTHZ_USER VARCHAR2(100),
            TENANT_ID INTEGER,
            USER_DOMAIN VARCHAR2(50),
            GRANT_TYPE VARCHAR2(50),
            REFRESH_TOKEN_TIME_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            REFRESH_TOKEN_VALIDITY_PERIOD NUMBER(19),
            TOKEN_SCOPE_HASH VARCHAR2(32),
            TOKEN_STATE VARCHAR2(25) DEFAULT ''ACTIVE'',
            SUBJECT_IDENTIFIER VARCHAR2(255),
            REFRESH_TOKEN_HASH VARCHAR2(512),
            IDP_ID INTEGER DEFAULT -1 NOT NULL,
            CONSENTED_TOKEN VARCHAR2(6),
            AUTHORIZED_ORGANIZATION VARCHAR2(36) DEFAULT ''NONE'' NOT NULL,
            PRIMARY KEY (REFRESH_TOKEN_ID),
            FOREIGN KEY (CONSUMER_KEY_ID) REFERENCES IDN_OAUTH_CONSUMER_APPS(ID) ON DELETE CASCADE
        )';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_OAUTH2_REFRESH_TOKEN_SCOPE';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_OAUTH2_REFRESH_TOKEN_SCOPE (
            REFRESH_TOKEN_ID VARCHAR2(255),
            TOKEN_SCOPE VARCHAR2(255),
            TENANT_ID INTEGER DEFAULT -1,
            PRIMARY KEY (REFRESH_TOKEN_ID, TOKEN_SCOPE),
            FOREIGN KEY (REFRESH_TOKEN_ID) REFERENCES IDN_OAUTH2_REFRESH_TOKEN(REFRESH_TOKEN_ID) ON DELETE CASCADE
        )';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_OAUTH2_REVOKED_TOKENS';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_OAUTH2_REVOKED_TOKENS (
            UUID VARCHAR2(255) NOT NULL,
            TOKEN_IDENTIFIER VARCHAR2(2048) NOT NULL,
            CONSUMER_KEY VARCHAR2(255) NOT NULL,
            TIME_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            EXPIRY_TIMESTAMP TIMESTAMP NOT NULL,
            PRIMARY KEY (UUID)
        )';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_SUBJECT_ENTITY_REVOKED_EVENT';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_SUBJECT_ENTITY_REVOKED_EVENT (
            EVENT_ID VARCHAR2(255) NOT NULL,
            ENTITY_ID VARCHAR2(255) NOT NULL,
            ENTITY_TYPE VARCHAR2(100) NOT NULL,
            TIME_REVOKED TIMESTAMP NOT NULL,
            TENANT_ID INTEGER DEFAULT -1,
            PRIMARY KEY (EVENT_ID),
            CONSTRAINT IDN_SUBJECT_ENTITY_REVOKED_EVENT_CONSTRAINT UNIQUE (ENTITY_ID, ENTITY_TYPE, TENANT_ID)
        )';
    END IF;
END;
/

DECLARE
    index_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO index_exists FROM ALL_INDEXES WHERE INDEX_NAME = 'IDX_IDN_VC_NONCE_EXPIRY_TIME';
    IF index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_IDN_VC_NONCE_EXPIRY_TIME ON IDN_VC_NONCE (EXPIRY_TIME)';
    END IF;
END;
/

-- IDN_AUTH_SESSION_STORE --
DECLARE
    index_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO index_exists FROM ALL_INDEXES WHERE INDEX_NAME = 'IDX_IDN_AUTH_SSTR_TID_SID';
    IF index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_IDN_AUTH_SSTR_TID_SID ON IDN_AUTH_SESSION_STORE (TENANT_ID, SESSION_ID)';
    END IF;
END;
/

-- IDN_AUTH_SESSION_META_DATA --
DECLARE
    index_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO index_exists FROM ALL_INDEXES WHERE INDEX_NAME = 'IDX_IDN_AUTH_SMD_PT_VAL_SID';
    IF index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_IDN_AUTH_SMD_PT_VAL_SID ON IDN_AUTH_SESSION_META_DATA (PROPERTY_TYPE, VALUE, SESSION_ID)';
    END IF;
END;
/

-- IDN_SECRET --
DECLARE
    column_exists NUMBER;
    nullable_flag VARCHAR2(1);
BEGIN
    SELECT COUNT(*) INTO column_exists FROM ALL_TAB_COLUMNS WHERE TABLE_NAME = 'IDN_SECRET' AND COLUMN_NAME = 'SECRET_VALUE_CLOB';
    IF column_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_SECRET ADD SECRET_VALUE_CLOB CLOB';
    END IF;

    SELECT NULLABLE INTO nullable_flag FROM ALL_TAB_COLUMNS WHERE TABLE_NAME = 'IDN_SECRET' AND COLUMN_NAME = 'SECRET_VALUE';
    IF nullable_flag = 'N' THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_SECRET MODIFY SECRET_VALUE NULL';
    END IF;
END;
/

-- NON PERSISTENT ACCESS TOKEN INDEXES --
DECLARE
    index_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO index_exists FROM ALL_INDEXES WHERE INDEX_NAME = 'IDX_TOKEN_CONSUMER';
    IF index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_TOKEN_CONSUMER ON IDN_OAUTH2_REVOKED_TOKENS (TOKEN_IDENTIFIER, CONSUMER_KEY)';
    END IF;
END;
/

DECLARE
    index_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO index_exists FROM ALL_INDEXES WHERE INDEX_NAME = 'IDX_ENTITY_TIME_REVOKED';
    IF index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_ENTITY_TIME_REVOKED ON IDN_SUBJECT_ENTITY_REVOKED_EVENT (ENTITY_ID, TIME_REVOKED)';
    END IF;
END;
/

DECLARE
    index_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO index_exists FROM ALL_INDEXES WHERE INDEX_NAME = 'IDX_REFRESH_TOKEN_HASH';
    IF index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_REFRESH_TOKEN_HASH ON IDN_OAUTH2_REFRESH_TOKEN (REFRESH_TOKEN_HASH)';
    END IF;
END;
/

DECLARE
    index_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO index_exists FROM ALL_INDEXES WHERE INDEX_NAME = 'IDX_AUTHZ_USER_TENANT_DOMAIN_STATE';
    IF index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_AUTHZ_USER_TENANT_DOMAIN_STATE ON IDN_OAUTH2_REFRESH_TOKEN (AUTHZ_USER, TENANT_ID, USER_DOMAIN, TOKEN_STATE)';
    END IF;
END;
/

DECLARE
    index_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO index_exists FROM ALL_INDEXES WHERE INDEX_NAME = 'IDX_CONSUMER_KEY_STATE';
    IF index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_CONSUMER_KEY_STATE ON IDN_OAUTH2_REFRESH_TOKEN (CONSUMER_KEY_ID, TOKEN_STATE)';
    END IF;
END;
/

DECLARE
    index_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO index_exists FROM ALL_INDEXES WHERE INDEX_NAME = 'IDX_CONSUMER_USER_SCOPE_IDP';
    IF index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_CONSUMER_USER_SCOPE_IDP ON IDN_OAUTH2_REFRESH_TOKEN (CONSUMER_KEY_ID, AUTHZ_USER, TENANT_ID, USER_DOMAIN, TOKEN_SCOPE_HASH, TOKEN_STATE, IDP_ID)';
    END IF;
END;
/

-- IDN_OAUTH2_CIBA_AUTH_CODE --
DECLARE
    column_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO column_count FROM ALL_TAB_COLUMNS
    WHERE OWNER = (SELECT USER FROM DUAL)
        AND TABLE_NAME = 'IDN_OAUTH2_CIBA_AUTH_CODE'
        AND COLUMN_NAME = 'RESOLVED_USER_ID';
    IF column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_OAUTH2_CIBA_AUTH_CODE ADD RESOLVED_USER_ID CHAR(36)';
    END IF;

    SELECT COUNT(*) INTO column_count FROM ALL_TAB_COLUMNS
    WHERE OWNER = (SELECT USER FROM DUAL)
        AND TABLE_NAME = 'IDN_OAUTH2_CIBA_AUTH_CODE'
        AND COLUMN_NAME = 'REQUESTED_ACTOR';
    IF column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_OAUTH2_CIBA_AUTH_CODE ADD REQUESTED_ACTOR VARCHAR2(255) DEFAULT NULL';
    END IF;
END;
/

INSERT INTO IDN_CONFIG_TYPE (ID, NAME, DESCRIPTION)
SELECT '08fbc096-56c5-4ae6-9edc-54198a07e0dc', 'ISSUER_USAGE_SCOPE', 'A resource type to store issuer usage scope for organizations.' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM IDN_CONFIG_TYPE WHERE id = '08fbc096-56c5-4ae6-9edc-54198a07e0dc' OR name = 'ISSUER_USAGE_SCOPE')
/

UPDATE SCOPE
SET NAME = CASE NAME
    WHEN 'internal_user_mgt_view' THEN 'internal_user_credential_mgt_view'
    WHEN 'internal_user_mgt_delete' THEN 'internal_user_credential_mgt_delete'
    WHEN 'internal_org_user_mgt_view' THEN 'internal_org_user_credential_mgt_view'
    WHEN 'internal_org_user_mgt_delete' THEN 'internal_org_user_credential_mgt_delete'
END
WHERE NAME IN (
    'internal_user_mgt_view',
    'internal_user_mgt_delete',
    'internal_org_user_mgt_view',
    'internal_org_user_mgt_delete'
)
AND API_ID IN (
    SELECT ID FROM API_RESOURCE WHERE IDENTIFIER IN (
        '/api/server/v1/users/(.*)/credentials',
        '/o/api/server/v1/users/(.*)/credentials'
    )
)
/

INSERT INTO IDN_SECRET_TYPE (ID, NAME, DESCRIPTION)
SELECT 'f47bce92-3d81-4a06-b7e5-29c1d830f5a2', 'SMS_PROVIDER_SECRET_PROPERTIES', 'Secret type to uniquely identify secrets relevant to SMS provider properties' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM IDN_SECRET_TYPE WHERE id = 'f47bce92-3d81-4a06-b7e5-29c1d830f5a2')
/
