CREATE SEQUENCE IF NOT EXISTS IDN_VC_TEMPLATE_CURSOR_KEY_SEQ;
CREATE TABLE IF NOT EXISTS IDN_VC_TEMPLATE (
    ID CHAR(36) NOT NULL,
    CURSOR_KEY INTEGER DEFAULT NEXTVAL('IDN_VC_TEMPLATE_CURSOR_KEY_SEQ'),
    TENANT_ID INTEGER NOT NULL,
    IDENTIFIER VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    FORMAT VARCHAR(64) NOT NULL,
    SIGNING_ALG VARCHAR(64) NOT NULL,
    OFFER_ID CHAR(36),
    EXPIRES_IN BIGINT,
    PRIMARY KEY (ID),
    CONSTRAINT IDN_VC_TEMPLATE_TENANT_IDENTIFIER_UNQ UNIQUE (TENANT_ID, IDENTIFIER)
);

CREATE SEQUENCE IF NOT EXISTS IDN_VC_CLAIMS_SEQ;
CREATE TABLE IF NOT EXISTS IDN_VC_CLAIMS (
    ID INTEGER DEFAULT NEXTVAL('IDN_VC_CLAIMS_SEQ'),
    NAME VARCHAR(255) NOT NULL,
    TYPE VARCHAR(32) NOT NULL,
    TEMPLATE_ID CHAR(36) NOT NULL,
    CLAIM_URI VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT IDN_VC_CLAIMS_UNQ UNIQUE (TEMPLATE_ID, NAME),
    FOREIGN KEY (TEMPLATE_ID) REFERENCES IDN_VC_TEMPLATE (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS IDN_VC_NONCE (
    TENANT_ID    INTEGER       NOT NULL,
    NONCE        VARCHAR(255)  NOT NULL,
    EXPIRY_TIME  TIMESTAMP     NOT NULL,
    PRIMARY KEY (TENANT_ID, NONCE)
);

CREATE TABLE IF NOT EXISTS IDN_OAUTH2_REFRESH_TOKEN (
    REFRESH_TOKEN_ID VARCHAR (255),
    REFRESH_TOKEN VARCHAR(2048),
    CONSUMER_KEY_ID INTEGER,
    AUTHZ_USER VARCHAR (100),
    TENANT_ID INTEGER,
    USER_DOMAIN VARCHAR(50),
    GRANT_TYPE VARCHAR (50),
    REFRESH_TOKEN_TIME_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    REFRESH_TOKEN_VALIDITY_PERIOD BIGINT,
    TOKEN_SCOPE_HASH VARCHAR(32),
    TOKEN_STATE VARCHAR(25) DEFAULT 'ACTIVE',
    SUBJECT_IDENTIFIER VARCHAR(255),
    REFRESH_TOKEN_HASH VARCHAR(512),
    IDP_ID INTEGER DEFAULT -1 NOT NULL,
    CONSENTED_TOKEN VARCHAR(6),
    AUTHORIZED_ORGANIZATION VARCHAR(36) DEFAULT 'NONE' NOT NULL,
    PRIMARY KEY (REFRESH_TOKEN_ID),
    FOREIGN KEY (CONSUMER_KEY_ID) REFERENCES IDN_OAUTH_CONSUMER_APPS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS IDN_OAUTH2_REFRESH_TOKEN_SCOPE (
    REFRESH_TOKEN_ID VARCHAR (255),
    TOKEN_SCOPE VARCHAR (255),
    TENANT_ID INTEGER DEFAULT -1,
    PRIMARY KEY (REFRESH_TOKEN_ID, TOKEN_SCOPE),
    FOREIGN KEY (REFRESH_TOKEN_ID) REFERENCES IDN_OAUTH2_REFRESH_TOKEN(REFRESH_TOKEN_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS IDN_OAUTH2_REVOKED_TOKENS (
    UUID VARCHAR(255) NOT NULL,
    TOKEN_IDENTIFIER VARCHAR(2048) NOT NULL,
    CONSUMER_KEY VARCHAR(255) NOT NULL,
    TIME_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EXPIRY_TIMESTAMP TIMESTAMP NOT NULL,
    PRIMARY KEY (UUID)
);

CREATE TABLE IF NOT EXISTS IDN_SUBJECT_ENTITY_REVOKED_EVENT (
    EVENT_ID VARCHAR(255) NOT NULL,
    ENTITY_ID VARCHAR(255) NOT NULL,
    ENTITY_TYPE VARCHAR(100) NOT NULL,
    TIME_REVOKED TIMESTAMP NOT NULL,
    TENANT_ID INTEGER DEFAULT -1,
    PRIMARY KEY (EVENT_ID),
    CONSTRAINT IDN_SUBJECT_ENTITY_REVOKED_EVENT_CONSTRAINT UNIQUE (ENTITY_ID, ENTITY_TYPE, TENANT_ID)
);

-- IDN_VC_NONCE --
CREATE INDEX IF NOT EXISTS IDX_IDN_VC_NONCE_EXPIRY_TIME ON IDN_VC_NONCE (EXPIRY_TIME);

-- IDN_AUTH_SESSION_STORE --
CREATE INDEX IF NOT EXISTS IDX_IDN_AUTH_SSTR_TID_SID ON IDN_AUTH_SESSION_STORE (TENANT_ID, SESSION_ID);

-- IDN_AUTH_SESSION_META_DATA --
CREATE INDEX IF NOT EXISTS IDX_IDN_AUTH_SMD_PT_VAL_SID ON IDN_AUTH_SESSION_META_DATA (PROPERTY_TYPE, VALUE, SESSION_ID);

-- NON PERSISTENT ACCESS TOKEN INDEXES --
CREATE INDEX IF NOT EXISTS IDX_TOKEN_CONSUMER ON IDN_OAUTH2_REVOKED_TOKENS (TOKEN_IDENTIFIER, CONSUMER_KEY);
CREATE INDEX IF NOT EXISTS IDX_ENTITY_TIME_REVOKED ON IDN_SUBJECT_ENTITY_REVOKED_EVENT (ENTITY_ID, TIME_REVOKED);
CREATE INDEX IF NOT EXISTS IDX_REFRESH_TOKEN_HASH ON IDN_OAUTH2_REFRESH_TOKEN (REFRESH_TOKEN_HASH);
CREATE INDEX IF NOT EXISTS IDX_AUTHZ_USER_TENANT_DOMAIN_STATE ON IDN_OAUTH2_REFRESH_TOKEN (AUTHZ_USER, TENANT_ID, USER_DOMAIN, TOKEN_STATE);
CREATE INDEX IF NOT EXISTS IDX_CONSUMER_KEY_STATE ON IDN_OAUTH2_REFRESH_TOKEN (CONSUMER_KEY_ID, TOKEN_STATE);
CREATE INDEX IF NOT EXISTS IDX_CONSUMER_USER_SCOPE_IDP ON IDN_OAUTH2_REFRESH_TOKEN (CONSUMER_KEY_ID, AUTHZ_USER, TENANT_ID, USER_DOMAIN, TOKEN_SCOPE_HASH, TOKEN_STATE, IDP_ID);

-- IDN_OAUTH2_CIBA_AUTH_CODE --
ALTER TABLE IDN_OAUTH2_CIBA_AUTH_CODE ADD COLUMN IF NOT EXISTS RESOLVED_USER_ID CHAR(36);
ALTER TABLE IDN_OAUTH2_CIBA_AUTH_CODE ADD COLUMN IF NOT EXISTS REQUESTED_ACTOR VARCHAR(255) DEFAULT NULL;

INSERT INTO IDN_CONFIG_TYPE (ID, NAME, DESCRIPTION) VALUES
('08fbc096-56c5-4ae6-9edc-54198a07e0dc', 'ISSUER_USAGE_SCOPE', 'A resource type to store issuer usage scope for organizations.')
ON CONFLICT DO NOTHING;

-- Update scope names for user credential management API related scopes -- 
UPDATE SCOPE
SET NAME = CASE NAME
    WHEN 'internal_user_mgt_view' THEN 'internal_user_credential_mgt_view'
    WHEN 'internal_user_mgt_delete' THEN 'internal_user_credential_mgt_delete'
    WHEN 'internal_org_user_mgt_view' THEN 'internal_org_user_credential_mgt_view'
    WHEN 'internal_org_user_mgt_delete' THEN 'internal_org_user_credential_mgt_delete'
END
WHERE NAME IN (
    'internal_user_mgt_view',
    'internal_user_mgt_delete',
    'internal_org_user_mgt_view',
    'internal_org_user_mgt_delete'
)
AND API_ID IN (
    SELECT ID FROM API_RESOURCE WHERE IDENTIFIER IN (
        '/api/server/v1/users/(.*)/credentials',
        '/o/api/server/v1/users/(.*)/credentials'
));

INSERT INTO IDN_SECRET_TYPE (ID, NAME, DESCRIPTION) VALUES
('f47bce92-3d81-4a06-b7e5-29c1d830f5a2', 'SMS_PROVIDER_SECRET_PROPERTIES', 'Secret type to uniquely identify secrets relevant to SMS provider properties')
ON CONFLICT DO NOTHING;
