CREATE OR REPLACE PROCEDURE ALTER_CM_SP_PURPOSE_PII_CAT_ASSOC
BEGIN ATOMIC
    IF EXISTS(SELECT * FROM SYSCAT.TABLES WHERE TABNAME='CM_SP_PURPOSE_PII_CAT_ASSOC')
    THEN
        IF NOT EXISTS(SELECT * FROM SYSCAT.COLUMNS WHERE TABNAME='CM_SP_PURPOSE_PII_CAT_ASSOC' AND COLNAME='IS_CONSENTED')
        THEN
            EXECUTE IMMEDIATE 'ALTER TABLE CM_SP_PURPOSE_PII_CAT_ASSOC ADD IS_CONSENTED SMALLINT DEFAULT 1 NOT NULL';
        END IF;
    END IF;
END
/

CALL ALTER_CM_SP_PURPOSE_PII_CAT_ASSOC
/

DROP PROCEDURE ALTER_CM_SP_PURPOSE_PII_CAT_ASSOC
/
