IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CM_SP_PURPOSE_PII_CAT_ASSOC' AND COLUMN_NAME = 'IS_CONSENTED')
BEGIN
    ALTER TABLE CM_SP_PURPOSE_PII_CAT_ASSOC ADD IS_CONSENTED BIT DEFAULT 1 NOT NULL
END
