DROP PROCEDURE IF EXISTS ALTER_CM_SP_PURPOSE_PII_CAT_ASSOC;

DELIMITER $$
CREATE PROCEDURE ALTER_CM_SP_PURPOSE_PII_CAT_ASSOC()
BEGIN
    IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='CM_SP_PURPOSE_PII_CAT_ASSOC') THEN
        IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='CM_SP_PURPOSE_PII_CAT_ASSOC' AND COLUMN_NAME='IS_CONSENTED') THEN
            ALTER TABLE CM_SP_PURPOSE_PII_CAT_ASSOC ADD IS_CONSENTED BOOLEAN DEFAULT TRUE NOT NULL;
        END IF;
    END IF;
END $$
DELIMITER ;

CALL ALTER_CM_SP_PURPOSE_PII_CAT_ASSOC();

DROP PROCEDURE IF EXISTS ALTER_CM_SP_PURPOSE_PII_CAT_ASSOC;
