CREATE TABLE IF NOT EXISTS IDN_ASYNC_OPERATION_STATUS (
	OPERATION_ID VARCHAR(36) NOT NULL,
	CURSOR_KEY INTEGER NOT NULL,
	CORRELATION_ID VARCHAR(36) NOT NULL,
	OPERATION_TYPE VARCHAR(63) NOT NULL,
	SUBJECT_TYPE VARCHAR(63) NOT NULL,
	SUBJECT_ID VARCHAR(255) NOT NULL,
	INITIATED_ORG_ID VARCHAR(255) NOT NULL,
	INITIATED_USER_ID VARCHAR(255) NOT NULL,
	STATUS VARCHAR(127) NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	LAST_MODIFIED TIMESTAMP NOT NULL,
	POLICY VARCHAR(127),

	PRIMARY KEY (OPERATION_ID),
	CONSTRAINT ASYNC_OP_STATUS_CK_UNQ UNIQUE (CURSOR_KEY)
)
/
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_ASYNC_OPERATION_STATUS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
END
/
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE TRIGGER IDN_ASYNC_OPERATION_STATUS_TRIG NO CASCADE
            BEFORE INSERT
            ON IDN_ASYNC_OPERATION_STATUS
            REFERENCING NEW AS NEW
            FOR EACH ROW MODE DB2SQL
                BEGIN ATOMIC
                SET (NEW.CURSOR_KEY) = (NEXTVAL FOR IDN_ASYNC_OPERATION_STATUS_SEQ);
                END';
END
/

CREATE TABLE IF NOT EXISTS IDN_ASYNC_OPERATION_STATUS_UNIT (
	UNIT_OPERATION_ID VARCHAR(36) NOT NULL,
	CURSOR_KEY INTEGER NOT NULL,
	OPERATION_ID VARCHAR(36) NOT NULL,
	RESIDENT_RESOURCE_ID VARCHAR(255) NOT NULL,
	TARGET_ORG_ID VARCHAR(255) NOT NULL,
	STATUS VARCHAR(63) NOT NULL,
	STATUS_MESSAGE VARCHAR(127),
	CREATED_AT TIMESTAMP NOT NULL,

	PRIMARY KEY (UNIT_OPERATION_ID),
	CONSTRAINT ASYNC_OP_STATUS_UNIT_CK_UQ UNIQUE (CURSOR_KEY),
	FOREIGN KEY (OPERATION_ID) REFERENCES IDN_ASYNC_OPERATION_STATUS(OPERATION_ID) ON DELETE CASCADE ON UPDATE RESTRICT
)
/
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_ASYNC_OPERATION_STATUS_UNIT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
END
/
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE TRIGGER IDN_ASYNC_OPERATION_STATUS_UNIT_TRIG NO CASCADE
            BEFORE INSERT
            ON IDN_ASYNC_OPERATION_STATUS_UNIT
            REFERENCING NEW AS NEW
            FOR EACH ROW MODE DB2SQL
                BEGIN ATOMIC
                SET (NEW.CURSOR_KEY) = (NEXTVAL FOR IDN_ASYNC_OPERATION_STATUS_UNIT_SEQ);
                END';
END
/

INSERT INTO IDN_SECRET_TYPE (ID, NAME, DESCRIPTION)
SELECT 'a1b2c3d4-5e6f-7a89-b012-3456789ab8de', 'EMAIL_PROVIDER_SECRET_PROPERTIES', 'Secret type to uniquely identify secrets relevant to email provider properties' FROM "SYSIBM".SYSDUMMY1
WHERE NOT EXISTS (SELECT * FROM IDN_SECRET_TYPE WHERE id = 'a1b2c3d4-5e6f-7a89-b012-3456789ab8de')
/

INSERT INTO IDN_SECRET_TYPE (ID, NAME, DESCRIPTION)
SELECT 'e2bc9d81-91a0-4efc-9091-c37afc46663b', 'WEBHOOK_SECRETS', 'Secret type to uniquely identify secrets relevant to webhook configurations' FROM "SYSIBM".SYSDUMMY1
WHERE NOT EXISTS (SELECT * FROM IDN_SECRET_TYPE WHERE id = 'e2bc9d81-91a0-4efc-9091-c37afc46663b')
/

CREATE TABLE IF NOT EXISTS APP_GROUP_ASSOCIATION (
  ID INTEGER NOT NULL,
  APP_ID INTEGER NOT NULL,
  GROUP_ID VARCHAR (255) NOT NULL,
  DOMAIN_NAME VARCHAR (255) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (APP_ID) REFERENCES SP_APP(ID) ON DELETE CASCADE,
  CONSTRAINT APP_GROUP_DOMAIN_CONSTRAINT UNIQUE (APP_ID, GROUP_ID, DOMAIN_NAME))
/
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE APP_GROUP_ASSOCIATION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
END
/
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE TRIGGER APP_GROUP_ASSOCIATION_TRIG NO CASCADE
            BEFORE INSERT
            ON APP_GROUP_ASSOCIATION
            REFERENCING NEW AS NEW
            FOR EACH ROW MODE DB2SQL
                BEGIN ATOMIC
                    SET (NEW.ID) = (NEXTVAL FOR APP_GROUP_ASSOCIATION_SEQ);
                END';
END
/

CREATE TABLE IF NOT EXISTS IDN_CUSTOM_CONTENT_ORG (
    ID INTEGER NOT NULL,
    CONTENT BLOB NOT NULL,
    CONTENT_TYPE VARCHAR(50) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT ORG_CUSTOM_CONTENT_UNIQUE_CONSTRAINT UNIQUE (CONTENT_TYPE, TENANT_ID)
)
/
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_CUSTOM_CONTENT_ORG_SEQUENCE START WITH 1 INCREMENT BY 1 NOCACHE';
END
/
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE TRIGGER IDN_CUSTOM_CONTENT_ORG_TRIGGER NO CASCADE BEFORE INSERT ON IDN_CUSTOM_CONTENT_ORG
REFERENCING NEW AS NEW FOR EACH ROW MODE DB2SQL
  BEGIN ATOMIC
    SET (NEW.ID)
    = (NEXTVAL FOR IDN_CUSTOM_CONTENT_ORG_SEQUENCE);
  END';
END
/

CREATE TABLE IF NOT EXISTS IDN_CUSTOM_CONTENT_APP (
    ID INTEGER NOT NULL,
    CONTENT BLOB NOT NULL,
    CONTENT_TYPE VARCHAR(50) NOT NULL,
    APP_ID CHAR(36) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (APP_ID) REFERENCES SP_APP(UUID) ON DELETE CASCADE,
    CONSTRAINT APP_CUSTOM_CONTENT_UNIQUE_CONSTRAINT UNIQUE (CONTENT_TYPE, APP_ID, TENANT_ID)
)
/
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_CUSTOM_CONTENT_APP_SEQUENCE START WITH 1 INCREMENT BY 1 NOCACHE';
END
/
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE TRIGGER IDN_CUSTOM_CONTENT_APP_TRIGGER NO CASCADE BEFORE INSERT ON IDN_CUSTOM_CONTENT_APP
REFERENCING NEW AS NEW FOR EACH ROW MODE DB2SQL
  BEGIN ATOMIC
    SET (NEW.ID)
    = (NEXTVAL FOR IDN_CUSTOM_CONTENT_APP_SEQUENCE);
  END';
END
/

CREATE TABLE IF NOT EXISTS IDN_FLOW (
    ID VARCHAR(50) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    FLOW_NAME VARCHAR(255) NOT NULL,
    TYPE VARCHAR(100) NOT NULL,
    IS_DEFAULT SMALLINT DEFAULT 0,
    LAST_MODIFIED TIMESTAMP,
    CONSTRAINT PK_IDN_FLOW PRIMARY KEY (ID),
    CONSTRAINT UQ_IDN_FLOW UNIQUE (TENANT_ID, TYPE, FLOW_NAME)
)
/

CREATE TABLE IF NOT EXISTS IDN_FLOW_NODE (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NODE_ID VARCHAR(50) NOT NULL,
    FLOW_ID VARCHAR(50) NOT NULL,
    NODE_TYPE VARCHAR(100),
    IS_FIRST_NODE SMALLINT DEFAULT 0,
    CONSTRAINT PK_IDN_FLOW_NODE PRIMARY KEY (ID),
    CONSTRAINT UQ_IDN_FLOW_NODE UNIQUE (NODE_ID, FLOW_ID),
    FOREIGN KEY (FLOW_ID) REFERENCES IDN_FLOW(ID) ON DELETE CASCADE
)
/

CREATE TABLE IF NOT EXISTS IDN_FLOW_NODE_MAPPING (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    FLOW_NODE_ID INTEGER,
    NEXT_NODE_ID INTEGER,
    TRIGGERING_ELEMENT VARCHAR(100),
    CONSTRAINT PK_IDN_FLOW_NODE_MAPPING PRIMARY KEY (ID),
    FOREIGN KEY (FLOW_NODE_ID) REFERENCES IDN_FLOW_NODE(ID) ON DELETE CASCADE,
    FOREIGN KEY (NEXT_NODE_ID) REFERENCES IDN_FLOW_NODE(ID) ON DELETE CASCADE
)
/

CREATE TABLE IF NOT EXISTS IDN_FLOW_PAGE (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    FLOW_ID VARCHAR(50),
    FLOW_NODE_ID INTEGER,
    STEP_ID VARCHAR(50),
    PAGE_CONTENT BLOB,
    TYPE VARCHAR(100),
    CONSTRAINT PK_IDN_FLOW_PAGE PRIMARY KEY (ID),
    FOREIGN KEY (FLOW_ID) REFERENCES IDN_FLOW(ID) ON DELETE CASCADE,
    FOREIGN KEY (FLOW_NODE_ID) REFERENCES IDN_FLOW_NODE(ID) ON DELETE CASCADE
)
/

CREATE TABLE IF NOT EXISTS IDN_FLOW_PAGE_META (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    PAGE_ID INTEGER,
    COORDINATE_X DOUBLE,
    COORDINATE_Y DOUBLE,
    HEIGHT DOUBLE,
    WIDTH DOUBLE,
    CONSTRAINT PK_IDN_FLOW_PAGE_META PRIMARY KEY (ID),
    FOREIGN KEY (PAGE_ID) REFERENCES IDN_FLOW_PAGE(ID) ON DELETE CASCADE
)
/

CREATE TABLE IF NOT EXISTS IDN_FLOW_NODE_EXECUTOR (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    FLOW_NODE_ID INTEGER,
    EXECUTOR_NAME VARCHAR(255),
    IDP_NAME VARCHAR(255),
    CONSTRAINT PK_IDN_FLOW_NODE_EXECUTOR PRIMARY KEY (ID),
    FOREIGN KEY (FLOW_NODE_ID) REFERENCES IDN_FLOW_NODE(ID) ON DELETE CASCADE
)
/

CREATE TABLE IF NOT EXISTS IDN_FLOW_NODE_EXECUTOR_META (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    EXECUTOR_ID INTEGER,
    METADATA_NAME VARCHAR(255),
    METADATA_VALUE VARCHAR(255),
    CONSTRAINT PK_IDN_FLOW_NODE_EXECUTOR_META PRIMARY KEY (ID),
    FOREIGN KEY (EXECUTOR_ID) REFERENCES IDN_FLOW_NODE_EXECUTOR(ID) ON DELETE CASCADE
)
/

CREATE TABLE IF NOT EXISTS IDN_FLOW_CONTEXT_STORE (
    ID VARCHAR(255) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    FLOW_TYPE VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL,
    FLOW_STATE_JSON CLOB NOT NULL,
    CONSTRAINT PK_IDN_FLOW_CONTEXT_STORE PRIMARY KEY (ID)
)
/

CREATE TABLE IF NOT EXISTS IDN_OAUTH2_AUTHZ_CODE_ACTOR (
    ID INTEGER NOT NULL,
    CODE_ID VARCHAR(255) NOT NULL,
    ACTOR  VARCHAR(255) NOT NULL,
    TENANT_ID INTEGER DEFAULT -1,
    PRIMARY KEY (ID, CODE_ID, ACTOR),
    FOREIGN KEY (CODE_ID) REFERENCES IDN_OAUTH2_AUTHORIZATION_CODE(CODE_ID) ON DELETE CASCADE
)
/
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_OAUTH2_AUTHZ_CODE_ACTOR_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
END
/
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE TRIGGER IDN_OAUTH2_AUTHZ_CODE_ACTOR_TRIG NO CASCADE
            BEFORE INSERT
            ON IDN_OAUTH2_AUTHZ_CODE_ACTOR
            REFERENCING NEW AS NEW
            FOR EACH ROW MODE DB2SQL
                BEGIN ATOMIC
                SET (NEW.ID) = (NEXTVAL FOR IDN_OAUTH2_AUTHZ_CODE_ACTOR_SEQ);
                END';
END
/

CREATE TABLE IF NOT EXISTS IDN_WEBHOOK (
    ID INTEGER NOT NULL,
    UUID CHAR(36) NOT NULL,
    ENDPOINT VARCHAR(1024) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    SECRET_ALIAS VARCHAR(1024) NOT NULL,
    VERSION VARCHAR(15) NOT NULL,
    EVENT_PROFILE_NAME VARCHAR(100) NOT NULL,
    EVENT_PROFILE_URI VARCHAR(255) NOT NULL,
    EVENT_PROFILE_VERSION VARCHAR(15) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE(UUID),
    UNIQUE(TENANT_ID, ENDPOINT)
) IN TS32K
/

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_WEBHOOK_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
END
/

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE TRIGGER IDN_WEBHOOK_TRIG NO CASCADE BEFORE INSERT ON IDN_WEBHOOK
  REFERENCING NEW AS NEW FOR EACH ROW MODE DB2SQL
  BEGIN ATOMIC
    SET (NEW.ID) = (NEXTVAL FOR IDN_WEBHOOK_SEQ);
  END';
END
/

CREATE TABLE IF NOT EXISTS IDN_WEBHOOK_CHANNELS (
    ID INTEGER NOT NULL,
    WEBHOOK_ID INTEGER NOT NULL,
    CHANNEL_URI VARCHAR(255) NOT NULL,
    CHANNEL_SUBSCRIPTION_STATUS VARCHAR(30),
    UNIQUE (WEBHOOK_ID, CHANNEL_URI),
    PRIMARY KEY (ID),
    FOREIGN KEY (WEBHOOK_ID) REFERENCES IDN_WEBHOOK(ID) ON DELETE CASCADE
)
/

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_WEBHOOK_CHANNELS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
END
/

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE TRIGGER IDN_WEBHOOK_CHANNELS_TRIG NO CASCADE BEFORE INSERT ON IDN_WEBHOOK_CHANNELS
  REFERENCING NEW AS NEW FOR EACH ROW MODE DB2SQL
  BEGIN ATOMIC
    SET (NEW.ID) = (NEXTVAL FOR IDN_WEBHOOK_CHANNELS_SEQ);
  END';
END
/

CREATE TABLE IF NOT EXISTS IDN_WEBHOOK_TOPIC (
    ID INTEGER NOT NULL,
    TOPIC VARCHAR(255) NOT NULL,
    CHANNEL_URI VARCHAR(255) NOT NULL,
    EVENT_PROFILE_VERSION VARCHAR(32) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (TOPIC, TENANT_ID)
)
/

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_WEBHOOK_TOPIC_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
END
/

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
EXECUTE IMMEDIATE 'CREATE TRIGGER IDN_WEBHOOK_TOPIC_TRIG NO CASCADE BEFORE INSERT ON IDN_WEBHOOK_TOPIC
  REFERENCING NEW AS NEW FOR EACH ROW MODE DB2SQL
  BEGIN ATOMIC
    SET (NEW.ID) = (NEXTVAL FOR IDN_WEBHOOK_TOPIC_SEQ);
  END';
END
/

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_IDN_WEBHOOK_UUID_TID ON IDN_WEBHOOK (UUID, TENANT_ID)';
END
/

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_IDN_WEBHOOK_CHANNELS_WID ON IDN_WEBHOOK_CHANNELS (WEBHOOK_ID)';
END
/

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_IDN_WEBHOOK_TOPIC_TOPIC ON IDN_WEBHOOK_TOPIC (TOPIC)';
END
/

-- IDN_OAUTH2_ACCESS_TOKEN_ATTRIBUTES --
CREATE TABLE IF NOT EXISTS IDN_OAUTH2_ACCESS_TOKEN_ATTRIBUTES (
            ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
            TOKEN_ATTR_NAME varchar(100) NOT NULL,
            TOKEN_ATTR_VALUE varchar(255) NULL,
            TOKEN_ID varchar(255) NOT NULL,
            PRIMARY KEY (ID),
            UNIQUE (TOKEN_ID,TOKEN_ATTR_NAME),
            FOREIGN KEY (TOKEN_ID) REFERENCES IDN_OAUTH2_ACCESS_TOKEN(TOKEN_ID) ON DELETE CASCADE)
/

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_OAUTH2_ACCESS_TOKEN_ATTRIBUTES_TOKEN_ID ON IDN_OAUTH2_ACCESS_TOKEN_ATTRIBUTES (TOKEN_ID)';
END
/

CREATE TABLE IF NOT EXISTS IDN_OAUTH2_DPOP_JKT (
    CODE_ID VARCHAR(255) NOT NULL,
    DPOP_JKT VARCHAR(255),
    PRIMARY KEY (CODE_ID),
    FOREIGN KEY (CODE_ID) REFERENCES IDN_OAUTH2_AUTHORIZATION_CODE(CODE_ID) ON DELETE CASCADE
)
/

CREATE TABLE IF NOT EXISTS WF_REQUEST (
    UUID VARCHAR (45) NOT NULL,
    CREATED_BY VARCHAR (255),
    TENANT_ID INTEGER NOT NULL DEFAULT -1,
    OPERATION_TYPE VARCHAR (50),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    STATUS VARCHAR (30),
    REQUEST BLOB,
    PRIMARY KEY (UUID))
/


CREATE TABLE IF NOT EXISTS WF_WORKFLOW (
    ID VARCHAR (45) NOT NULL,
    WF_NAME VARCHAR (45),
    DESCRIPTION VARCHAR (255),
    TEMPLATE_ID VARCHAR (45),
    IMPL_ID VARCHAR (45),
    TENANT_ID INTEGER NOT NULL DEFAULT -1,
    PRIMARY KEY (ID))
/

CREATE TABLE IF NOT EXISTS WF_WORKFLOW_ASSOCIATION (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ASSOC_NAME VARCHAR (45),
    EVENT_ID VARCHAR(45),
    ASSOC_CONDITION VARCHAR (2000),
    WORKFLOW_ID VARCHAR (45),
    IS_ENABLED CHAR (1) DEFAULT '1',
    TENANT_ID INTEGER DEFAULT -1,
    PRIMARY KEY(ID),
    FOREIGN KEY (WORKFLOW_ID) REFERENCES WF_WORKFLOW(ID) ON DELETE CASCADE)
/

CREATE TABLE IF NOT EXISTS WF_WORKFLOW_CONFIG_PARAM (
    WORKFLOW_ID VARCHAR (45) NOT NULL,
    PARAM_NAME VARCHAR (45) NOT NULL,
    PARAM_VALUE VARCHAR (1000),
    PARAM_QNAME VARCHAR (45) NOT NULL,
    PARAM_HOLDER VARCHAR (45) NOT NULL,
    TENANT_ID INTEGER DEFAULT -1,
    PRIMARY KEY (WORKFLOW_ID, PARAM_NAME, PARAM_QNAME, PARAM_HOLDER),
    FOREIGN KEY (WORKFLOW_ID) REFERENCES WF_WORKFLOW(ID) ON DELETE CASCADE)
/

CREATE TABLE IF NOT EXISTS WF_REQUEST_ENTITY_RELATIONSHIP (
  REQUEST_ID VARCHAR (45) NOT NULL,
  ENTITY_NAME VARCHAR (255) NOT NULL,
  ENTITY_TYPE VARCHAR (50) NOT NULL,
  TENANT_ID INTEGER NOT NULL DEFAULT -1,
  PRIMARY KEY(REQUEST_ID, ENTITY_NAME, ENTITY_TYPE, TENANT_ID),
  FOREIGN KEY (REQUEST_ID) REFERENCES WF_REQUEST(UUID) ON DELETE CASCADE)
/

CREATE TABLE IF NOT EXISTS WF_WORKFLOW_REQUEST_RELATION (
  RELATIONSHIP_ID VARCHAR (45) NOT NULL,
  WORKFLOW_ID VARCHAR (45),
  REQUEST_ID VARCHAR (45),
  UPDATED_AT TIMESTAMP,
  STATUS VARCHAR (30),
  TENANT_ID INTEGER DEFAULT -1,
  PRIMARY KEY (RELATIONSHIP_ID),
  FOREIGN KEY (WORKFLOW_ID) REFERENCES WF_WORKFLOW(ID) ON DELETE CASCADE,
  FOREIGN KEY (REQUEST_ID) REFERENCES WF_REQUEST(UUID) ON DELETE CASCADE)
/

CREATE TABLE IF NOT EXISTS WF_WORKFLOW_APPROVAL_RELATION (
    TASK_ID VARCHAR(45) NOT NULL,
    EVENT_ID VARCHAR(45) NOT NULL,
    WORKFLOW_ID VARCHAR(45) NOT NULL,
    APPROVER_TYPE VARCHAR(45) NOT NULL,
    APPROVER_NAME VARCHAR(255) NOT NULL,
    TASK_STATUS VARCHAR(255),
    PRIMARY KEY (TASK_ID, APPROVER_TYPE, APPROVER_NAME),
    FOREIGN KEY (EVENT_ID) REFERENCES WF_REQUEST(UUID) ON DELETE CASCADE,
    FOREIGN KEY (WORKFLOW_ID) REFERENCES WF_WORKFLOW(ID) ON DELETE CASCADE)
/

CREATE TABLE IF NOT EXISTS WF_WORKFLOW_APPROVAL_STATE (
    EVENT_ID VARCHAR(45) NOT NULL,
    WORKFLOW_ID VARCHAR(45) NOT NULL,
    CURRENT_STEP INTEGER,
    PRIMARY KEY (EVENT_ID, WORKFLOW_ID),
    FOREIGN KEY (EVENT_ID) REFERENCES WF_REQUEST(UUID) ON DELETE CASCADE,
    FOREIGN KEY (WORKFLOW_ID) REFERENCES WF_WORKFLOW(ID) ON DELETE CASCADE)
/

CREATE OR REPLACE PROCEDURE ALTER_IDN_ACTION_AND_IDN_ACTION_PROPERTIES
BEGIN ATOMIC
    IF EXISTS(SELECT * FROM SYSCAT.TABLES WHERE TABNAME='IDN_ACTION')
    THEN
        -- Add CREATED_AT column to IDN_ACTION
        IF NOT EXISTS(SELECT * FROM SYSCAT.COLUMNS WHERE TABNAME='IDN_ACTION' AND COLNAME='CREATED_AT')
        THEN
            EXECUTE IMMEDIATE 'ALTER TABLE IDN_ACTION ADD COLUMN CREATED_AT TIMESTAMP NULL';
        END IF;
        -- Add UPDATED_AT column to IDN_ACTION
        IF NOT EXISTS(SELECT * FROM SYSCAT.COLUMNS WHERE TABNAME='IDN_ACTION' AND COLNAME='UPDATED_AT')
        THEN
            EXECUTE IMMEDIATE 'ALTER TABLE IDN_ACTION ADD COLUMN UPDATED_AT TIMESTAMP NULL';
        END IF;
        -- Add ACTION_VERSION column to IDN_ACTION
        IF NOT EXISTS(SELECT * FROM SYSCAT.COLUMNS WHERE TABNAME='IDN_ACTION' AND COLNAME='ACTION_VERSION')
        THEN
            EXECUTE IMMEDIATE 'ALTER TABLE IDN_ACTION ADD COLUMN ACTION_VERSION VARCHAR(15) NOT NULL DEFAULT ''v1''';
        END IF;
    END IF;

    IF EXISTS(SELECT * FROM SYSCAT.TABLES WHERE TABNAME='IDN_ACTION_PROPERTIES')
    THEN
        -- Add PROPERTY_TYPE column to IDN_ACTION_PROPERTIES
        IF NOT EXISTS(SELECT * FROM SYSCAT.COLUMNS WHERE TABNAME='IDN_ACTION_PROPERTIES' AND COLNAME='PROPERTY_TYPE')
        THEN
            EXECUTE IMMEDIATE 'ALTER TABLE IDN_ACTION_PROPERTIES ADD COLUMN PROPERTY_TYPE VARCHAR(10) NOT NULL DEFAULT ''PRIMITIVE''';
        END IF;
        -- Add OBJECT_VALUE column to IDN_ACTION_PROPERTIES
        IF NOT EXISTS(SELECT * FROM SYSCAT.COLUMNS WHERE TABNAME='IDN_ACTION_PROPERTIES' AND COLNAME='OBJECT_VALUE')
        THEN
            EXECUTE IMMEDIATE 'ALTER TABLE IDN_ACTION_PROPERTIES ADD COLUMN OBJECT_VALUE BLOB';
        END IF;
        -- Make PROPERTY_VALUE column nullable and increase width to 1024 in IDN_ACTION_PROPERTIES
        IF EXISTS(SELECT * FROM SYSCAT.COLUMNS WHERE TABNAME='IDN_ACTION_PROPERTIES' AND COLNAME='PROPERTY_VALUE')
        THEN
            EXECUTE IMMEDIATE 'ALTER TABLE IDN_ACTION_PROPERTIES ALTER COLUMN PROPERTY_VALUE DROP NOT NULL'; 
            EXECUTE IMMEDIATE 'ALTER TABLE IDN_ACTION_PROPERTIES ALTER COLUMN PROPERTY_VALUE SET DATA TYPE VARCHAR(1024)';
        END IF;
    END IF;
END
/
CALL ALTER_IDN_ACTION_AND_IDN_ACTION_PROPERTIES
/
DROP PROCEDURE ALTER_IDN_ACTION_AND_IDN_ACTION_PROPERTIES
/
