CREATE TABLE IF NOT EXISTS IDN_ASYNC_OPERATION_STATUS (
    OPERATION_ID VARCHAR(36) NOT NULL,
    CURSOR_KEY INTEGER NOT NULL AUTO_INCREMENT,
    CORRELATION_ID VARCHAR(36) NOT NULL,
    OPERATION_TYPE VARCHAR(63) NOT NULL,
    SUBJECT_TYPE VARCHAR(63) NOT NULL,
    SUBJECT_ID VARCHAR(255) NOT NULL,
    INITIATED_ORG_ID VARCHAR(255) NOT NULL,
    INITIATED_USER_ID VARCHAR(255) NOT NULL,
    STATUS VARCHAR(127) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    LAST_MODIFIED TIMESTAMP NOT NULL,
    POLICY VARCHAR(127),
    PRIMARY KEY (OPERATION_ID),
    CONSTRAINT ASYNC_OP_STATUS_CK_UNQ UNIQUE (CURSOR_KEY)
);

CREATE TABLE IF NOT EXISTS IDN_ASYNC_OPERATION_STATUS_UNIT (
    UNIT_OPERATION_ID VARCHAR(36) NOT NULL,
    CURSOR_KEY INTEGER NOT NULL AUTO_INCREMENT,
    OPERATION_ID VARCHAR(36) NOT NULL,
    RESIDENT_RESOURCE_ID VARCHAR(255) NOT NULL,
    TARGET_ORG_ID VARCHAR(255) NOT NULL,
    STATUS VARCHAR(63) NOT NULL,
    STATUS_MESSAGE VARCHAR(127),
    CREATED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (UNIT_OPERATION_ID),
    CONSTRAINT ASYNC_OP_STATUS_UNIT_CK_UQ UNIQUE (CURSOR_KEY),
    FOREIGN KEY (OPERATION_ID) REFERENCES IDN_ASYNC_OPERATION_STATUS(OPERATION_ID) ON DELETE CASCADE ON UPDATE RESTRICT
);

INSERT INTO IDN_SECRET_TYPE (ID, NAME, DESCRIPTION)
SELECT 'a1b2c3d4-5e6f-7a89-b012-3456789ab8de',
       'EMAIL_PROVIDER_SECRET_PROPERTIES',
       'Secret type to uniquely identify secrets relevant to email provider properties'
WHERE NOT EXISTS (
    SELECT * FROM IDN_SECRET_TYPE
    WHERE ID = 'a1b2c3d4-5e6f-7a89-b012-3456789ab8de'
);

INSERT INTO IDN_SECRET_TYPE (ID, NAME, DESCRIPTION)
SELECT 'e2bc9d81-91a0-4efc-9091-c37afc46663b',
       'WEBHOOK_SECRETS',
       'Secret type to uniquely identify secrets relevant to webhook configurations'
    WHERE NOT EXISTS (
    SELECT * FROM IDN_SECRET_TYPE
    WHERE ID = 'e2bc9d81-91a0-4efc-9091-c37afc46663b'
);

CREATE TABLE IF NOT EXISTS APP_GROUP_ASSOCIATION (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    APP_ID INTEGER NOT NULL,
    GROUP_ID VARCHAR (255) NOT NULL,
    DOMAIN_NAME VARCHAR (255) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (APP_ID) REFERENCES SP_APP(ID) ON DELETE CASCADE,
    CONSTRAINT APP_GROUP_DOMAIN_CONSTRAINT UNIQUE (APP_ID, GROUP_ID, DOMAIN_NAME)
);

CREATE TABLE IF NOT EXISTS IDN_CUSTOM_CONTENT_ORG (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    CONTENT BLOB NOT NULL,
    CONTENT_TYPE VARCHAR(50) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT ORG_CUSTOM_CONTENT_UNIQUE_CONSTRAINT UNIQUE (CONTENT_TYPE, TENANT_ID)
);

CREATE TABLE IF NOT EXISTS IDN_CUSTOM_CONTENT_APP (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    CONTENT BLOB NOT NULL,
    CONTENT_TYPE VARCHAR(50) NOT NULL,
    APP_ID CHAR(36) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (APP_ID) REFERENCES SP_APP(UUID) ON DELETE CASCADE,
    CONSTRAINT APP_CUSTOM_CONTENT_UNIQUE_CONSTRAINT UNIQUE (CONTENT_TYPE, APP_ID, TENANT_ID)
);

CREATE TABLE IF NOT EXISTS IDN_FLOW (
    ID VARCHAR(50) PRIMARY KEY,
    TENANT_ID INT,
    FLOW_NAME VARCHAR(255),
    TYPE VARCHAR(100),
    IS_DEFAULT BOOLEAN DEFAULT FALSE,
    LAST_MODIFIED TIMESTAMP,
    UNIQUE (TENANT_ID, TYPE, FLOW_NAME)
);

CREATE TABLE IF NOT EXISTS IDN_FLOW_NODE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NODE_ID VARCHAR(50),
    FLOW_ID VARCHAR(50),
    NODE_TYPE VARCHAR(100),
    IS_FIRST_NODE BOOLEAN DEFAULT FALSE,
    UNIQUE (NODE_ID, FLOW_ID),
    FOREIGN KEY (FLOW_ID) REFERENCES IDN_FLOW(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS IDN_FLOW_NODE_MAPPING (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FLOW_NODE_ID INT,
    NEXT_NODE_ID INT,
    TRIGGERING_ELEMENT VARCHAR(100),
    FOREIGN KEY (FLOW_NODE_ID) REFERENCES IDN_FLOW_NODE(ID) ON DELETE CASCADE,
    FOREIGN KEY (NEXT_NODE_ID) REFERENCES IDN_FLOW_NODE(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS IDN_FLOW_PAGE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FLOW_ID VARCHAR(50),
    FLOW_NODE_ID INT,
    STEP_ID VARCHAR(50),
    PAGE_CONTENT BLOB,
    TYPE VARCHAR(100),
    FOREIGN KEY (FLOW_ID) REFERENCES IDN_FLOW(ID) ON DELETE CASCADE,
    FOREIGN KEY (FLOW_NODE_ID) REFERENCES IDN_FLOW_NODE(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS IDN_FLOW_PAGE_META (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PAGE_ID INT,
    COORDINATE_X DOUBLE,
    COORDINATE_Y DOUBLE,
    HEIGHT DOUBLE,
    WIDTH DOUBLE,
    FOREIGN KEY (PAGE_ID) REFERENCES IDN_FLOW_PAGE(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS IDN_FLOW_NODE_EXECUTOR (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FLOW_NODE_ID INT,
    EXECUTOR_NAME VARCHAR(255),
    FOREIGN KEY (FLOW_NODE_ID) REFERENCES IDN_FLOW_NODE(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS IDN_FLOW_NODE_EXECUTOR_META (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    EXECUTOR_ID INT,
    METADATA_NAME VARCHAR(255),
    METADATA_VALUE VARCHAR(255),
    FOREIGN KEY (EXECUTOR_ID) REFERENCES IDN_FLOW_NODE_EXECUTOR(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS IDN_FLOW_CONTEXT_STORE (
    ID VARCHAR(255) PRIMARY KEY,
    TENANT_ID INT NOT NULL,
    FLOW_TYPE VARCHAR(100) NOT NULL,
    FLOW_STATE_JSON CLOB NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS IDN_OAUTH2_AUTHZ_CODE_ACTOR (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    CODE_ID VARCHAR(255),
    ACTOR  VARCHAR(255),
    TENANT_ID INTEGER DEFAULT -1,
    PRIMARY KEY (ID, CODE_ID, ACTOR),
    FOREIGN KEY (CODE_ID) REFERENCES IDN_OAUTH2_AUTHORIZATION_CODE(CODE_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS IDN_WEBHOOK (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    UUID CHAR(36) NOT NULL,
    ENDPOINT VARCHAR(1024) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    SECRET_ALIAS VARCHAR(1024) NOT NULL,
    VERSION VARCHAR(15) NOT NULL,
    EVENT_PROFILE_NAME VARCHAR(100) NOT NULL,
    EVENT_PROFILE_URI VARCHAR(255) NOT NULL,
    EVENT_PROFILE_VERSION VARCHAR(15) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE (UUID),
    UNIQUE (TENANT_ID, ENDPOINT)
);

CREATE TABLE IF NOT EXISTS IDN_WEBHOOK_CHANNELS (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    WEBHOOK_ID INTEGER NOT NULL,
    CHANNEL_URI VARCHAR(255) NOT NULL,
    CHANNEL_SUBSCRIPTION_STATUS VARCHAR(30),
    PRIMARY KEY (ID),
    UNIQUE (WEBHOOK_ID, CHANNEL_URI),
    FOREIGN KEY (WEBHOOK_ID) REFERENCES IDN_WEBHOOK(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS IDN_WEBHOOK_TOPIC (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    TOPIC VARCHAR(255) NOT NULL,
    CHANNEL_URI VARCHAR(255) NOT NULL,
    EVENT_PROFILE_VERSION VARCHAR(32) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (TOPIC, TENANT_ID)
);

CREATE INDEX IF NOT EXISTS IDX_IDN_WEBHOOK_UUID_TID ON IDN_WEBHOOK (UUID, TENANT_ID);
CREATE INDEX IF NOT EXISTS IDX_IDN_WEBHOOK_CHANNELS_WID ON IDN_WEBHOOK_CHANNELS (WEBHOOK_ID);
CREATE INDEX IF NOT EXISTS IDX_IDN_WEBHOOK_TOPIC_TOPIC ON IDN_WEBHOOK_TOPIC (TOPIC);

-- IDN_OAUTH2_ACCESS_TOKEN_ATTRIBUTES --
CREATE TABLE IF NOT EXISTS IDN_OAUTH2_ACCESS_TOKEN_ATTRIBUTES (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    TOKEN_ATTR_NAME varchar(100) NOT NULL,
    TOKEN_ATTR_VALUE varchar(255) NULL,
    TOKEN_ID varchar(255) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (TOKEN_ID,TOKEN_ATTR_NAME),
    FOREIGN KEY (TOKEN_ID) REFERENCES IDN_OAUTH2_ACCESS_TOKEN(TOKEN_ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_OAUTH2_ACCESS_TOKEN_ATTRIBUTES_TOKEN_ID ON IDN_OAUTH2_ACCESS_TOKEN_ATTRIBUTES (TOKEN_ID);

CREATE TABLE IF NOT EXISTS IDN_OAUTH2_DPOP_JKT (
    CODE_ID VARCHAR(255),
    DPOP_JKT VARCHAR(255),
    PRIMARY KEY (CODE_ID),
    FOREIGN KEY (CODE_ID) REFERENCES IDN_OAUTH2_AUTHORIZATION_CODE(CODE_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS WF_REQUEST (
    UUID VARCHAR (45),
    CREATED_BY VARCHAR (255),
    TENANT_ID INTEGER DEFAULT -1,
    OPERATION_TYPE VARCHAR (50),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    STATUS VARCHAR (30),
    REQUEST BLOB,
    PRIMARY KEY (UUID)
);

CREATE TABLE IF NOT EXISTS WF_WORKFLOW(
    ID VARCHAR (45),
    WF_NAME VARCHAR (45),
    DESCRIPTION VARCHAR (255),
    TEMPLATE_ID VARCHAR (45),
    IMPL_ID VARCHAR (45),
    TENANT_ID INTEGER DEFAULT -1,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS WF_WORKFLOW_ASSOCIATION(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    ASSOC_NAME VARCHAR (45),
    EVENT_ID VARCHAR(45),
    ASSOC_CONDITION VARCHAR (2000),
    WORKFLOW_ID VARCHAR (45),
    IS_ENABLED CHAR (1) DEFAULT '1',
    TENANT_ID INTEGER DEFAULT -1,
    PRIMARY KEY(ID),
    FOREIGN KEY (WORKFLOW_ID) REFERENCES WF_WORKFLOW(ID)ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS WF_WORKFLOW_CONFIG_PARAM(
    WORKFLOW_ID VARCHAR (45),
    PARAM_NAME VARCHAR (45),
    PARAM_VALUE VARCHAR (1000),
    PARAM_QNAME VARCHAR (45),
    PARAM_HOLDER VARCHAR (45),
    TENANT_ID INTEGER DEFAULT -1,
    PRIMARY KEY (WORKFLOW_ID, PARAM_NAME, PARAM_QNAME, PARAM_HOLDER),
    FOREIGN KEY (WORKFLOW_ID) REFERENCES WF_WORKFLOW(ID)ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS WF_REQUEST_ENTITY_RELATIONSHIP(
    REQUEST_ID VARCHAR (45),
    ENTITY_NAME VARCHAR (255),
    ENTITY_TYPE VARCHAR (50),
    TENANT_ID INTEGER DEFAULT -1,
    PRIMARY KEY(REQUEST_ID, ENTITY_NAME, ENTITY_TYPE, TENANT_ID),
    FOREIGN KEY (REQUEST_ID) REFERENCES WF_REQUEST(UUID)ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS WF_WORKFLOW_REQUEST_RELATION(
    RELATIONSHIP_ID VARCHAR (45),
    WORKFLOW_ID VARCHAR (45),
    REQUEST_ID VARCHAR (45),
    UPDATED_AT TIMESTAMP,
    STATUS VARCHAR (30),
    TENANT_ID INTEGER DEFAULT -1,
    PRIMARY KEY (RELATIONSHIP_ID),
    FOREIGN KEY (WORKFLOW_ID) REFERENCES WF_WORKFLOW(ID)ON DELETE CASCADE,
    FOREIGN KEY (REQUEST_ID) REFERENCES WF_REQUEST(UUID)ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS WF_WORKFLOW_APPROVAL_RELATION (
    TASK_ID VARCHAR(45) NOT NULL,
    EVENT_ID VARCHAR(45) NOT NULL,
    WORKFLOW_ID VARCHAR(45) NOT NULL,
    APPROVER_TYPE VARCHAR(45) NOT NULL,
    APPROVER_NAME VARCHAR(255) NOT NULL,
    TASK_STATUS VARCHAR(255),
    CONSTRAINT PK_WF_WORKFLOW_RELATION_CONSTRAINT PRIMARY KEY (TASK_ID, APPROVER_TYPE, APPROVER_NAME),
    FOREIGN KEY (EVENT_ID) REFERENCES  WF_REQUEST(UUID) ON DELETE CASCADE,
    FOREIGN KEY (WORKFLOW_ID) REFERENCES  WF_WORKFLOW(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS WF_WORKFLOW_APPROVAL_STATE (
    EVENT_ID VARCHAR(45) NOT NULL,
    WORKFLOW_ID VARCHAR(45) NOT NULL,
    CURRENT_STEP INTEGER,
    CONSTRAINT PK_WF_APPROVAL_STATE_CONSTRAINT PRIMARY KEY (EVENT_ID, WORKFLOW_ID),
    FOREIGN KEY (EVENT_ID) REFERENCES  WF_REQUEST(UUID) ON DELETE CASCADE,
    FOREIGN KEY (WORKFLOW_ID) REFERENCES  WF_WORKFLOW(ID) ON DELETE CASCADE
);

-- Add CREATED_AT column to IDN_ACTION
ALTER TABLE IF EXISTS IDN_ACTION ADD COLUMN IF NOT EXISTS CREATED_AT TIMESTAMP NULL;

-- Add UPDATED_AT column to IDN_ACTION
ALTER TABLE IF EXISTS IDN_ACTION ADD COLUMN IF NOT EXISTS UPDATED_AT TIMESTAMP NULL;

-- Add ACTION_VERSION column to IDN_ACTION
ALTER TABLE IF EXISTS IDN_ACTION ADD COLUMN IF NOT EXISTS ACTION_VERSION VARCHAR(15) NOT NULL DEFAULT 'v1';

-- Add PROPERTY_TYPE column to IDN_ACTION_PROPERTIES
ALTER TABLE IF EXISTS IDN_ACTION_PROPERTIES ADD COLUMN IF NOT EXISTS PROPERTY_TYPE VARCHAR(10) NOT NULL DEFAULT 'PRIMITIVE';

-- Add OBJECT_VALUE column to IDN_ACTION_PROPERTIES
ALTER TABLE IF EXISTS IDN_ACTION_PROPERTIES ADD COLUMN IF NOT EXISTS OBJECT_VALUE BLOB;

-- Make PROPERTY_VALUE column nullable and increase width to 1024 in IDN_ACTION_PROPERTIES
ALTER TABLE IF EXISTS IDN_ACTION_PROPERTIES ALTER COLUMN PROPERTY_VALUE SET DATA TYPE VARCHAR(1024);
ALTER TABLE IF EXISTS IDN_ACTION_PROPERTIES ALTER COLUMN PROPERTY_VALUE SET NULL;
