IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_ASYNC_OPERATION_STATUS]') AND TYPE IN (N'U'))
CREATE TABLE IDN_ASYNC_OPERATION_STATUS (
    OPERATION_ID CHAR(36) NOT NULL,
    CURSOR_KEY INT NOT NULL IDENTITY(1,1),
    CORRELATION_ID CHAR(36) NOT NULL,
    OPERATION_TYPE VARCHAR(63) NOT NULL,
    SUBJECT_TYPE VARCHAR(63) NOT NULL,
    SUBJECT_ID VARCHAR(255) NOT NULL,
    INITIATED_ORG_ID VARCHAR(255) NOT NULL,
    INITIATED_USER_ID VARCHAR(255) NOT NULL,
    STATUS VARCHAR(127) NOT NULL,
    CREATED_AT DATETIME2 NOT NULL,
    LAST_MODIFIED DATETIME2 NOT NULL,
    POLICY VARCHAR(127),
    PRIMARY KEY (OPERATION_ID),
    CONSTRAINT ASYNC_OP_STATUS_CK_UNQ UNIQUE (CURSOR_KEY)
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_ASYNC_OPERATION_STATUS_UNIT]') AND TYPE IN (N'U'))
CREATE TABLE IDN_ASYNC_OPERATION_STATUS_UNIT (
    UNIT_OPERATION_ID CHAR(36) NOT NULL,
    CURSOR_KEY INT NOT NULL IDENTITY(1,1),
    OPERATION_ID CHAR(36) NOT NULL,
    RESIDENT_RESOURCE_ID VARCHAR(255) NOT NULL,
    TARGET_ORG_ID VARCHAR(255) NOT NULL,
    STATUS VARCHAR(63) NOT NULL,
    STATUS_MESSAGE VARCHAR(127),
    CREATED_AT DATETIME2 NOT NULL,
    PRIMARY KEY (UNIT_OPERATION_ID),
    CONSTRAINT ASYNC_OP_STATUS_UNIT_CK_UQ UNIQUE (CURSOR_KEY),
    CONSTRAINT FK_IDN_ASYNC_OPERATION_STATUS_UNIT FOREIGN KEY (OPERATION_ID) REFERENCES IDN_ASYNC_OPERATION_STATUS(OPERATION_ID) ON DELETE CASCADE
);

IF NOT EXISTS (SELECT * FROM IDN_SECRET_TYPE WHERE id = 'a1b2c3d4-5e6f-7a89-b012-3456789ab8de')
BEGIN
  INSERT INTO IDN_SECRET_TYPE (ID, NAME, DESCRIPTION)
  VALUES ('a1b2c3d4-5e6f-7a89-b012-3456789ab8de', 'EMAIL_PROVIDER_SECRET_PROPERTIES', 'Secret type to uniquely identify secrets relevant to email provider properties')
END;

IF NOT EXISTS (SELECT * FROM IDN_SECRET_TYPE WHERE ID = 'e2bc9d81-91a0-4efc-9091-c37afc46663b')
BEGIN
  INSERT INTO IDN_SECRET_TYPE (ID, NAME, DESCRIPTION)
  VALUES ('e2bc9d81-91a0-4efc-9091-c37afc46663b', 'WEBHOOK_SECRETS', 'Secret type to uniquely identify secrets relevant to webhook configurations')
END;

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[APP_GROUP_ASSOCIATION]') AND TYPE IN (N'U'))
CREATE TABLE APP_GROUP_ASSOCIATION (
    ID INTEGER NOT NULL IDENTITY,
    APP_ID INTEGER NOT NULL,
    GROUP_ID VARCHAR (255) NOT NULL,
    DOMAIN_NAME VARCHAR (255) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (APP_ID) REFERENCES SP_APP(ID) ON DELETE CASCADE,
    CONSTRAINT APP_GROUP_DOMAIN_CONSTRAINT UNIQUE (APP_ID, GROUP_ID, DOMAIN_NAME)
);

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_CUSTOM_CONTENT_ORG]') AND TYPE IN (N'U'))
CREATE TABLE IDN_CUSTOM_CONTENT_ORG (
    ID INTEGER IDENTITY,
    CONTENT VARBINARY(MAX) NOT NULL,
    CONTENT_TYPE VARCHAR(50) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT ORG_CUSTOM_CONTENT_UNIQUE_CONSTRAINT UNIQUE (CONTENT_TYPE, TENANT_ID)
);

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_CUSTOM_CONTENT_APP]') AND TYPE IN (N'U'))
CREATE TABLE IDN_CUSTOM_CONTENT_APP (
    ID INTEGER IDENTITY,
    CONTENT VARBINARY(MAX) NOT NULL,
    CONTENT_TYPE VARCHAR(50) NOT NULL,
    APP_ID CHAR(36) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (APP_ID) REFERENCES SP_APP(UUID) ON DELETE CASCADE,
    CONSTRAINT APP_CUSTOM_CONTENT_UNIQUE_CONSTRAINT UNIQUE (CONTENT_TYPE, APP_ID, TENANT_ID)
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_FLOW]') AND TYPE IN (N'U'))
CREATE TABLE IDN_FLOW (
    ID VARCHAR(50) PRIMARY KEY,
    TENANT_ID INT,
    FLOW_NAME VARCHAR(255),
    TYPE VARCHAR(100),
    IS_DEFAULT BIT DEFAULT 0,
    LAST_MODIFIED DATETIME,
    CONSTRAINT UQ_IDN_FLOW UNIQUE (TENANT_ID, TYPE, FLOW_NAME)
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_FLOW_NODE]') AND TYPE IN (N'U'))
CREATE TABLE IDN_FLOW_NODE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NODE_ID VARCHAR(50),
    FLOW_ID VARCHAR(50),
    NODE_TYPE VARCHAR(100),
    IS_FIRST_NODE BIT DEFAULT 0,
    CONSTRAINT UQ_IDN_FLOW_NODE UNIQUE (NODE_ID, FLOW_ID),
    CONSTRAINT FK_IDN_FLOW_NODE_FLOW FOREIGN KEY (FLOW_ID) REFERENCES IDN_FLOW(ID) ON DELETE CASCADE
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_FLOW_NODE_MAPPING]') AND TYPE IN (N'U'))
CREATE TABLE IDN_FLOW_NODE_MAPPING (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    FLOW_NODE_ID INT,
    NEXT_NODE_ID INT,
    TRIGGERING_ELEMENT VARCHAR(100),
    CONSTRAINT FK_IDN_FLOW_NODE_MAPPING_FLOW_NODE FOREIGN KEY (FLOW_NODE_ID) REFERENCES IDN_FLOW_NODE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_IDN_FLOW_NODE_MAPPING_NEXT_NODE FOREIGN KEY (NEXT_NODE_ID) REFERENCES IDN_FLOW_NODE(ID)
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_FLOW_PAGE]') AND TYPE IN (N'U'))
CREATE TABLE IDN_FLOW_PAGE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    FLOW_ID VARCHAR(50),
    FLOW_NODE_ID INT,
    STEP_ID VARCHAR(50),
    PAGE_CONTENT VARBINARY(MAX),
    TYPE VARCHAR(100),
    CONSTRAINT FK_IDN_FLOW_PAGE_FLOW FOREIGN KEY (FLOW_ID) REFERENCES IDN_FLOW(ID),
    CONSTRAINT FK_IDN_FLOW_PAGE_NODE FOREIGN KEY (FLOW_NODE_ID) REFERENCES IDN_FLOW_NODE(ID) ON DELETE CASCADE
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_FLOW_PAGE_META]') AND TYPE IN (N'U'))
CREATE TABLE IDN_FLOW_PAGE_META (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    PAGE_ID INT,
    COORDINATE_X FLOAT,
    COORDINATE_Y FLOAT,
    HEIGHT FLOAT,
    WIDTH FLOAT,
    CONSTRAINT FK_IDN_FLOW_PAGE_META FOREIGN KEY (PAGE_ID) REFERENCES IDN_FLOW_PAGE(ID) ON DELETE CASCADE
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_FLOW_NODE_EXECUTOR]') AND TYPE IN (N'U'))
CREATE TABLE IDN_FLOW_NODE_EXECUTOR (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    FLOW_NODE_ID INT,
    EXECUTOR_NAME VARCHAR(255),
    CONSTRAINT FK_IDN_FLOW_NODE_EXECUTOR FOREIGN KEY (FLOW_NODE_ID) REFERENCES IDN_FLOW_NODE(ID) ON DELETE CASCADE
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_FLOW_NODE_EXECUTOR_META]') AND TYPE IN (N'U'))
CREATE TABLE IDN_FLOW_NODE_EXECUTOR_META (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    EXECUTOR_ID INT NOT NULL,
    METADATA_NAME VARCHAR(255),
    METADATA_VALUE VARCHAR(255),
    FOREIGN KEY (EXECUTOR_ID) REFERENCES IDN_FLOW_NODE_EXECUTOR(ID) ON DELETE CASCADE
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_FLOW_CONTEXT_STORE]') AND TYPE IN (N'U'))
CREATE TABLE IDN_FLOW_CONTEXT_STORE (
    ID VARCHAR(255) PRIMARY KEY,
    TENANT_ID INT NOT NULL,
    FLOW_TYPE VARCHAR(100) NOT NULL,
    FLOW_STATE_JSON NVARCHAR(MAX) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    EXPIRES_AT DATETIME NOT NULL
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_OAUTH2_AUTHZ_CODE_ACTOR]') AND TYPE IN (N'U'))
CREATE TABLE IDN_OAUTH2_AUTHZ_CODE_ACTOR (
    ID INTEGER IDENTITY(1,1) NOT NULL,
    CODE_ID VARCHAR(255),
    ACTOR  VARCHAR(255),
    TENANT_ID INTEGER DEFAULT -1,
    PRIMARY KEY (ID, CODE_ID, ACTOR),
    FOREIGN KEY (CODE_ID) REFERENCES IDN_OAUTH2_AUTHORIZATION_CODE(CODE_ID) ON DELETE CASCADE
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_WEBHOOK]') AND TYPE IN (N'U'))
CREATE TABLE IDN_WEBHOOK (
    ID INTEGER IDENTITY,
    UUID CHAR(36) NOT NULL,
    ENDPOINT VARCHAR(1024) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    SECRET_ALIAS VARCHAR(1024) NOT NULL,
    VERSION VARCHAR(15) NOT NULL,
    EVENT_PROFILE_NAME VARCHAR(100) NOT NULL,
    EVENT_PROFILE_URI VARCHAR(255) NOT NULL,
    EVENT_PROFILE_VERSION VARCHAR(15) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    CREATED_AT DATETIME2 DEFAULT GETDATE(),
    UPDATED_AT DATETIME2 DEFAULT GETDATE(),
    PRIMARY KEY (ID),
    UNIQUE(UUID),
    UNIQUE(TENANT_ID, ENDPOINT)
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_WEBHOOK_CHANNELS]') AND TYPE IN (N'U'))
CREATE TABLE IDN_WEBHOOK_CHANNELS (
    ID INTEGER IDENTITY,
    WEBHOOK_ID INTEGER NOT NULL,
    CHANNEL_URI VARCHAR(255) NOT NULL,
    CHANNEL_SUBSCRIPTION_STATUS VARCHAR(30),
    UNIQUE (WEBHOOK_ID, CHANNEL_URI),
    PRIMARY KEY (ID),
    FOREIGN KEY (WEBHOOK_ID) REFERENCES IDN_WEBHOOK(ID) ON DELETE CASCADE
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_WEBHOOK_TOPIC]') AND TYPE IN (N'U'))
CREATE TABLE IDN_WEBHOOK_TOPIC (
    ID INTEGER IDENTITY,
    TOPIC VARCHAR(255) NOT NULL,
    CHANNEL_URI VARCHAR(255) NOT NULL,
    EVENT_PROFILE_VERSION VARCHAR(32) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (TOPIC, TENANT_ID)
);

-- IDN_OAUTH2_ACCESS_TOKEN_ATTRIBUTES --
IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_OAUTH2_ACCESS_TOKEN_ATTRIBUTES]') AND TYPE IN (N'U'))
CREATE TABLE IDN_OAUTH2_ACCESS_TOKEN_ATTRIBUTES (
            ID INTEGER NOT NULL IDENTITY,
            TOKEN_ATTR_NAME varchar(100) NOT NULL,
            TOKEN_ATTR_VALUE varchar(255) NULL,
            TOKEN_ID varchar(255) NOT NULL,
            PRIMARY KEY (ID),
            UNIQUE (TOKEN_ID,TOKEN_ATTR_NAME),
            FOREIGN KEY (TOKEN_ID) REFERENCES IDN_OAUTH2_ACCESS_TOKEN(TOKEN_ID) ON DELETE CASCADE
);

IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'IDX_IDN_WEBHOOK_UUID_TID')
    DROP INDEX [dbo].[IDN_WEBHOOK].[IDX_IDN_WEBHOOK_UUID_TID];
CREATE INDEX [IDX_IDN_WEBHOOK_UUID_TID] ON [dbo].[IDN_WEBHOOK] ([UUID], [TENANT_ID]);

IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'IDX_IDN_WEBHOOK_CHANNELS_WID')
    DROP INDEX [dbo].[IDN_WEBHOOK_CHANNELS].[IDX_IDN_WEBHOOK_CHANNELS_WID];
CREATE INDEX [IDX_IDN_WEBHOOK_CHANNELS_WID] ON [dbo].[IDN_WEBHOOK_CHANNELS] ([WEBHOOK_ID]);

IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'IDX_IDN_WEBHOOK_TOPIC_TOPIC')
    DROP INDEX [dbo].[IDN_WEBHOOK_TOPIC].[IDX_IDN_WEBHOOK_TOPIC_TOPIC];
CREATE INDEX [IDX_IDN_WEBHOOK_TOPIC_TOPIC] ON [dbo].[IDN_WEBHOOK_TOPIC] ([TOPIC]);

IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'IDX_OAUTH2_ACCESS_TOKEN_ATTRIBUTES_TOKEN_ID')
    DROP INDEX [dbo].[IDN_OAUTH2_ACCESS_TOKEN_ATTRIBUTES].[IDX_OAUTH2_ACCESS_TOKEN_ATTRIBUTES_TOKEN_ID];
CREATE INDEX [IDX_OAUTH2_ACCESS_TOKEN_ATTRIBUTES_TOKEN_ID]
    ON [dbo].[IDN_OAUTH2_ACCESS_TOKEN_ATTRIBUTES] ([TOKEN_ID]);

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_OAUTH2_DPOP_JKT]') AND TYPE IN (N'U'))
CREATE TABLE IDN_OAUTH2_DPOP_JKT (
    CODE_ID VARCHAR(255),
    DPOP_JKT VARCHAR(255),
    PRIMARY KEY (CODE_ID),
    FOREIGN KEY (CODE_ID) REFERENCES IDN_OAUTH2_AUTHORIZATION_CODE(CODE_ID) ON DELETE CASCADE
);

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[WF_REQUEST]') AND TYPE IN (N'U'))
CREATE TABLE WF_REQUEST (
    UUID VARCHAR (45),
    CREATED_BY VARCHAR (255),
    TENANT_ID INTEGER DEFAULT -1,
    OPERATION_TYPE VARCHAR (50),
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME,
    STATUS VARCHAR (30),
    REQUEST VARBINARY(MAX),
    PRIMARY KEY (UUID)
);

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[WF_WORKFLOW]') AND TYPE IN (N'U'))
CREATE TABLE WF_WORKFLOW (
    ID VARCHAR (45),
    WF_NAME VARCHAR (45),
    DESCRIPTION VARCHAR (255),
    TEMPLATE_ID VARCHAR (45),
    IMPL_ID VARCHAR (45),
    TENANT_ID INTEGER DEFAULT -1,
    PRIMARY KEY (ID)
);

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[WF_WORKFLOW_ASSOCIATION]') AND TYPE IN (N'U'))
CREATE TABLE WF_WORKFLOW_ASSOCIATION (
    ID INTEGER NOT NULL IDENTITY ,
    ASSOC_NAME VARCHAR (45),
    EVENT_ID VARCHAR(45),
    ASSOC_CONDITION VARCHAR (2000),
    WORKFLOW_ID VARCHAR (45),
    IS_ENABLED CHAR (1) DEFAULT '1',
    TENANT_ID INTEGER DEFAULT -1,
    PRIMARY KEY(ID),
    FOREIGN KEY (WORKFLOW_ID) REFERENCES WF_WORKFLOW(ID) ON DELETE CASCADE
);

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[WF_WORKFLOW_CONFIG_PARAM]') AND TYPE IN (N'U'))
CREATE TABLE WF_WORKFLOW_CONFIG_PARAM (
    WORKFLOW_ID VARCHAR (45),
    PARAM_NAME VARCHAR (45),
    PARAM_VALUE VARCHAR (1000),
    PARAM_QNAME VARCHAR (45),
    PARAM_HOLDER VARCHAR (45),
    TENANT_ID INTEGER DEFAULT -1,
    PRIMARY KEY (WORKFLOW_ID, PARAM_NAME, PARAM_QNAME, PARAM_HOLDER),
    FOREIGN KEY (WORKFLOW_ID) REFERENCES WF_WORKFLOW(ID)ON DELETE CASCADE
);

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[WF_REQUEST_ENTITY_RELATIONSHIP]') AND TYPE IN (N'U'))
CREATE TABLE WF_REQUEST_ENTITY_RELATIONSHIP (
    REQUEST_ID VARCHAR (45),
    ENTITY_NAME VARCHAR (255),
    ENTITY_TYPE VARCHAR (50),
    TENANT_ID INTEGER DEFAULT -1,
    PRIMARY KEY(REQUEST_ID, ENTITY_NAME, ENTITY_TYPE, TENANT_ID),
    FOREIGN KEY (REQUEST_ID) REFERENCES WF_REQUEST(UUID) ON DELETE CASCADE
);

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[WF_WORKFLOW_REQUEST_RELATION]') AND TYPE IN (N'U'))
CREATE TABLE WF_WORKFLOW_REQUEST_RELATION (
    RELATIONSHIP_ID VARCHAR (45),
    WORKFLOW_ID VARCHAR (45),
    REQUEST_ID VARCHAR (45),
    UPDATED_AT DATETIME,
    STATUS VARCHAR (30),
    TENANT_ID INTEGER DEFAULT -1,
    PRIMARY KEY (RELATIONSHIP_ID),
    FOREIGN KEY (WORKFLOW_ID) REFERENCES WF_WORKFLOW(ID) ON DELETE CASCADE,
    FOREIGN KEY (REQUEST_ID) REFERENCES WF_REQUEST(UUID) ON DELETE CASCADE
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[WF_WORKFLOW_APPROVAL_RELATION]') AND TYPE IN (N'U'))
CREATE TABLE WF_WORKFLOW_APPROVAL_RELATION (
   TASK_ID VARCHAR(45) NOT NULL,
   EVENT_ID VARCHAR(45) NOT NULL,
   WORKFLOW_ID VARCHAR(45) NOT NULL,
   APPROVER_TYPE VARCHAR(45) NOT NULL,
   APPROVER_NAME VARCHAR(255) NOT NULL,
   TASK_STATUS VARCHAR(255),
   CONSTRAINT PK_WF_WORKFLOW_RELATION_CONSTRAINT PRIMARY KEY (TASK_ID, APPROVER_TYPE, APPROVER_NAME),
   FOREIGN KEY (EVENT_ID) REFERENCES  WF_REQUEST(UUID) ON DELETE CASCADE,
   FOREIGN KEY (WORKFLOW_ID) REFERENCES  WF_WORKFLOW(ID) ON DELETE CASCADE
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[WF_WORKFLOW_APPROVAL_STATE]') AND TYPE IN (N'U'))
CREATE TABLE WF_WORKFLOW_APPROVAL_STATE (
   EVENT_ID VARCHAR(45) NOT NULL,
   WORKFLOW_ID VARCHAR(45) NOT NULL,
   CURRENT_STEP INTEGER,
   CONSTRAINT PK_WF_APPROVAL_STATE_CONSTRAINT PRIMARY KEY (EVENT_ID, WORKFLOW_ID),
   FOREIGN KEY (EVENT_ID) REFERENCES  WF_REQUEST(UUID) ON DELETE CASCADE,
   FOREIGN KEY (WORKFLOW_ID) REFERENCES  WF_WORKFLOW(ID) ON DELETE CASCADE
);

-- Add CREATED_AT column to IDN_ACTION
IF NOT EXISTS (
    SELECT 1
    FROM sys.columns
    WHERE object_id = OBJECT_ID(N'[DBO].[IDN_ACTION]')
    AND name = N'CREATED_AT'
)
BEGIN
    ALTER TABLE [DBO].[IDN_ACTION] ADD [CREATED_AT] DATETIME2 NULL
END;

-- Add UPDATED_AT column to IDN_ACTION
IF NOT EXISTS (
    SELECT 1
    FROM sys.columns
    WHERE object_id = OBJECT_ID(N'[DBO].[IDN_ACTION]')
    AND name = N'UPDATED_AT'
)
BEGIN
    ALTER TABLE [DBO].[IDN_ACTION] ADD [UPDATED_AT] DATETIME2 NULL
END;

-- Add ACTION_VERSION column to IDN_ACTION
IF NOT EXISTS (
    SELECT 1
    FROM sys.columns
    WHERE object_id = OBJECT_ID(N'[DBO].[IDN_ACTION]')
    AND name = N'ACTION_VERSION'
)
BEGIN
    ALTER TABLE [DBO].[IDN_ACTION] ADD [ACTION_VERSION] VARCHAR(15) NOT NULL DEFAULT 'v1'
END;

-- Add PROPERTY_TYPE column to IDN_ACTION_PROPERTIES
IF NOT EXISTS (
    SELECT 1
    FROM sys.columns
    WHERE object_id = OBJECT_ID(N'[DBO].[IDN_ACTION_PROPERTIES]')
    AND name = N'PROPERTY_TYPE'
)
BEGIN
    ALTER TABLE [DBO].[IDN_ACTION_PROPERTIES] ADD [PROPERTY_TYPE] VARCHAR(10) NOT NULL
        CONSTRAINT [DF_IDN_ACTION_PROPERTIES_PROPERTY_TYPE]
        DEFAULT (CONVERT(VARCHAR(10), 0x5052494d4954495645)) -- 'PRIMITIVE' in hex
END;

-- Add OBJECT_VALUE column to IDN_ACTION_PROPERTIES
IF NOT EXISTS (
    SELECT 1
    FROM sys.columns
    WHERE object_id = OBJECT_ID(N'[DBO].[IDN_ACTION_PROPERTIES]')
    AND name = N'OBJECT_VALUE'
)
BEGIN
    ALTER TABLE [DBO].[IDN_ACTION_PROPERTIES] ADD [OBJECT_VALUE] VARBINARY(MAX)
END;

-- Make PROPERTY_VALUE column nullable and increase width to 1024 in IDN_ACTION_PROPERTIES
IF EXISTS (
    SELECT 1
    FROM sys.columns
    WHERE object_id = OBJECT_ID(N'[DBO].[IDN_ACTION_PROPERTIES]')
    AND name = N'PROPERTY_VALUE'
)
BEGIN
    ALTER TABLE [DBO].[IDN_ACTION_PROPERTIES] ALTER COLUMN [PROPERTY_VALUE] VARCHAR(1024) NULL
END;
