CREATE TABLE IF NOT EXISTS IDN_ASYNC_OPERATION_STATUS (
	OPERATION_ID VARCHAR(36) NOT NULL,
	CURSOR_KEY INT NOT NULL AUTO_INCREMENT,
	CORRELATION_ID VARCHAR(36) NOT NULL,
	OPERATION_TYPE VARCHAR(63) NOT NULL,
	SUBJECT_TYPE VARCHAR(63) NOT NULL,
	SUBJECT_ID VARCHAR(255) NOT NULL,
	INITIATED_ORG_ID VARCHAR(255) NOT NULL,
	INITIATED_USER_ID VARCHAR(255) NOT NULL,
	STATUS VARCHAR(127) NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	LAST_MODIFIED TIMESTAMP NOT NULL,
	POLICY VARCHAR(127),

	PRIMARY KEY (OPERATION_ID),
	CONSTRAINT ASYNC_OP_STATUS_CK_UNQ UNIQUE (CURSOR_KEY)
) ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_ASYNC_OPERATION_STATUS_UNIT (
	UNIT_OPERATION_ID CHARACTER(36) NOT NULL,
	CURSOR_KEY INTEGER NOT NULL AUTO_INCREMENT,
	OPERATION_ID CHARACTER(36) NOT NULL,
	RESIDENT_RESOURCE_ID VARCHAR(255) NOT NULL,
	TARGET_ORG_ID VARCHAR(255) NOT NULL,
	STATUS VARCHAR(63) NOT NULL,
	STATUS_MESSAGE VARCHAR(127),
	CREATED_AT TIMESTAMP NOT NULL,

	PRIMARY KEY (UNIT_OPERATION_ID),
	CONSTRAINT ASYNC_OP_STATUS_UNIT_CK_UQ UNIQUE (CURSOR_KEY),
	FOREIGN KEY (OPERATION_ID) REFERENCES IDN_ASYNC_OPERATION_STATUS(OPERATION_ID) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE NDB;

INSERT INTO IDN_SECRET_TYPE (ID, NAME, DESCRIPTION)
SELECT 'a1b2c3d4-5e6f-7a89-b012-3456789ab8de',
       'EMAIL_PROVIDER_SECRET_PROPERTIES',
       'Secret type to uniquely identify secrets relevant to email provider properties'
WHERE NOT EXISTS (
    SELECT 1 FROM IDN_SECRET_TYPE
    WHERE ID = 'a1b2c3d4-5e6f-7a89-b012-3456789ab8de'
);

INSERT INTO IDN_SECRET_TYPE (ID, NAME, DESCRIPTION)
SELECT 'e2bc9d81-91a0-4efc-9091-c37afc46663b',
       'WEBHOOK_SECRETS',
       'Secret type to uniquely identify secrets relevant to webhook configurations'
WHERE NOT EXISTS (
    SELECT 1 FROM IDN_SECRET_TYPE
    WHERE ID = 'e2bc9d81-91a0-4efc-9091-c37afc46663b'
);

CREATE TABLE IF NOT EXISTS APP_GROUP_ASSOCIATION (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  APP_ID INTEGER NOT NULL,
  GROUP_ID VARCHAR (255) NOT NULL,
  DOMAIN_NAME VARCHAR (255) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (APP_ID) REFERENCES SP_APP(ID) ON DELETE CASCADE,
  CONSTRAINT APP_GROUP_DOMAIN_CONSTRAINT UNIQUE (APP_ID, GROUP_ID, DOMAIN_NAME)
)ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_CUSTOM_CONTENT_ORG (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    CONTENT BLOB NOT NULL,
    CONTENT_TYPE VARCHAR(50) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT ORG_CUSTOM_CONTENT_UNIQUE_CONSTRAINT UNIQUE (CONTENT_TYPE, TENANT_ID)
)ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_CUSTOM_CONTENT_APP (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    CONTENT BLOB NOT NULL,
    CONTENT_TYPE VARCHAR(50) NOT NULL,
    APP_ID CHAR(36) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (APP_ID) REFERENCES SP_APP(UUID) ON DELETE CASCADE,
    CONSTRAINT APP_CUSTOM_CONTENT_UNIQUE_CONSTRAINT UNIQUE (CONTENT_TYPE, APP_ID, TENANT_ID)
)ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_FLOW (
    ID VARCHAR(50) PRIMARY KEY,
    TENANT_ID INT,
    FLOW_NAME VARCHAR(255),
    TYPE VARCHAR(100),
    IS_DEFAULT BOOLEAN DEFAULT FALSE,
    LAST_MODIFIED TIMESTAMP,
    UNIQUE (TENANT_ID, TYPE, FLOW_NAME)
) ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_FLOW_NODE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NODE_ID VARCHAR(50),
    FLOW_ID VARCHAR(50),
    NODE_TYPE VARCHAR(100),
    IS_FIRST_NODE BOOLEAN DEFAULT FALSE,
    UNIQUE (NODE_ID, FLOW_ID),
    FOREIGN KEY (FLOW_ID) REFERENCES IDN_FLOW(ID) ON DELETE CASCADE
) ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_FLOW_NODE_MAPPING (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FLOW_NODE_ID INT,
    NEXT_NODE_ID INT,
    TRIGGERING_ELEMENT VARCHAR(100),
    FOREIGN KEY (FLOW_NODE_ID) REFERENCES IDN_FLOW_NODE(ID) ON DELETE CASCADE,
    FOREIGN KEY (NEXT_NODE_ID) REFERENCES IDN_FLOW_NODE(ID) ON DELETE CASCADE
) ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_FLOW_PAGE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FLOW_ID VARCHAR(50),
    FLOW_NODE_ID INT,
    STEP_ID VARCHAR(50),
    PAGE_CONTENT BLOB,
    TYPE VARCHAR(100),
    FOREIGN KEY (FLOW_ID) REFERENCES IDN_FLOW(ID) ON DELETE CASCADE,
    FOREIGN KEY (FLOW_NODE_ID) REFERENCES IDN_FLOW_NODE(ID) ON DELETE CASCADE
) ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_FLOW_PAGE_META (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PAGE_ID INT,
    COORDINATE_X DOUBLE,
    COORDINATE_Y DOUBLE,
    HEIGHT DOUBLE,
    WIDTH DOUBLE,
    FOREIGN KEY (PAGE_ID) REFERENCES IDN_FLOW_PAGE(ID) ON DELETE CASCADE
) ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_FLOW_NODE_EXECUTOR (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FLOW_NODE_ID INT,
    EXECUTOR_NAME VARCHAR(255),
    FOREIGN KEY (FLOW_NODE_ID) REFERENCES IDN_FLOW_NODE(ID) ON DELETE CASCADE
) ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_FLOW_NODE_EXECUTOR_META (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EXECUTOR_ID INT NOT NULL,
    METADATA_NAME VARCHAR(255),
    METADATA_VALUE VARCHAR(255),
    FOREIGN KEY (EXECUTOR_ID) REFERENCES IDN_FLOW_NODE_EXECUTOR(ID) ON DELETE CASCADE
) ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_FLOW_CONTEXT_STORE (
    ID VARCHAR(255) PRIMARY KEY,
    TENANT_ID INT NOT NULL,
    FLOW_TYPE VARCHAR(100) NOT NULL,
    FLOW_STATE_JSON LONGTEXT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL
) ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_OAUTH2_AUTHZ_CODE_ACTOR (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    CODE_ID VARCHAR(255),
    ACTOR  VARCHAR(255),
    TENANT_ID INTEGER DEFAULT -1,
    PRIMARY KEY (ID, CODE_ID, ACTOR),
    FOREIGN KEY (CODE_ID) REFERENCES IDN_OAUTH2_AUTHORIZATION_CODE(CODE_ID) ON DELETE CASCADE
) ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_WEBHOOK (
    ID INTEGER AUTO_INCREMENT,
    UUID CHAR(36) NOT NULL,
    ENDPOINT VARCHAR(1024) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    SECRET_ALIAS VARCHAR(1024) NOT NULL,
    VERSION VARCHAR(15) NOT NULL,
    EVENT_PROFILE_NAME VARCHAR(100) NOT NULL,
    EVENT_PROFILE_URI VARCHAR(255) NOT NULL,
    EVENT_PROFILE_VERSION VARCHAR(15) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE (UUID),
    UNIQUE (TENANT_ID, ENDPOINT)
) ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_WEBHOOK_CHANNELS (
    ID INTEGER AUTO_INCREMENT,
    WEBHOOK_ID INTEGER NOT NULL,
    CHANNEL_URI VARCHAR(255) NOT NULL,
    CHANNEL_SUBSCRIPTION_STATUS VARCHAR(30),
    UNIQUE (WEBHOOK_ID, CHANNEL_URI),
    PRIMARY KEY (ID),
    FOREIGN KEY (WEBHOOK_ID) REFERENCES IDN_WEBHOOK(ID) ON DELETE CASCADE
) ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_WEBHOOK_TOPIC (
    ID INTEGER AUTO_INCREMENT,
    TOPIC VARCHAR(255) NOT NULL,
    CHANNEL_URI VARCHAR(255) NOT NULL,
    EVENT_PROFILE_VERSION VARCHAR(32) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (TOPIC, TENANT_ID)
) ENGINE NDB;

DROP PROCEDURE IF EXISTS CREATE_INDEX_IF_NOT_EXISTS;
DELIMITER $$
CREATE PROCEDURE CREATE_INDEX_IF_NOT_EXISTS(
    IN p_table_name VARCHAR(64),
    IN p_index_name VARCHAR(64),
    IN p_index_columns VARCHAR(1000)
)
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM INFORMATION_SCHEMA.STATISTICS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = p_table_name
          AND INDEX_NAME = p_index_name
    ) THEN
        SET @create_sql = CONCAT('CREATE INDEX ', p_index_name, ' ON ', p_table_name, ' ', p_index_columns);
        PREPARE stmt FROM @create_sql;
        EXECUTE stmt;
        DEALLOCATE PREPARE stmt;
    END IF;
END $$
DELIMITER ;

CALL CREATE_INDEX_IF_NOT_EXISTS('IDN_WEBHOOK', 'IDX_IDN_WEBHOOK_UUID_TID', '(UUID, TENANT_ID)');
CALL CREATE_INDEX_IF_NOT_EXISTS('IDN_WEBHOOK_CHANNELS', 'IDX_IDN_WEBHOOK_CHANNELS_WID', '(WEBHOOK_ID)');
CALL CREATE_INDEX_IF_NOT_EXISTS('IDN_WEBHOOK_TOPIC', 'IDX_IDN_WEBHOOK_TOPIC_TOPIC', '(TOPIC)');

-- IDN_OAUTH2_ACCESS_TOKEN_ATTRIBUTES --
CREATE TABLE IF NOT EXISTS IDN_OAUTH2_ACCESS_TOKEN_ATTRIBUTES (
    ID                  INTEGER NOT NULL AUTO_INCREMENT,
    TOKEN_ATTR_NAME     varchar(100) NOT NULL,
    TOKEN_ATTR_VALUE    varchar(255) NULL,
    TOKEN_ID            varchar(255) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (TOKEN_ID,TOKEN_ATTR_NAME),
    FOREIGN KEY (TOKEN_ID) REFERENCES IDN_OAUTH2_ACCESS_TOKEN(TOKEN_ID)
    ON DELETE CASCADE
) ENGINE NDB;

CALL CREATE_INDEX_IF_NOT_EXISTS('IDN_OAUTH2_ACCESS_TOKEN_ATTRIBUTES', 'IDX_OAUTH2_ACCESS_TOKEN_ATTRIBUTES_TOKEN_ID', '(TOKEN_ID)');

DROP PROCEDURE IF EXISTS CREATE_INDEX_IF_NOT_EXISTS;

CREATE TABLE IF NOT EXISTS IDN_OAUTH2_DPOP_JKT (
    CODE_ID VARCHAR(255),
    DPOP_JKT VARCHAR(255),
    PRIMARY KEY (CODE_ID),
    FOREIGN KEY (CODE_ID) REFERENCES IDN_OAUTH2_AUTHORIZATION_CODE(CODE_ID) ON DELETE CASCADE
) ENGINE NDB;

CREATE TABLE IF NOT EXISTS WF_REQUEST (
  UUID           VARCHAR(45),
  CREATED_BY     VARCHAR(255),
  TENANT_ID      INTEGER   DEFAULT -1,
  OPERATION_TYPE VARCHAR(50),
  CREATED_AT     TIMESTAMP,
  UPDATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  STATUS         VARCHAR(30),
  REQUEST        BLOB,
  PRIMARY KEY (UUID)
) ENGINE NDB;

CREATE TABLE IF NOT EXISTS WF_WORKFLOW (
  ID          VARCHAR(45),
  WF_NAME     VARCHAR(45),
  DESCRIPTION VARCHAR(255),
  TEMPLATE_ID VARCHAR(45),
  IMPL_ID     VARCHAR(45),
  TENANT_ID   INTEGER DEFAULT -1,
  PRIMARY KEY (ID)
) ENGINE NDB;

CREATE TABLE IF NOT EXISTS WF_WORKFLOW_ASSOCIATION (
  ID              INTEGER NOT NULL AUTO_INCREMENT,
  ASSOC_NAME      VARCHAR(45),
  EVENT_ID        VARCHAR(45),
  ASSOC_CONDITION VARCHAR(2000),
  WORKFLOW_ID     VARCHAR(45),
  IS_ENABLED      CHAR(1) DEFAULT '1',
  TENANT_ID       INTEGER DEFAULT -1,
  PRIMARY KEY (ID),
  FOREIGN KEY (WORKFLOW_ID) REFERENCES WF_WORKFLOW (ID)
    ON DELETE CASCADE
) ENGINE NDB;

CREATE TABLE IF NOT EXISTS WF_WORKFLOW_CONFIG_PARAM (
  WORKFLOW_ID  VARCHAR(45),
  PARAM_NAME   VARCHAR(45),
  PARAM_VALUE  VARCHAR(1000),
  PARAM_QNAME  VARCHAR(45),
  PARAM_HOLDER VARCHAR(45),
  TENANT_ID    INTEGER DEFAULT -1,
  PRIMARY KEY (WORKFLOW_ID, PARAM_NAME, PARAM_QNAME, PARAM_HOLDER),
  FOREIGN KEY (WORKFLOW_ID) REFERENCES WF_WORKFLOW (ID)
    ON DELETE CASCADE
) ENGINE NDB;

CREATE TABLE IF NOT EXISTS WF_REQUEST_ENTITY_RELATIONSHIP (
  REQUEST_ID  VARCHAR(45),
  ENTITY_NAME VARCHAR(255),
  ENTITY_TYPE VARCHAR(50),
  TENANT_ID   INTEGER DEFAULT -1,
  PRIMARY KEY (REQUEST_ID, ENTITY_NAME, ENTITY_TYPE, TENANT_ID),
  FOREIGN KEY (REQUEST_ID) REFERENCES WF_REQUEST (UUID)
    ON DELETE CASCADE
) ENGINE NDB;

CREATE TABLE IF NOT EXISTS WF_WORKFLOW_REQUEST_RELATION (
  RELATIONSHIP_ID VARCHAR(45),
  WORKFLOW_ID     VARCHAR(45),
  REQUEST_ID      VARCHAR(45),
  UPDATED_AT      TIMESTAMP,
  STATUS          VARCHAR(30),
  TENANT_ID       INTEGER DEFAULT -1,
  PRIMARY KEY (RELATIONSHIP_ID),
  FOREIGN KEY (WORKFLOW_ID) REFERENCES WF_WORKFLOW (ID)
    ON DELETE CASCADE,
  FOREIGN KEY (REQUEST_ID) REFERENCES WF_REQUEST (UUID)
    ON DELETE CASCADE
) ENGINE NDB;

CREATE TABLE IF NOT EXISTS WF_WORKFLOW_APPROVAL_RELATION (
  TASK_ID VARCHAR(45) NOT NULL,
  EVENT_ID VARCHAR(45) NOT NULL,
  WORKFLOW_ID VARCHAR(45) NOT NULL,
  APPROVER_TYPE VARCHAR(45) NOT NULL,
  APPROVER_NAME VARCHAR(255) NOT NULL,
  TASK_STATUS VARCHAR(255),
  PRIMARY KEY (TASK_ID, APPROVER_TYPE, APPROVER_NAME),
  FOREIGN KEY (EVENT_ID) REFERENCES WF_REQUEST(UUID)
    ON DELETE CASCADE,
  FOREIGN KEY (WORKFLOW_ID) REFERENCES WF_WORKFLOW(ID)
    ON DELETE CASCADE
) ENGINE NDB;

CREATE TABLE IF NOT EXISTS WF_WORKFLOW_APPROVAL_STATE (
  EVENT_ID VARCHAR(45) NOT NULL,
  WORKFLOW_ID VARCHAR(45) NOT NULL,
  CURRENT_STEP INTEGER,
  PRIMARY KEY (EVENT_ID, WORKFLOW_ID),
  FOREIGN KEY (EVENT_ID) REFERENCES WF_REQUEST(UUID)
    ON DELETE CASCADE,
  FOREIGN KEY (WORKFLOW_ID) REFERENCES WF_WORKFLOW(ID)
    ON DELETE CASCADE
) ENGINE NDB;

DROP PROCEDURE IF EXISTS ALTER_IDN_ACTION_AND_IDN_ACTION_PROPERTIES;
DELIMITER $$
CREATE PROCEDURE ALTER_IDN_ACTION_AND_IDN_ACTION_PROPERTIES()
BEGIN
    -- Add CREATED_AT column to IDN_ACTION
    IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='IDN_ACTION' AND COLUMN_NAME='CREATED_AT' and TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE `IDN_ACTION` ADD COLUMN `CREATED_AT` TIMESTAMP NULL;
    END IF;
    -- Add UPDATED_AT column to IDN_ACTION
    IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='IDN_ACTION' AND COLUMN_NAME='UPDATED_AT' and TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE `IDN_ACTION` ADD COLUMN `UPDATED_AT` TIMESTAMP NULL;
    END IF;
    -- Add ACTION_VERSION column to IDN_ACTION
    IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='IDN_ACTION' AND COLUMN_NAME='ACTION_VERSION' and TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE `IDN_ACTION` ADD COLUMN `ACTION_VERSION` VARCHAR(15) NOT NULL DEFAULT 'v1';
    END IF;
    -- Add PROPERTY_TYPE column to IDN_ACTION_PROPERTIES
    IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='IDN_ACTION_PROPERTIES' AND COLUMN_NAME='PROPERTY_TYPE' and TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE `IDN_ACTION_PROPERTIES` ADD COLUMN `PROPERTY_TYPE` VARCHAR(10) NOT NULL DEFAULT 'PRIMITIVE';
    END IF;
    -- Add OBJECT_VALUE column to IDN_ACTION_PROPERTIES
    IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='IDN_ACTION_PROPERTIES' AND COLUMN_NAME='OBJECT_VALUE' and TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE `IDN_ACTION_PROPERTIES` ADD COLUMN `OBJECT_VALUE` BLOB;
    END IF;
    -- Make PROPERTY_VALUE column nullable and increase width to 1024 in IDN_ACTION_PROPERTIES
    IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='IDN_ACTION_PROPERTIES' AND COLUMN_NAME='PROPERTY_VALUE' and TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE `IDN_ACTION_PROPERTIES` MODIFY COLUMN `PROPERTY_VALUE` VARCHAR(1024) NULL;
    END IF;
END $$
DELIMITER ;
CALL ALTER_IDN_ACTION_AND_IDN_ACTION_PROPERTIES();
DROP PROCEDURE IF EXISTS ALTER_IDN_ACTION_AND_IDN_ACTION_PROPERTIES;
