DECLARE
    table_exists NUMBER;
    sequence_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_ASYNC_OPERATION_STATUS';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_ASYNC_OPERATION_STATUS (
            OPERATION_ID CHAR(36) NOT NULL,
            CURSOR_KEY INTEGER NOT NULL,
            CORRELATION_ID CHAR(36) NOT NULL,
            OPERATION_TYPE VARCHAR(63) NOT NULL,
            SUBJECT_TYPE VARCHAR(63) NOT NULL,
            SUBJECT_ID VARCHAR(255) NOT NULL,
            INITIATED_ORG_ID VARCHAR(255) NOT NULL,
            INITIATED_USER_ID VARCHAR(255) NOT NULL,
            STATUS VARCHAR2(127) NOT NULL,
            CREATED_AT TIMESTAMP NOT NULL,
            LAST_MODIFIED TIMESTAMP NOT NULL,
            POLICY VARCHAR(127),
            PRIMARY KEY (OPERATION_ID),
            CONSTRAINT ASYNC_OP_STATUS_CK_UNQ UNIQUE (CURSOR_KEY)
        )';
    END IF;
    SELECT COUNT(*) INTO sequence_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_ASYNC_OPERATION_STATUS_SEQ';
    IF sequence_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_ASYNC_OPERATION_STATUS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/
DECLARE
    trig_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO trig_exists FROM ALL_TRIGGERS WHERE TRIGGER_NAME = 'IDN_ASYNC_OPERATION_STATUS_TRG';
    IF trig_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE OR REPLACE TRIGGER IDN_ASYNC_OPERATION_STATUS_TRG
        BEFORE INSERT ON IDN_ASYNC_OPERATION_STATUS
        FOR EACH ROW
        BEGIN
            SELECT IDN_ASYNC_OPERATION_STATUS_SEQ.NEXTVAL INTO :NEW.CURSOR_KEY FROM DUAL;
        END;';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
    sequence_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_ASYNC_OPERATION_STATUS_UNIT';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_ASYNC_OPERATION_STATUS_UNIT (
            UNIT_OPERATION_ID CHAR(36) NOT NULL,
            CURSOR_KEY INTEGER NOT NULL,
            OPERATION_ID CHAR(36) NOT NULL,
            RESIDENT_RESOURCE_ID VARCHAR2(255) NOT NULL,
            TARGET_ORG_ID VARCHAR2(255) NOT NULL,
            STATUS VARCHAR2(63) NOT NULL,
            STATUS_MESSAGE VARCHAR2(127),
            CREATED_AT TIMESTAMP NOT NULL,
            PRIMARY KEY (UNIT_OPERATION_ID),
            CONSTRAINT ASYNC_OP_STATUS_UNIT_CK_UQ UNIQUE (CURSOR_KEY),
            FOREIGN KEY (OPERATION_ID) REFERENCES IDN_ASYNC_OPERATION_STATUS(OPERATION_ID) ON DELETE CASCADE
        )';
    END IF;
    SELECT COUNT(*) INTO sequence_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_ASYNC_OPERATION_STATUS_UNIT_SEQ';
    IF sequence_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_ASYNC_OPERATION_STATUS_UNIT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/
DECLARE
    trig_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO trig_exists FROM ALL_TRIGGERS WHERE TRIGGER_NAME = 'IDN_ASYNC_OPERATION_STATUS_UNIT_TRG';
    IF trig_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE OR REPLACE TRIGGER IDN_ASYNC_OPERATION_STATUS_UNIT_TRG
        BEFORE INSERT ON IDN_ASYNC_OPERATION_STATUS_UNIT
        FOR EACH ROW
        BEGIN
            SELECT IDN_ASYNC_OPERATION_STATUS_UNIT_SEQ.NEXTVAL INTO :NEW.CURSOR_KEY FROM DUAL;
        END;';
    END IF;
END;
/

INSERT INTO IDN_SECRET_TYPE (ID, NAME, DESCRIPTION)
SELECT 'a1b2c3d4-5e6f-7a89-b012-3456789ab8de', 'EMAIL_PROVIDER_SECRET_PROPERTIES', 'Secret type to uniquely identify secrets relevant to email provider properties' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM IDN_SECRET_TYPE WHERE id = 'a1b2c3d4-5e6f-7a89-b012-3456789ab8de')
/

INSERT INTO IDN_SECRET_TYPE (ID, NAME, DESCRIPTION)
SELECT 'e2bc9d81-91a0-4efc-9091-c37afc46663b', 'WEBHOOK_SECRETS', 'Secret type to uniquely identify secrets relevant to webhook configurations' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM IDN_SECRET_TYPE WHERE ID = 'e2bc9d81-91a0-4efc-9091-c37afc46663b')
/

DECLARE
    table_exists NUMBER;
    sequence_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'APP_GROUP_ASSOCIATION';
    
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE APP_GROUP_ASSOCIATION (
          ID INTEGER NOT NULL,
          APP_ID INTEGER NOT NULL,
          GROUP_ID VARCHAR (255) NOT NULL,
          DOMAIN_NAME VARCHAR (255) NOT NULL,
          PRIMARY KEY (ID),
          FOREIGN KEY (APP_ID) REFERENCES SP_APP(ID) ON DELETE CASCADE,
          CONSTRAINT APP_GROUP_DOMAIN_CONSTRAINT UNIQUE (APP_ID, GROUP_ID, DOMAIN_NAME))';
    END IF;
    
    SELECT COUNT(*) INTO sequence_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'APP_GROUP_ASSOCIATION_SEQ';
    
    IF sequence_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE APP_GROUP_ASSOCIATION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/
CREATE OR REPLACE TRIGGER APP_GROUP_ASSOCIATION_TRIG
            BEFORE INSERT
            ON APP_GROUP_ASSOCIATION
            REFERENCING NEW AS NEW
            FOR EACH ROW
               BEGIN
                   SELECT APP_GROUP_ASSOCIATION_SEQ.nextval INTO :NEW.ID FROM dual;
               END;
/

DECLARE
    table_exists NUMBER;
    sequence_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_CUSTOM_CONTENT_ORG';
    
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_CUSTOM_CONTENT_ORG (
            ID INTEGER NOT NULL,
            CONTENT BLOB NOT NULL,
            CONTENT_TYPE VARCHAR(50) NOT NULL,
            TENANT_ID INTEGER NOT NULL,
            PRIMARY KEY (ID),
            CONSTRAINT ORG_CUSTOM_CONTENT_UNIQUE_CONSTRAINT UNIQUE (CONTENT_TYPE, TENANT_ID)
        )';
    END IF;
    
    SELECT COUNT(*) INTO sequence_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_CUSTOM_CONTENT_ORG_SEQ';
    
    IF sequence_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_CUSTOM_CONTENT_ORG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/
CREATE OR REPLACE TRIGGER IDN_CUSTOM_CONTENT_ORG_TRIG
            BEFORE INSERT
            ON IDN_CUSTOM_CONTENT_ORG
            REFERENCING NEW AS NEW
            FOR EACH ROW
              BEGIN
                SELECT IDN_CUSTOM_CONTENT_ORG_SEQ.nextval INTO :NEW.ID FROM dual;
              END;
/

DECLARE
    table_exists NUMBER;
    sequence_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_CUSTOM_CONTENT_APP';
    
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_CUSTOM_CONTENT_APP (
            ID INTEGER NOT NULL,
            CONTENT BLOB NOT NULL,
            CONTENT_TYPE VARCHAR(50) NOT NULL,
            APP_ID CHAR(36) NOT NULL,
            TENANT_ID INTEGER NOT NULL,
            PRIMARY KEY (ID),
            FOREIGN KEY (APP_ID) REFERENCES SP_APP(UUID) ON DELETE CASCADE,
            CONSTRAINT APP_CUSTOM_CONTENT_UNIQUE_CONSTRAINT UNIQUE (CONTENT_TYPE, APP_ID, TENANT_ID)
        )';
    END IF;
    
    SELECT COUNT(*) INTO sequence_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_CUSTOM_CONTENT_APP_SEQ';
    
    IF sequence_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_CUSTOM_CONTENT_APP_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/
CREATE OR REPLACE TRIGGER IDN_CUSTOM_CONTENT_APP_TRIG
            BEFORE INSERT
            ON IDN_CUSTOM_CONTENT_APP
            REFERENCING NEW AS NEW
            FOR EACH ROW
              BEGIN
                SELECT IDN_CUSTOM_CONTENT_APP_SEQ.nextval INTO :NEW.ID FROM dual;
              END;
/

DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_FLOW';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE IDN_FLOW (
            ID VARCHAR(50) NOT NULL,
            TENANT_ID INTEGER NOT NULL,
            FLOW_NAME VARCHAR(255),
            TYPE VARCHAR(100),
            IS_DEFAULT NUMBER(1) DEFAULT 0,
            LAST_MODIFIED TIMESTAMP,
            PRIMARY KEY (ID),
            CONSTRAINT UC_IDN_FLOW UNIQUE (TENANT_ID, TYPE, FLOW_NAME)
        )';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
    seq_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_FLOW_NODE';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE IDN_FLOW_NODE (
            ID INTEGER NOT NULL,
            NODE_ID VARCHAR(50),
            FLOW_ID VARCHAR(50),
            NODE_TYPE VARCHAR(100),
            IS_FIRST_NODE NUMBER(1) DEFAULT 0,
            PRIMARY KEY (ID),
            CONSTRAINT UC_IDN_FLOW_NODE UNIQUE (NODE_ID, FLOW_ID),
            FOREIGN KEY (FLOW_ID) REFERENCES IDN_FLOW(ID) ON DELETE CASCADE
        )';
    END IF;

    SELECT COUNT(*) INTO seq_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_FLOW_NODE_SEQ';
    IF seq_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_FLOW_NODE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

DECLARE
    trig_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO trig_exists FROM ALL_TRIGGERS WHERE TRIGGER_NAME = 'IDN_FLOW_NODE_TRIG';

    IF trig_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE OR REPLACE TRIGGER IDN_FLOW_NODE_TRIG
        BEFORE INSERT ON IDN_FLOW_NODE
        REFERENCING NEW AS NEW
        FOR EACH ROW
        BEGIN
            SELECT IDN_FLOW_NODE_SEQ.nextval INTO :NEW.ID FROM dual;
        END;';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
    seq_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_FLOW_NODE_MAPPING';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE IDN_FLOW_NODE_MAPPING (
            ID INTEGER NOT NULL,
            FLOW_NODE_ID INTEGER,
            NEXT_NODE_ID INTEGER,
            TRIGGERING_ELEMENT VARCHAR(100),
            PRIMARY KEY (ID),
            FOREIGN KEY (FLOW_NODE_ID) REFERENCES IDN_FLOW_NODE(ID) ON DELETE CASCADE,
            FOREIGN KEY (NEXT_NODE_ID) REFERENCES IDN_FLOW_NODE(ID) ON DELETE CASCADE
        )';
    END IF;

    SELECT COUNT(*) INTO seq_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_FLOW_NODE_MAPPING_SEQ';
    IF seq_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_FLOW_NODE_MAPPING_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

DECLARE
    trig_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO trig_exists FROM ALL_TRIGGERS WHERE TRIGGER_NAME = 'IDN_FLOW_NODE_MAPPING_TRIG';

    IF trig_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE OR REPLACE TRIGGER IDN_FLOW_NODE_MAPPING_TRIG
        BEFORE INSERT ON IDN_FLOW_NODE_MAPPING
        REFERENCING NEW AS NEW
        FOR EACH ROW
        BEGIN
            SELECT IDN_FLOW_NODE_MAPPING_SEQ.nextval INTO :NEW.ID FROM dual;
        END;';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
    seq_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_FLOW_PAGE';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE IDN_FLOW_PAGE (
            ID INTEGER NOT NULL,
            FLOW_ID VARCHAR(50),
            FLOW_NODE_ID INTEGER,
            STEP_ID VARCHAR(50),
            PAGE_CONTENT BLOB,
            TYPE VARCHAR(100),
            PRIMARY KEY (ID),
            FOREIGN KEY (FLOW_ID) REFERENCES IDN_FLOW(ID) ON DELETE CASCADE,
            FOREIGN KEY (FLOW_NODE_ID) REFERENCES IDN_FLOW_NODE(ID) ON DELETE CASCADE
        )';
    END IF;

    SELECT COUNT(*) INTO seq_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_FLOW_PAGE_SEQ';
    IF seq_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_FLOW_PAGE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

DECLARE
    trig_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO trig_exists FROM ALL_TRIGGERS WHERE TRIGGER_NAME = 'IDN_FLOW_PAGE_TRIG';

    IF trig_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE OR REPLACE TRIGGER IDN_FLOW_PAGE_TRIG
        BEFORE INSERT ON IDN_FLOW_PAGE
        REFERENCING NEW AS NEW
        FOR EACH ROW
        BEGIN
            SELECT IDN_FLOW_PAGE_SEQ.nextval INTO :NEW.ID FROM dual;
        END;';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
    seq_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_FLOW_PAGE_META';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE IDN_FLOW_PAGE_META (
            ID INTEGER NOT NULL,
            PAGE_ID INTEGER,
            COORDINATE_X NUMBER(10,2),
            COORDINATE_Y NUMBER(10,2),
            HEIGHT NUMBER(10,2),
            WIDTH NUMBER(10,2),
            PRIMARY KEY (ID),
            FOREIGN KEY (PAGE_ID) REFERENCES IDN_FLOW_PAGE(ID) ON DELETE CASCADE
        )';
    END IF;

    SELECT COUNT(*) INTO seq_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_FLOW_PAGE_META_SEQ';
    IF seq_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_FLOW_PAGE_META_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

DECLARE
    trig_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO trig_exists FROM ALL_TRIGGERS WHERE TRIGGER_NAME = 'IDN_FLOW_PAGE_META_TRIG';

    IF trig_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE OR REPLACE TRIGGER IDN_FLOW_PAGE_META_TRIG
        BEFORE INSERT ON IDN_FLOW_PAGE_META
        REFERENCING NEW AS NEW
        FOR EACH ROW
        BEGIN
            SELECT IDN_FLOW_PAGE_META_SEQ.nextval INTO :NEW.ID FROM dual;
        END;';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
    seq_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_FLOW_NODE_EXECUTOR';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE IDN_FLOW_NODE_EXECUTOR (
            ID INTEGER NOT NULL,
            FLOW_NODE_ID INTEGER,
            EXECUTOR_NAME VARCHAR(255),
            PRIMARY KEY (ID),
            FOREIGN KEY (FLOW_NODE_ID) REFERENCES IDN_FLOW_NODE(ID) ON DELETE CASCADE
        )';
    END IF;

    SELECT COUNT(*) INTO seq_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_FLOW_NODE_EXECUTOR_SEQ';
    IF seq_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_FLOW_NODE_EXECUTOR_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

DECLARE
    trig_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO trig_exists FROM ALL_TRIGGERS WHERE TRIGGER_NAME = 'IDN_FLOW_NODE_EXECUTOR_TRIG';

    IF trig_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE OR REPLACE TRIGGER IDN_FLOW_NODE_EXECUTOR_TRIG
        BEFORE INSERT ON IDN_FLOW_NODE_EXECUTOR
        REFERENCING NEW AS NEW
        FOR EACH ROW
        BEGIN
            SELECT IDN_FLOW_NODE_EXECUTOR_SEQ.nextval INTO :NEW.ID FROM dual;
        END;';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
    seq_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_FLOW_NODE_EXECUTOR_META';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE IDN_FLOW_NODE_EXECUTOR_META (
            ID INTEGER NOT NULL,
            EXECUTOR_ID INTEGER,
            METADATA_NAME VARCHAR(255),
            METADATA_VALUE VARCHAR(255),
            PRIMARY KEY (ID),
            FOREIGN KEY (EXECUTOR_ID) REFERENCES IDN_FLOW_NODE_EXECUTOR(ID) ON DELETE CASCADE
        )';
    END IF;

    SELECT COUNT(*) INTO seq_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_FLOW_NODE_EXECUTOR_META_SEQ';
    IF seq_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_FLOW_NODE_EXECUTOR_META_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

DECLARE
    trig_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO trig_exists FROM ALL_TRIGGERS WHERE TRIGGER_NAME = 'IDN_FLOW_NODE_EXECUTOR_META_TRIG';

    IF trig_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE OR REPLACE TRIGGER IDN_FLOW_NODE_EXECUTOR_META_TRIG
        BEFORE INSERT ON IDN_FLOW_NODE_EXECUTOR_META
        REFERENCING NEW AS NEW
        FOR EACH ROW
        BEGIN
            SELECT IDN_FLOW_NODE_EXECUTOR_META_SEQ.nextval INTO :NEW.ID FROM dual;
        END;';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_FLOW_CONTEXT_STORE';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE IDN_FLOW_CONTEXT_STORE (
            ID VARCHAR2(255) PRIMARY KEY,
            TENANT_ID NUMBER(10) NOT NULL,
            FLOW_TYPE VARCHAR2(100) NOT NULL,
            FLOW_STATE_JSON CLOB NOT NULL,
            CREATED_AT TIMESTAMP NOT NULL,
            EXPIRES_AT TIMESTAMP NOT NULL
        )';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
    sequence_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_OAUTH2_AUTHZ_CODE_ACTOR';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE IDN_OAUTH2_AUTHZ_CODE_ACTOR (
            ID INTEGER NOT NULL,
            CODE_ID VARCHAR(255),
            ACTOR  VARCHAR(255),
            TENANT_ID INTEGER DEFAULT -1,
            PRIMARY KEY (ID, CODE_ID, ACTOR),
            FOREIGN KEY (CODE_ID) REFERENCES IDN_OAUTH2_AUTHORIZATION_CODE(CODE_ID) ON DELETE CASCADE
        )';
    END IF;

    SELECT COUNT(*) INTO sequence_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_OAUTH2_AUTHZ_CODE_ACTOR_SEQ';

    IF sequence_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_OAUTH2_AUTHZ_CODE_ACTOR_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER IDN_OAUTH2_AUTHZ_CODE_ACTOR_TRIG
    BEFORE INSERT
    ON IDN_OAUTH2_AUTHZ_CODE_ACTOR
    REFERENCING NEW AS NEW
    FOR EACH ROW
    BEGIN
        SELECT IDN_OAUTH2_AUTHZ_CODE_ACTOR_SEQ.nextval INTO :NEW.ID FROM dual;
    END;
/

DECLARE
    table_exists NUMBER;
    seq_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_WEBHOOK';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE IDN_WEBHOOK (
            ID INTEGER,
            UUID CHAR(36) NOT NULL,
            ENDPOINT VARCHAR(1024) NOT NULL,
            NAME VARCHAR(255) NOT NULL,
            SECRET_ALIAS VARCHAR(1024) NOT NULL,
            VERSION VARCHAR(15) NOT NULL,
            EVENT_PROFILE_NAME VARCHAR(100) NOT NULL,
            EVENT_PROFILE_URI VARCHAR(255) NOT NULL,
            EVENT_PROFILE_VERSION VARCHAR(15) NOT NULL,
            STATUS VARCHAR(30) NOT NULL,
            TENANT_ID INTEGER NOT NULL,
            CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (ID),
            UNIQUE (UUID),
            UNIQUE (TENANT_ID, ENDPOINT)
        )';
    END IF;

    SELECT COUNT(*) INTO seq_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_WEBHOOK_SEQ';

    IF seq_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_WEBHOOK_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER IDN_WEBHOOK_TRIGGER
    BEFORE INSERT ON IDN_WEBHOOK
    REFERENCING NEW AS NEW
    FOR EACH ROW
        BEGIN
            SELECT IDN_WEBHOOK_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
        END;
/

DECLARE
    table_exists NUMBER;
    seq_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_WEBHOOK_CHANNELS';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE IDN_WEBHOOK_CHANNELS (
            ID INTEGER,
            WEBHOOK_ID INTEGER NOT NULL,
            CHANNEL_URI VARCHAR(255) NOT NULL,
            CHANNEL_SUBSCRIPTION_STATUS VARCHAR(30),
            UNIQUE (WEBHOOK_ID, CHANNEL_URI),
            PRIMARY KEY (ID),
            FOREIGN KEY (WEBHOOK_ID) REFERENCES IDN_WEBHOOK(ID) ON DELETE CASCADE
        )';
    END IF;

    SELECT COUNT(*) INTO seq_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_WEBHOOK_CHANNELS_SEQ';

    IF seq_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_WEBHOOK_CHANNELS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER IDN_WEBHOOK_CHANNELS_TRIGGER
    BEFORE INSERT ON IDN_WEBHOOK_CHANNELS
    REFERENCING NEW AS NEW
    FOR EACH ROW
    BEGIN
        SELECT IDN_WEBHOOK_CHANNELS_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
    END;
/

DECLARE
    table_exists NUMBER;
    seq_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_WEBHOOK_TOPIC';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE IDN_WEBHOOK_TOPIC (
            ID INTEGER,
            TOPIC VARCHAR(255) NOT NULL,
            CHANNEL_URI VARCHAR(255) NOT NULL,
            EVENT_PROFILE_VERSION VARCHAR(32) NOT NULL,
            TENANT_ID INTEGER NOT NULL,
            PRIMARY KEY (ID),
            UNIQUE (TOPIC, TENANT_ID)
        )';
    END IF;

    SELECT COUNT(*) INTO seq_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_WEBHOOK_TOPIC_SEQ';

    IF seq_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_WEBHOOK_TOPIC_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER IDN_WEBHOOK_TOPIC_TRIGGER
    BEFORE INSERT ON IDN_WEBHOOK_TOPIC
    REFERENCING NEW AS NEW
    FOR EACH ROW
    BEGIN
        SELECT IDN_WEBHOOK_TOPIC_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
    END;
/

DECLARE
    index_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO index_exists FROM ALL_INDEXES WHERE INDEX_NAME = 'IDX_IDN_WEBHOOK_UUID_TID';
    IF index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_IDN_WEBHOOK_UUID_TID ON IDN_WEBHOOK (UUID, TENANT_ID)';
    END IF;

    SELECT COUNT(*) INTO index_exists FROM ALL_INDEXES WHERE INDEX_NAME = 'IDX_IDN_WEBHOOK_CHANNELS_WID';
    IF index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_IDN_WEBHOOK_CHANNELS_WID ON IDN_WEBHOOK_CHANNELS (WEBHOOK_ID)';
    END IF;

    SELECT COUNT(*) INTO index_exists FROM ALL_INDEXES WHERE INDEX_NAME = 'IDX_IDN_WEBHOOK_TOPIC_TOPIC';
    IF index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_IDN_WEBHOOK_TOPIC_TOPIC ON IDN_WEBHOOK_TOPIC (TOPIC)';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
    sequence_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_OAUTH2_ACCESS_TOKEN_ATTRIBUTES';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_OAUTH2_ACCESS_TOKEN_ATTRIBUTES (
           ID INTEGER,
           TOKEN_ATTR_NAME varchar(100) NOT NULL,
           TOKEN_ATTR_VALUE varchar(255) NULL,
           TOKEN_ID varchar(255) NOT NULL,
           PRIMARY KEY (ID),
           UNIQUE (TOKEN_ID,TOKEN_ATTR_NAME),
           FOREIGN KEY (TOKEN_ID) REFERENCES IDN_OAUTH2_ACCESS_TOKEN(TOKEN_ID) ON DELETE CASCADE)';
    END IF;

    SELECT COUNT(*) INTO sequence_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_OAUTH2_ACCESS_TOKEN_ATTRIBUTES_SEQ';

    IF sequence_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_OAUTH2_ACCESS_TOKEN_ATTRIBUTES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER IDN_OAUTH2_ACCESS_TOKEN_ATTRIBUTES_SEQ
    BEFORE INSERT
    ON IDN_OAUTH2_ACCESS_TOKEN_ATTRIBUTES
    REFERENCING NEW AS NEW
    FOR EACH ROW
        BEGIN
            SELECT IDN_OAUTH2_ACCESS_TOKEN_ATTRIBUTES_SEQ.nextval INTO :NEW.ID FROM dual;
        END;
/

DECLARE
    index_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO index_exists FROM ALL_INDEXES WHERE INDEX_NAME = 'IDX_OAUTH2_ACCESS_TOKEN_ATTRIBUTES_TOKEN_ID';
    IF index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_OAUTH2_ACCESS_TOKEN_ATTRIBUTES_TOKEN_ID ON IDN_OAUTH2_ACCESS_TOKEN_ATTRIBUTES (TOKEN_ID)';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_OAUTH2_DPOP_JKT';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_OAUTH2_DPOP_JKT (
            CODE_ID VARCHAR2(255),
            DPOP_JKT VARCHAR2(255),
            PRIMARY KEY (CODE_ID),
            FOREIGN KEY (CODE_ID) REFERENCES IDN_OAUTH2_AUTHORIZATION_CODE(CODE_ID) ON DELETE CASCADE
        )';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'WF_REQUEST';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE WF_REQUEST (
            UUID VARCHAR2 (45),
            CREATED_BY VARCHAR2 (255),
            TENANT_ID INTEGER DEFAULT -1,
            OPERATION_TYPE VARCHAR2 (50),
            CREATED_AT TIMESTAMP,
            UPDATED_AT TIMESTAMP,
            STATUS VARCHAR2 (30),
            REQUEST BLOB,
            PRIMARY KEY (UUID)
        )';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'WF_WORKFLOW';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE WF_WORKFLOW(
            ID VARCHAR2 (45),
            WF_NAME VARCHAR2 (45),
            DESCRIPTION VARCHAR2 (255),
            TEMPLATE_ID VARCHAR2 (45),
            IMPL_ID VARCHAR2 (45),
            TENANT_ID INTEGER DEFAULT -1,
            PRIMARY KEY (ID)
        )';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
    seq_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'WF_WORKFLOW_ASSOCIATION';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE WF_WORKFLOW_ASSOCIATION(
            ID INTEGER,
            ASSOC_NAME VARCHAR2 (45),
            EVENT_ID VARCHAR2(45),
            ASSOC_CONDITION VARCHAR2 (2000),
            WORKFLOW_ID VARCHAR2 (45),
            IS_ENABLED CHAR (1) DEFAULT ''1'',
            TENANT_ID INTEGER DEFAULT -1,
            PRIMARY KEY(ID),
            FOREIGN KEY (WORKFLOW_ID) REFERENCES WF_WORKFLOW(ID) ON DELETE CASCADE
        )';
    END IF;

    SELECT COUNT(*) INTO seq_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'WF_WORKFLOW_ASSOCIATION_SEQ';
    IF seq_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE WF_WORKFLOW_ASSOCIATION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

DECLARE
    trig_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO trig_exists FROM ALL_TRIGGERS WHERE TRIGGER_NAME = 'WF_WORKFLOW_ASSOCIATION_TRIG';

    IF trig_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE OR REPLACE TRIGGER WF_WORKFLOW_ASSOCIATION_TRIG
        BEFORE INSERT
        ON WF_WORKFLOW_ASSOCIATION
        REFERENCING NEW AS NEW
        FOR EACH ROW
          BEGIN
            SELECT WF_WORKFLOW_ASSOCIATION_SEQ.nextval
            INTO :NEW.ID
            FROM dual;
          END;';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'WF_WORKFLOW_CONFIG_PARAM';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE WF_WORKFLOW_CONFIG_PARAM(
            WORKFLOW_ID VARCHAR2 (45),
            PARAM_NAME VARCHAR2 (45),
            PARAM_VALUE VARCHAR2 (1000),
            PARAM_QNAME VARCHAR2 (45),
            PARAM_HOLDER VARCHAR2 (45),
            TENANT_ID INTEGER DEFAULT -1,
            PRIMARY KEY (WORKFLOW_ID, PARAM_NAME, PARAM_QNAME, PARAM_HOLDER),
            FOREIGN KEY (WORKFLOW_ID) REFERENCES WF_WORKFLOW(ID) ON DELETE CASCADE
        )';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'WF_REQUEST_ENTITY_RELATIONSHIP';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE WF_REQUEST_ENTITY_RELATIONSHIP(
          REQUEST_ID VARCHAR2 (45),
          ENTITY_NAME VARCHAR2 (255),
          ENTITY_TYPE VARCHAR2 (50),
          TENANT_ID INTEGER DEFAULT -1,
          PRIMARY KEY(REQUEST_ID, ENTITY_NAME, ENTITY_TYPE, TENANT_ID),
          FOREIGN KEY (REQUEST_ID) REFERENCES WF_REQUEST(UUID) ON DELETE CASCADE
        )';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'WF_WORKFLOW_REQUEST_RELATION';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE WF_WORKFLOW_REQUEST_RELATION(
          RELATIONSHIP_ID VARCHAR2 (45),
          WORKFLOW_ID VARCHAR2 (45),
          REQUEST_ID VARCHAR2 (45),
          UPDATED_AT TIMESTAMP,
          STATUS VARCHAR (30),
          TENANT_ID INTEGER DEFAULT -1,
          PRIMARY KEY (RELATIONSHIP_ID),
          FOREIGN KEY (WORKFLOW_ID) REFERENCES WF_WORKFLOW(ID) ON DELETE CASCADE,
          FOREIGN KEY (REQUEST_ID) REFERENCES WF_REQUEST(UUID) ON DELETE CASCADE
        )';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'WF_WORKFLOW_APPROVAL_RELATION';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE WF_WORKFLOW_APPROVAL_RELATION (
            TASK_ID VARCHAR2(45) NOT NULL,
            EVENT_ID VARCHAR2(45) NOT NULL,
            WORKFLOW_ID VARCHAR2(45) NOT NULL,
            APPROVER_TYPE VARCHAR2(45) NOT NULL,
            APPROVER_NAME VARCHAR2(255) NOT NULL,
            TASK_STATUS VARCHAR2(255),
            CONSTRAINT PK_WF_WORKFLOW_RELATION_CONSTRAINT PRIMARY KEY (TASK_ID, APPROVER_TYPE, APPROVER_NAME),
            CONSTRAINT FK_WF_WF_APPROVAL_REL_EVENT FOREIGN KEY (EVENT_ID) REFERENCES WF_REQUEST(UUID) ON DELETE CASCADE,
            CONSTRAINT FK_WF_WF_APPROVAL_REL_WF FOREIGN KEY (WORKFLOW_ID) REFERENCES WF_WORKFLOW(ID) ON DELETE CASCADE
        )';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'WF_WORKFLOW_APPROVAL_STATE';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE WF_WORKFLOW_APPROVAL_STATE (
            EVENT_ID VARCHAR2(45) NOT NULL,
            WORKFLOW_ID VARCHAR2(45) NOT NULL,
            CURRENT_STEP INTEGER,
            CONSTRAINT PK_WF_APPROVAL_STATE_CONSTRAINT PRIMARY KEY (EVENT_ID, WORKFLOW_ID),
            CONSTRAINT FK_WF_WF_APPROVAL_STATE_EVENT FOREIGN KEY (EVENT_ID) REFERENCES WF_REQUEST(UUID) ON DELETE CASCADE,
            CONSTRAINT FK_WF_WF_APPROVAL_STATE_WF FOREIGN KEY (WORKFLOW_ID) REFERENCES WF_WORKFLOW(ID) ON DELETE CASCADE
        )';
    END IF;
END;
/

DECLARE
    column_count INTEGER;
BEGIN
    -- Add CREATED_AT column to IDN_ACTION
    SELECT COUNT(*) INTO column_count
    FROM ALL_TAB_COLUMNS
    WHERE OWNER = (SELECT USER FROM DUAL)
        AND TABLE_NAME = 'IDN_ACTION'
        AND COLUMN_NAME = 'CREATED_AT';
    IF column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_ACTION ADD CREATED_AT TIMESTAMP NULL';
    END IF;

    -- Add UPDATED_AT column to IDN_ACTION
    SELECT COUNT(*) INTO column_count
    FROM ALL_TAB_COLUMNS
    WHERE OWNER = (SELECT USER FROM DUAL)
        AND TABLE_NAME = 'IDN_ACTION'
        AND COLUMN_NAME = 'UPDATED_AT';
    IF column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_ACTION ADD UPDATED_AT TIMESTAMP NULL';
    END IF;

    -- Add ACTION_VERSION column to IDN_ACTION
    SELECT COUNT(*) INTO column_count
    FROM ALL_TAB_COLUMNS
    WHERE OWNER = (SELECT USER FROM DUAL)
        AND TABLE_NAME = 'IDN_ACTION'
        AND COLUMN_NAME = 'ACTION_VERSION';
    IF column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_ACTION ADD ACTION_VERSION VARCHAR(15) DEFAULT ''v1'' NOT NULL';
    END IF;

    -- Add PROPERTY_TYPE column to IDN_ACTION_PROPERTIES
    SELECT COUNT(*) INTO column_count
    FROM ALL_TAB_COLUMNS
    WHERE OWNER = (SELECT USER FROM DUAL)
        AND TABLE_NAME = 'IDN_ACTION_PROPERTIES'
        AND COLUMN_NAME = 'PROPERTY_TYPE';
    IF column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_ACTION_PROPERTIES ADD PROPERTY_TYPE VARCHAR(10) DEFAULT ''PRIMITIVE'' NOT NULL';
    END IF;

    -- Add OBJECT_VALUE column to IDN_ACTION_PROPERTIES
    SELECT COUNT(*) INTO column_count
    FROM ALL_TAB_COLUMNS
    WHERE OWNER = (SELECT USER FROM DUAL)
        AND TABLE_NAME = 'IDN_ACTION_PROPERTIES'
        AND COLUMN_NAME = 'OBJECT_VALUE';
    IF column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_ACTION_PROPERTIES ADD OBJECT_VALUE BLOB';
    END IF;

    -- Make PROPERTY_VALUE column nullable and increase width to 1024 in IDN_ACTION_PROPERTIES
    SELECT COUNT(*) INTO column_count
    FROM ALL_TAB_COLUMNS
    WHERE OWNER = (SELECT USER FROM DUAL)
        AND TABLE_NAME = 'IDN_ACTION_PROPERTIES'
        AND COLUMN_NAME = 'PROPERTY_VALUE'
        AND (DATA_LENGTH < 1024 OR NULLABLE = 'N');
    IF column_count > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_ACTION_PROPERTIES MODIFY PROPERTY_VALUE VARCHAR(1024) NULL';
    END IF;

    -- Increase IS_ACTIVE column width to 5 in IDN_RULE
    SELECT COUNT(*) INTO column_count
    FROM ALL_TAB_COLUMNS
    WHERE OWNER = (SELECT USER FROM DUAL)
        AND TABLE_NAME = 'IDN_RULE'
        AND COLUMN_NAME = 'IS_ACTIVE'
        AND (DATA_LENGTH < 5);
    IF column_count > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_RULE MODIFY IS_ACTIVE CHAR(5)';
    END IF;
END;
/


-- IDN_SECRET --
DECLARE
    column_exists NUMBER;
    nullable_flag VARCHAR2(1);
BEGIN
    SELECT COUNT(*) INTO column_exists FROM ALL_TAB_COLUMNS WHERE TABLE_NAME = 'IDN_SECRET' AND COLUMN_NAME = 'SECRET_VALUE_CLOB';
    IF column_exists = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE IDN_SECRET ADD SECRET_VALUE_CLOB CLOB';
    END IF;

    SELECT NULLABLE INTO nullable_flag FROM ALL_TAB_COLUMNS WHERE TABLE_NAME = 'IDN_SECRET' AND COLUMN_NAME = 'SECRET_VALUE';
    IF nullable_flag = 'N' THEN
            EXECUTE IMMEDIATE 'ALTER TABLE IDN_SECRET MODIFY SECRET_VALUE NULL';
    END IF;
END;
/
