DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'MIGRATION_STATUS';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE MIGRATION_STATUS (
            IS_VERSION VARCHAR(255) NOT NULL,
                STATUS VARCHAR(255),
                LOCKED_BY VARCHAR(255),
                LOCK_ACQUIRED_AT TIMESTAMP,
                EXPIRES_AT TIMESTAMP,
                PRIMARY KEY (IS_VERSION)
        )';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'MIGRATOR_PROGRESS';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE MIGRATOR_PROGRESS (
                IS_VERSION VARCHAR(255) NOT NULL,
                STATUS VARCHAR(255),
                CURRENT_MIGRATOR VARCHAR(255),
                CURRENT_TENANT VARCHAR(255),
                LAST_COMPLETED_MIGRATOR VARCHAR(255),
                LAST_COMPLETED_TENANT VARCHAR(255),
                PRIMARY KEY (IS_VERSION)
        )';
    END IF;
END;
/

INSERT INTO MIGRATION_STATUS (IS_VERSION, LOCKED_BY, STATUS, LOCK_ACQUIRED_AT, EXPIRES_AT)
SELECT '7.2.0', NULL, 'NOT-STARTED', NULL, NULL FROM DUAL
WHERE NOT EXISTS (SELECT * FROM MIGRATION_STATUS WHERE IS_VERSION = '7.2.0')
/

INSERT INTO MIGRATOR_PROGRESS (IS_VERSION,STATUS, CURRENT_MIGRATOR, CURRENT_TENANT, LAST_COMPLETED_MIGRATOR, LAST_COMPLETED_TENANT)
SELECT '7.2.0', 'NOT-STARTED', NULL, NULL, NULL, NULL FROM DUAL
WHERE NOT EXISTS (SELECT * FROM MIGRATOR_PROGRESS WHERE IS_VERSION = '7.2.0')
/
