-- Disable foreign key checks temporarily to avoid issues during DDL operations,
-- especially when adding columns or indexes that might interact with existing data.
-- Re-enable them at the end of the script.
SET FOREIGN_KEY_CHECKS = 0;

-- --- Table Creation ---

CREATE TABLE IF NOT EXISTS SP_TRUSTED_APPS (
  ID INTEGER AUTO_INCREMENT NOT NULL,
  SP_ID INTEGER NOT NULL,
  PLATFORM_TYPE VARCHAR(255) NOT NULL,
  APP_IDENTIFIER VARCHAR(255) NOT NULL,
  THUMBPRINTS VARCHAR(2048),
  IS_FIDO_TRUSTED BOOLEAN DEFAULT FALSE,
  TENANT_ID INTEGER NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE (SP_ID, PLATFORM_TYPE),
  FOREIGN KEY (SP_ID) REFERENCES SP_APP(ID)
    ON DELETE CASCADE
)ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_NOTIFICATION_TYPE (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    TYPE_KEY VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CHANNEL VARCHAR(255) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    VERSION VARCHAR(15) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT NOTIFICATION_TYPE_KEY_CONSTRAINT UNIQUE (TYPE_KEY, CHANNEL, TENANT_ID),
    CONSTRAINT NOTIFICATION_TYPE_NAME_CONSTRAINT UNIQUE (NAME, CHANNEL, TENANT_ID)
)ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_NOTIFICATION_ORG_TEMPLATE (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    TEMPLATE_KEY VARCHAR(50) NOT NULL,
    LOCALE VARCHAR(50) NOT NULL,
    CONTENT BLOB NOT NULL,
    CONTENT_TYPE VARCHAR(50),
    TYPE_ID INTEGER NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    VERSION VARCHAR(15) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (TYPE_ID) REFERENCES IDN_NOTIFICATION_TYPE(ID) ON DELETE CASCADE,
    CONSTRAINT ORG_NOTIFICATION_TEMPLATE_KEY_CONSTRAINT UNIQUE (TEMPLATE_KEY, TYPE_ID, TENANT_ID),
    CONSTRAINT ORG_NOTIFICATION_TEMPLATE_LOCALE_CONSTRAINT UNIQUE (LOCALE, TYPE_ID, TENANT_ID)
)ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_NOTIFICATION_APP_TEMPLATE (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    TEMPLATE_KEY VARCHAR(50) NOT NULL,
    LOCALE VARCHAR(50) NOT NULL,
    CONTENT BLOB NOT NULL,
    CONTENT_TYPE VARCHAR(50),
    TYPE_ID INTEGER NOT NULL,
    APP_ID VARCHAR(255) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    VERSION VARCHAR(15) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (TYPE_ID) REFERENCES IDN_NOTIFICATION_TYPE(ID) ON DELETE CASCADE,
    CONSTRAINT APP_NOTIFICATION_TEMPLATE_KEY_CONSTRAINT UNIQUE (TEMPLATE_KEY, TYPE_ID, APP_ID, TENANT_ID),
    CONSTRAINT APP_NOTIFICATION_TEMPLATE_LOCALE_CONSTRAINT UNIQUE (LOCALE, TYPE_ID, APP_ID, TENANT_ID)
)ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_ACTION (
    UUID CHAR(36) NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    STATUS VARCHAR(10) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    VERSION VARCHAR(15) NOT NULL,
    PRIMARY KEY (UUID)
)ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_ACTION_PROPERTIES (
    ACTION_UUID CHAR(36) NOT NULL,
    PROPERTY_NAME VARCHAR(100) NOT NULL,
    PROPERTY_VALUE VARCHAR(255) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    PRIMARY KEY (ACTION_UUID, PROPERTY_NAME),
    FOREIGN KEY (ACTION_UUID) REFERENCES IDN_ACTION(UUID) ON DELETE CASCADE
)ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_OAUTH2_TOKEN_CLAIMS (
    ID INTEGER AUTO_INCREMENT,
    APP_ID INTEGER NOT NULL,
    CLAIM_URI VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT TOKEN_CLAIMS_CONSTRAINT UNIQUE (APP_ID, CLAIM_URI),
    FOREIGN KEY (APP_ID) REFERENCES IDN_OAUTH_CONSUMER_APPS(ID) ON DELETE CASCADE
)ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_SAML2_SERVICE_PROVIDER (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    ISSUER VARCHAR(255) NOT NULL,
    DEFAULT_ASSERTION_CONSUMER_URL VARCHAR(2048) NOT NULL,
    NAME_ID_FORMAT VARCHAR(255) NOT NULL,
    CERT_ALIAS VARCHAR(255),
    REQ_SIG_VALIDATION BOOLEAN,
    SIGN_RESPONSE BOOLEAN NOT NULL,
    SIGN_ASSERTIONS BOOLEAN NOT NULL,
    SIGNING_ALGO VARCHAR(255) NOT NULL,
    DIGEST_ALGO VARCHAR(255) NOT NULL,
    ENCRYPT_ASSERTION BOOLEAN,
    ASSERTION_ENCRYPTION_ALGO VARCHAR(255),
    KEY_ENCRYPTION_ALGO VARCHAR(255),
    ATTR_PROFILE_ENABLED BOOLEAN NOT NULL,
    ATTR_SERVICE_INDEX VARCHAR(255),
    SLO_PROFILE_ENABLED BOOLEAN NOT NULL,
    SLO_METHOD VARCHAR(255),
    SLO_RESPONSE_URL VARCHAR(2048),
    SLO_REQUEST_URL VARCHAR(2048),
    IDP_INIT_SSO_ENABLED BOOLEAN,
    IDP_INIT_SLO_ENABLED BOOLEAN,
    QUERY_REQUEST_PROFILE_ENABLED BOOLEAN NOT NULL,
    ECP_ENABLED BOOLEAN NOT NULL,
    ARTIFACT_BINDING_ENABLED BOOLEAN NOT NULL,
    ARTIFACT_RESOLVE_REQ_SIG_VALIDATION BOOLEAN,
    IDP_ENTITY_ID_ALIAS VARCHAR(255),
    ISSUER_QUALIFIER VARCHAR(255),
    SUPPORTED_ASSERTION_QUERY_REQUEST_TYPES VARCHAR(255),
    TENANT_ID INTEGER NOT NULL,
    VERSION VARCHAR(15) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    ATTR_NAME_FORMAT VARCHAR(255),
    PRIMARY KEY (ID),
    CONSTRAINT IDN_SAML2_SERVICE_PROVIDER_CONSTRAINT UNIQUE (ISSUER, TENANT_ID)
) ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_SAML2_SP_PROPERTIES (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    PROPERTY_NAME VARCHAR(255) NOT NULL,
    PROPERTY_VALUE VARCHAR(2048) NOT NULL,
    SP_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (SP_ID) REFERENCES IDN_SAML2_SERVICE_PROVIDER(ID) ON DELETE CASCADE
) ENGINE NDB;

CREATE TABLE IF NOT EXISTS AUTHORIZATION_DETAILS_TYPES (
    ID CHAR(36) NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    API_ID CHAR(36) NOT NULL,
    CURSOR_KEY INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR (255),
    JSON_SCHEMA TEXT NOT NULL,
    TENANT_ID INTEGER,

    PRIMARY KEY (ID),
    UNIQUE KEY (CURSOR_KEY),
    CONSTRAINT AUTHORIZATION_DETAILS_TYPES_UNIQUE_CONSTRAINT UNIQUE (TYPE, TENANT_ID),
    FOREIGN KEY (API_ID) REFERENCES API_RESOURCE(ID) ON DELETE CASCADE
) ENGINE NDB;

CREATE TABLE IF NOT EXISTS AUTHORIZED_AUTHORIZATION_DETAILS_TYPES (
    APP_ID CHAR(36) NOT NULL,
    API_ID CHAR(36) NOT NULL,
    TYPE_ID CHAR(36) NOT NULL,

    PRIMARY KEY (APP_ID, API_ID, TYPE_ID),
    FOREIGN KEY (API_ID) REFERENCES API_RESOURCE(ID),
    FOREIGN KEY (TYPE_ID) REFERENCES AUTHORIZATION_DETAILS_TYPES(ID) ON DELETE CASCADE,
    FOREIGN KEY (APP_ID) REFERENCES SP_APP(UUID),
    FOREIGN KEY (APP_ID, API_ID) REFERENCES AUTHORIZED_API(APP_ID, API_ID) ON DELETE CASCADE,

    CONSTRAINT AUTHORIZED_AUTHORIZATION_DETAILS_UNIQUE UNIQUE (APP_ID, TYPE_ID)
) ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_OAUTH2_USER_CONSENTED_AUTHORIZATION_DETAILS (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    CONSENT_ID VARCHAR(255) NOT NULL,
    TYPE_ID CHAR(36) NOT NULL,
    AUTHORIZATION_DETAILS TEXT NOT NULL,
    CONSENT BOOLEAN NOT NULL DEFAULT 0,
    TENANT_ID INTEGER NOT NULL,

    PRIMARY KEY (ID, CONSENT_ID, TYPE_ID),
    FOREIGN KEY (TYPE_ID) REFERENCES AUTHORIZATION_DETAILS_TYPES(ID) ON DELETE CASCADE,
    FOREIGN KEY (CONSENT_ID) REFERENCES IDN_OAUTH2_USER_CONSENT(CONSENT_ID) ON DELETE CASCADE
) ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_OAUTH2_ACCESS_TOKEN_AUTHORIZATION_DETAILS (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    TYPE_ID CHAR(36) NOT NULL,
    AUTHORIZATION_DETAILS TEXT NOT NULL,
    TOKEN_ID VARCHAR(255),
    TENANT_ID INTEGER DEFAULT -1,

    PRIMARY KEY (ID, TOKEN_ID, TYPE_ID),
    FOREIGN KEY (TYPE_ID) REFERENCES AUTHORIZATION_DETAILS_TYPES(ID) ON DELETE CASCADE,
    FOREIGN KEY (TOKEN_ID) REFERENCES IDN_OAUTH2_ACCESS_TOKEN(TOKEN_ID) ON DELETE CASCADE
) ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_OAUTH2_AUTHZ_CODE_AUTHORIZATION_DETAILS (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    TYPE_ID CHAR(36) NOT NULL,
    AUTHORIZATION_DETAILS TEXT NOT NULL,
    CODE_ID VARCHAR(255),
    TENANT_ID INTEGER DEFAULT -1,

    PRIMARY KEY (ID, CODE_ID, TYPE_ID),
    FOREIGN KEY (TYPE_ID) REFERENCES AUTHORIZATION_DETAILS_TYPES(ID) ON DELETE CASCADE,
    FOREIGN KEY (CODE_ID) REFERENCES IDN_OAUTH2_AUTHORIZATION_CODE(CODE_ID) ON DELETE CASCADE
) ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_RULE (
    ID INTEGER AUTO_INCREMENT,
    UUID CHAR(36) NOT NULL,
    CONTENT BLOB NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    TENANT_ID INTEGER NOT NULL,
    VERSION VARCHAR(15) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (UUID)
)ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_RULE_REFERENCES (
    ID INTEGER AUTO_INCREMENT,
    RULE_ID INTEGER NOT NULL,
    FIELD_NAME VARCHAR(100) NOT NULL,
    FIELD_REFERENCE VARCHAR(255) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (RULE_ID) REFERENCES IDN_RULE(ID) ON DELETE CASCADE
)ENGINE NDB;

CREATE TABLE IF NOT EXISTS IDN_PUSH_DEVICE_STORE (
    ID VARCHAR(255) NOT NULL,
    USER_ID VARCHAR(255) NOT NULL,
    DEVICE_NAME VARCHAR(45) NOT NULL,
    DEVICE_MODEL VARCHAR(45) NOT NULL,
    DEVICE_TOKEN VARCHAR(255) NOT NULL,
    DEVICE_HANDLE VARCHAR(255),
    PUBLIC_KEY VARCHAR(2048) NOT NULL,
    PROVIDER VARCHAR(45) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (USER_ID)
) ENGINE NDB;

-- --- Column Additions ---

-- Add DEFINED_BY, AUTHENTICATION_TYPE, IMAGE_URL, DESCRIPTION to IDP_AUTHENTICATOR
DROP PROCEDURE IF EXISTS ALTER_IDP_AUTHENTICATOR_COLUMNS;
DELIMITER $$
CREATE PROCEDURE ALTER_IDP_AUTHENTICATOR_COLUMNS()
BEGIN
    IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='IDP_AUTHENTICATOR' AND COLUMN_NAME='DEFINED_BY' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE `IDP_AUTHENTICATOR` ADD COLUMN `DEFINED_BY` VARCHAR(25) NOT NULL DEFAULT 'SYSTEM';
    END IF;
    IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='IDP_AUTHENTICATOR' AND COLUMN_NAME='AUTHENTICATION_TYPE' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE `IDP_AUTHENTICATOR` ADD COLUMN `AUTHENTICATION_TYPE` VARCHAR(25) NOT NULL DEFAULT 'IDENTIFICATION';
    END IF;
    IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='IDP_AUTHENTICATOR' AND COLUMN_NAME='IMAGE_URL' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE `IDP_AUTHENTICATOR` ADD COLUMN `IMAGE_URL` VARCHAR(1024);
    END IF;
    IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='IDP_AUTHENTICATOR' AND COLUMN_NAME='DESCRIPTION' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE `IDP_AUTHENTICATOR` ADD COLUMN `DESCRIPTION` VARCHAR(1024);
    END IF;
END $$
DELIMITER ;
CALL ALTER_IDP_AUTHENTICATOR_COLUMNS();
DROP PROCEDURE IF EXISTS ALTER_IDP_AUTHENTICATOR_COLUMNS;

-- Add VERSION to SP_APP
DROP PROCEDURE IF EXISTS ADD_VERSION_TO_SP_APP;
DELIMITER $$
CREATE PROCEDURE ADD_VERSION_TO_SP_APP()
BEGIN
     IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SP_APP' AND COLUMN_NAME='VERSION' and TABLE_SCHEMA = DATABASE()) THEN
            ALTER TABLE `SP_APP` ADD COLUMN `VERSION` VARCHAR(255) NOT NULL DEFAULT 'v1.0.0';
     END IF;
END $$
DELIMITER ;
CALL ADD_VERSION_TO_SP_APP();
DROP PROCEDURE IF EXISTS ADD_VERSION_TO_SP_APP;


-- Add UUID to IDN_CERTIFICATE
DROP PROCEDURE IF EXISTS ADD_UUID_TO_IDN_CERTIFICATE;
DELIMITER $$
CREATE PROCEDURE ADD_UUID_TO_IDN_CERTIFICATE()
BEGIN
    IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='IDN_CERTIFICATE' AND COLUMN_NAME='UUID' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE `IDN_CERTIFICATE` ADD COLUMN `UUID` CHAR(36);
    END IF;
END $$
DELIMITER ;
CALL ADD_UUID_TO_IDN_CERTIFICATE();
DROP PROCEDURE IF EXISTS ADD_UUID_TO_IDN_CERTIFICATE;

-- Insert Data - Use INSERT IGNORE INTO for idempotence if PK/Unique exists
INSERT IGNORE INTO IDN_SECRET_TYPE (ID, NAME, DESCRIPTION) VALUES
('33f0a41b-569d-4ea5-a891-6c0e78a1c3b0', 'ACTION_API_ENDPOINT_AUTH_SECRETS', 'Secret type to uniquely identify secrets relevant to action endpoint authentication properties'),
('b411dafd-e2c4-4d2f-afba-3900d802725a', 'PUSH_PROVIDER_SECRET_PROPERTIES', 'Secret type to uniquely identify secrets relevant to push provider properties'),
('ce234fd5-3fb4-4a40-9911-818be9b4ee10', 'REMOTE_LOGGING_SECRETS', 'Secret type to uniquely identify secrets relevant to remote logging properties');

INSERT IGNORE INTO IDN_CONFIG_TYPE (ID, NAME, DESCRIPTION) VALUES
('3e5b1f91-72d8-4fbc-94d1-1b9a4f8c3b07', 'IMPERSONATION_CONFIGURATION', 'A resource type to keep the tenant impersonation preferences.'),
('91116e95-ca63-4787-be2d-de13d04d1b55', 'CERTIFICATE_VALIDATOR', 'A resource type to keep the certificate validators.'),
('a17952b9-0942-4669-8529-479ca481146b', 'CERTIFICATE_REVOCATION_VALIDATION_CA', 'A resource type to keep the certificate revocation validation related certificate authorities.'),
('32360745-9c3e-4391-b563-66f17f0eb93a', 'ADMIN_ADVISORY_BANNER', 'A resource type to store admin advisory banner configurations.'),
('82ab7001-fb0e-44da-9169-1f63e4964d9b', 'REMOTE_LOGGING_CONFIG', 'A resource type to store remote server logger configurations.');

-- Add TOKEN_BINDING_REF to IDN_OAUTH2_ACCESS_TOKEN_AUDIT
DROP PROCEDURE IF EXISTS ADD_TOKEN_BINDING_REF_TO_OAUTH2_AUDIT;
DELIMITER $$
CREATE PROCEDURE ADD_TOKEN_BINDING_REF_TO_OAUTH2_AUDIT()
BEGIN
    IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='IDN_OAUTH2_ACCESS_TOKEN_AUDIT' AND COLUMN_NAME='TOKEN_BINDING_REF' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE `IDN_OAUTH2_ACCESS_TOKEN_AUDIT` ADD COLUMN `TOKEN_BINDING_REF` VARCHAR(32) DEFAULT 'NONE';
    END IF;
END $$
DELIMITER ;
CALL ADD_TOKEN_BINDING_REF_TO_OAUTH2_AUDIT();
DROP PROCEDURE IF EXISTS ADD_TOKEN_BINDING_REF_TO_OAUTH2_AUDIT;

-- Add CONSENTED_TOKEN column (original procedure, kept as is)
DROP PROCEDURE IF EXISTS ALTER_IDN_OAUTH2_ACCESS_TOKEN_AUDIT;

DELIMITER $$
CREATE PROCEDURE ALTER_IDN_OAUTH2_ACCESS_TOKEN_AUDIT()
BEGIN
    IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='IDN_OAUTH2_ACCESS_TOKEN_AUDIT') THEN
        IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='IDN_OAUTH2_ACCESS_TOKEN_AUDIT' AND COLUMN_NAME='CONSENTED_TOKEN') THEN
            ALTER TABLE `IDN_OAUTH2_ACCESS_TOKEN_AUDIT` ADD COLUMN `CONSENTED_TOKEN` VARCHAR(6);
        END IF;
    END IF;
END $$
DELIMITER ;

CALL ALTER_IDN_OAUTH2_ACCESS_TOKEN_AUDIT();

DROP PROCEDURE IF EXISTS ALTER_IDN_OAUTH2_ACCESS_TOKEN_AUDIT;

-- Add AUTHORIZED_ORGANIZATION to IDN_OAUTH2_ACCESS_TOKEN_AUDIT
DROP PROCEDURE IF EXISTS ADD_AUTHORIZED_ORG_TO_OAUTH2_AUDIT;
DELIMITER $$
CREATE PROCEDURE ADD_AUTHORIZED_ORG_TO_OAUTH2_AUDIT()
BEGIN
    IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='IDN_OAUTH2_ACCESS_TOKEN_AUDIT' AND COLUMN_NAME='AUTHORIZED_ORGANIZATION' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE `IDN_OAUTH2_ACCESS_TOKEN_AUDIT` ADD COLUMN `AUTHORIZED_ORGANIZATION` varchar(36) NOT NULL DEFAULT 'NONE';
    END IF;
END $$
DELIMITER ;
CALL ADD_AUTHORIZED_ORG_TO_OAUTH2_AUDIT();
DROP PROCEDURE IF EXISTS ADD_AUTHORIZED_ORG_TO_OAUTH2_AUDIT;

-- Alter table UM_ORG_USER_ASSOCIATION to add UM_SHARED_TYPE
DROP PROCEDURE IF EXISTS ADD_UM_SHARED_TYPE_TO_UM_ORG_USER_ASSOCIATION;
DELIMITER $$
CREATE PROCEDURE ADD_UM_SHARED_TYPE_TO_UM_ORG_USER_ASSOCIATION()
BEGIN
    IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='UM_ORG_USER_ASSOCIATION' AND COLUMN_NAME='UM_SHARED_TYPE' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE `UM_ORG_USER_ASSOCIATION` ADD COLUMN `UM_SHARED_TYPE` VARCHAR(255) DEFAULT 'NOT SPECIFIED' NOT NULL;
    END IF;
END $$
DELIMITER ;
CALL ADD_UM_SHARED_TYPE_TO_UM_ORG_USER_ASSOCIATION();
DROP PROCEDURE IF EXISTS ADD_UM_SHARED_TYPE_TO_UM_ORG_USER_ASSOCIATION;

-- Alter table UM_ORG_USER_ASSOCIATION to add unique auto-incrementing UM_ID
-- This procedure handles both column addition and the unique constraint.
DROP PROCEDURE IF EXISTS ADD_UM_ID_TO_UM_ORG_USER_ASSOCIATION;
DELIMITER $$
CREATE PROCEDURE ADD_UM_ID_TO_UM_ORG_USER_ASSOCIATION()
BEGIN
    -- Add UM_ID column if it doesn't exist
    IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='UM_ORG_USER_ASSOCIATION' AND COLUMN_NAME='UM_ID' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE `UM_ORG_USER_ASSOCIATION` ADD COLUMN `UM_ID` INTEGER AUTO_INCREMENT UNIQUE;
    ELSE
        -- If UM_ID column exists, ensure it has a unique index (which 'UNIQUE' constraint creates)
        -- MySQL often names unique indexes after the column if not specified.
        IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'UM_ORG_USER_ASSOCIATION' AND INDEX_NAME = 'UM_ID' AND NON_UNIQUE = 0) THEN
            -- Attempt to add the unique constraint. This will create a unique index.
            ALTER TABLE `UM_ORG_USER_ASSOCIATION` ADD UNIQUE (`UM_ID`);
        END IF;
    END IF;
END $$
DELIMITER ;
CALL ADD_UM_ID_TO_UM_ORG_USER_ASSOCIATION();
DROP PROCEDURE IF EXISTS ADD_UM_ID_TO_UM_ORG_USER_ASSOCIATION;

-- --- Index Creation ---
DROP PROCEDURE IF EXISTS CREATE_INDEX_IF_NOT_EXISTS;
DELIMITER $$
CREATE PROCEDURE CREATE_INDEX_IF_NOT_EXISTS(
    IN p_table_name VARCHAR(64),
    IN p_index_name VARCHAR(64),
    IN p_index_columns VARCHAR(1000)
)
BEGIN
    -- Check if the index exists
    IF NOT EXISTS (
        SELECT 1
        FROM INFORMATION_SCHEMA.STATISTICS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = p_table_name
          AND INDEX_NAME = p_index_name
    ) THEN
        -- If it does NOT exist, create it
        SET @create_sql = CONCAT('CREATE INDEX ', p_index_name, ' ON ', p_table_name, ' ', p_index_columns);
        PREPARE stmt FROM @create_sql;
        EXECUTE stmt;
        DEALLOCATE PREPARE stmt;
    END IF;
END $$
DELIMITER ;

-- Call the helper procedure for each index
CALL CREATE_INDEX_IF_NOT_EXISTS('IDN_ACTION', 'IDX_IDN_ACTION_TY_TI', '(TYPE, TENANT_ID)');
CALL CREATE_INDEX_IF_NOT_EXISTS('IDN_ACTION_PROPERTIES', 'IDX_IDN_ACTION_PROPERTIES_AU_TI', '(ACTION_UUID, TENANT_ID)');
CALL CREATE_INDEX_IF_NOT_EXISTS('IDN_SAML2_SERVICE_PROVIDER', 'IDX_SAML2_SP_TENANT_ID', '(TENANT_ID)');
CALL CREATE_INDEX_IF_NOT_EXISTS('IDN_SAML2_SP_PROPERTIES', 'IDX_SAML2_SP_PROPERTIES', '(SP_ID)');
CALL CREATE_INDEX_IF_NOT_EXISTS('IDN_RULE', 'IDX_IDN_RULE_UUID_TID', '(UUID, TENANT_ID)');
CALL CREATE_INDEX_IF_NOT_EXISTS('IDN_RULE_REFERENCES', 'IDX_IDN_RULE_REF_RID_TID', '(RULE_ID, TENANT_ID)');
CALL CREATE_INDEX_IF_NOT_EXISTS('SP_CLAIM_MAPPING', 'IDX_SPCM_APP', '(APP_ID)');
CALL CREATE_INDEX_IF_NOT_EXISTS('IDP_AUTHENTICATOR', 'IDX_IDP_AUTH_DEFINED_BY', '(DEFINED_BY)');
CALL CREATE_INDEX_IF_NOT_EXISTS('IDP_AUTHENTICATOR', 'IDX_IDP_AUTH_IDP_ID', '(IDP_ID)');
CALL CREATE_INDEX_IF_NOT_EXISTS('UM_RESOURCE_SHARING_POLICY', 'IDX_POLICY_HOLDING_ORG_ID', '(UM_POLICY_HOLDING_ORG_ID)');
CALL CREATE_INDEX_IF_NOT_EXISTS('UM_SHARED_RESOURCE_ATTRIBUTES', 'IDX_RESOURCE_SHARING_POLICY_ID', '(UM_RESOURCE_SHARING_POLICY_ID)');

-- Drop the helper procedure after all index creations are done.
DROP PROCEDURE IF EXISTS CREATE_INDEX_IF_NOT_EXISTS;

-- Re-enable foreign key checks now that all DDL operations are complete.
SET FOREIGN_KEY_CHECKS = 1;
