DECLARE
    table_exists NUMBER;
    sequence_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'SP_TRUSTED_APPS';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE SP_TRUSTED_APPS (
            ID INTEGER NOT NULL,
            SP_ID INTEGER NOT NULL,
            PLATFORM_TYPE VARCHAR(255) NOT NULL,
            APP_IDENTIFIER VARCHAR(255) NOT NULL,
            THUMBPRINTS VARCHAR(2048),
            IS_FIDO_TRUSTED NUMBER(1,0) DEFAULT 0,
            TENANT_ID INTEGER NOT NULL,
            PRIMARY KEY (ID),
            UNIQUE (SP_ID, PLATFORM_TYPE),
            FOREIGN KEY (SP_ID) REFERENCES SP_APP(ID) ON DELETE CASCADE)';
    END IF;

    SELECT COUNT(*) INTO sequence_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'SP_TRUSTED_APPS_SEQ';

    IF sequence_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE SP_TRUSTED_APPS_SEQ START WITH 1 INCREMENT BY 1 CACHE 20';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER SP_TRUSTED_APPS_TRIG
            BEFORE INSERT
            ON SP_TRUSTED_APPS
            REFERENCING NEW AS NEW
            FOR EACH ROW
                BEGIN
                    SELECT SP_TRUSTED_APPS_SEQ.nextval INTO :NEW.ID FROM dual;
                END;
/

DECLARE
    table_exists NUMBER;
    sequence_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_NOTIFICATION_TYPE';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_NOTIFICATION_TYPE (
             ID INTEGER NOT NULL,
             TYPE_KEY VARCHAR(255) NOT NULL,
             NAME VARCHAR(255) NOT NULL,
             CHANNEL VARCHAR(255) NOT NULL,
             TENANT_ID INTEGER NOT NULL,
             VERSION VARCHAR(15) NOT NULL,
             CREATED_AT TIMESTAMP NOT NULL,
             UPDATED_AT TIMESTAMP NOT NULL,
             PRIMARY KEY (ID),
             CONSTRAINT NOTIFICATION_TYPE_KEY_CONSTRAINT UNIQUE (TYPE_KEY, CHANNEL, TENANT_ID),
             CONSTRAINT NOTIFICATION_TYPE_NAME_CONSTRAINT UNIQUE (NAME, CHANNEL, TENANT_ID))';
    END IF;

    SELECT COUNT(*) INTO sequence_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_NOTIFICATION_TYPE_SEQ';

    IF sequence_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_NOTIFICATION_TYPE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER IDN_NOTIFICATION_TYPE_TRIG
  BEFORE INSERT
    ON IDN_NOTIFICATION_TYPE
    REFERENCING NEW AS NEW
    FOR EACH ROW
  BEGIN
  SELECT IDN_NOTIFICATION_TYPE_SEQ.nextval INTO :NEW.ID FROM dual;
  END;
/

DECLARE
    table_exists NUMBER;
    sequence_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_NOTIFICATION_ORG_TEMPLATE';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_NOTIFICATION_ORG_TEMPLATE (
             ID INTEGER NOT NULL,
             TEMPLATE_KEY VARCHAR(50) NOT NULL,
             LOCALE VARCHAR(50) NOT NULL,
             CONTENT BLOB NOT NULL,
             CONTENT_TYPE VARCHAR(50),
             TYPE_ID INTEGER NOT NULL,
             TENANT_ID INTEGER NOT NULL,
             VERSION VARCHAR(15) NOT NULL,
             CREATED_AT TIMESTAMP NOT NULL,
             UPDATED_AT TIMESTAMP NOT NULL,
             PRIMARY KEY (ID),
             FOREIGN KEY (TYPE_ID) REFERENCES IDN_NOTIFICATION_TYPE(ID) ON DELETE CASCADE,
             CONSTRAINT ORG_NOTIFICATION_TEMPLATE_KEY_CONSTRAINT UNIQUE (TEMPLATE_KEY, TYPE_ID, TENANT_ID),
             CONSTRAINT ORG_NOTIFICATION_TEMPLATE_LOCALE_CONSTRAINT UNIQUE (LOCALE, TYPE_ID, TENANT_ID))';
    END IF;

    SELECT COUNT(*) INTO sequence_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_NOTIFICATION_ORG_TEMPLATE_SEQ';

    IF sequence_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_NOTIFICATION_ORG_TEMPLATE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER IDN_NOTIFICATION_ORG_TEMPLATE_TRIG
  BEFORE INSERT
    ON IDN_NOTIFICATION_ORG_TEMPLATE
    REFERENCING NEW AS NEW
    FOR EACH ROW
  BEGIN
  SELECT IDN_NOTIFICATION_ORG_TEMPLATE_SEQ.nextval INTO :NEW.ID FROM dual;
  END;
/

DECLARE
    table_exists NUMBER;
    sequence_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_NOTIFICATION_APP_TEMPLATE';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_NOTIFICATION_APP_TEMPLATE (
             ID INTEGER NOT NULL,
             TEMPLATE_KEY VARCHAR(50) NOT NULL,
             LOCALE VARCHAR(50) NOT NULL,
             CONTENT BLOB NOT NULL,
             CONTENT_TYPE VARCHAR(50),
             TYPE_ID INTEGER NOT NULL,
             APP_ID VARCHAR(255) NOT NULL,
             TENANT_ID INTEGER NOT NULL,
             VERSION VARCHAR(15) NOT NULL,
             CREATED_AT TIMESTAMP NOT NULL,
             UPDATED_AT TIMESTAMP NOT NULL,
             PRIMARY KEY (ID),
             FOREIGN KEY (TYPE_ID) REFERENCES IDN_NOTIFICATION_TYPE(ID) ON DELETE CASCADE,
             CONSTRAINT APP_NOTIFICATION_TEMPLATE_KEY_CONSTRAINT UNIQUE (TEMPLATE_KEY, TYPE_ID, APP_ID, TENANT_ID),
             CONSTRAINT APP_NOTIFICATION_TEMPLATE_LOCALE_CONSTRAINT UNIQUE (LOCALE, TYPE_ID, APP_ID, TENANT_ID)
           )';
    END IF;

    SELECT COUNT(*) INTO sequence_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_NOTIFICATION_APP_TEMPLATE_SEQ';

    IF sequence_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_NOTIFICATION_APP_TEMPLATE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER IDN_NOTIFICATION_APP_TEMPLATE_TRIG
  BEFORE INSERT
    ON IDN_NOTIFICATION_APP_TEMPLATE
    REFERENCING NEW AS NEW
    FOR EACH ROW
  BEGIN
  SELECT IDN_NOTIFICATION_APP_TEMPLATE_SEQ.nextval INTO :NEW.ID FROM dual;
  END;
/

DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_ACTION';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_ACTION (
           UUID CHAR(36) NOT NULL,
           TYPE VARCHAR(50) NOT NULL,
           NAME VARCHAR(255) NOT NULL,
           DESCRIPTION VARCHAR(255),
           STATUS VARCHAR(10) NOT NULL,
           TENANT_ID INTEGER NOT NULL,
           VERSION VARCHAR(15) NOT NULL,
           PRIMARY KEY (UUID)
        )';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_ACTION_PROPERTIES';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_ACTION_PROPERTIES (
           ACTION_UUID CHAR(36) NOT NULL,
           PROPERTY_NAME VARCHAR(100) NOT NULL,
           PROPERTY_VALUE VARCHAR(255) NOT NULL,
           TENANT_ID INTEGER NOT NULL,
           PRIMARY KEY (ACTION_UUID, PROPERTY_NAME),
           FOREIGN KEY (ACTION_UUID) REFERENCES IDN_ACTION(UUID) ON DELETE CASCADE
        )';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
    sequence_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_OAUTH2_TOKEN_CLAIMS';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_OAUTH2_TOKEN_CLAIMS (
             ID INTEGER,
             APP_ID INTEGER NOT NULL,
             CLAIM_URI VARCHAR(255) NOT NULL,
             PRIMARY KEY (ID),
             CONSTRAINT TOKEN_CLAIMS_CONSTRAINT UNIQUE (APP_ID, CLAIM_URI),
             FOREIGN KEY (APP_ID) REFERENCES IDN_OAUTH_CONSUMER_APPS(ID) ON DELETE CASCADE
        )';
    END IF;

    SELECT COUNT(*) INTO sequence_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_OAUTH2_TOKEN_CLAIMS_SEQ';

    IF sequence_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_OAUTH2_TOKEN_CLAIMS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER IDN_OAUTH2_TOKEN_CLAIMS_TRIG
  BEFORE INSERT
    ON IDN_OAUTH2_TOKEN_CLAIMS
    REFERENCING NEW AS NEW
    FOR EACH ROW
  BEGIN
  SELECT IDN_OAUTH2_TOKEN_CLAIMS_SEQ.nextval INTO :NEW.ID FROM dual;
  END;
/

DECLARE
    table_exists NUMBER;
    sequence_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_SAML2_SERVICE_PROVIDER';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_SAML2_SERVICE_PROVIDER (
            ID INTEGER NOT NULL,
            ISSUER VARCHAR(255) NOT NULL,
            DEFAULT_ASSERTION_CONSUMER_URL VARCHAR(2048) NOT NULL,
            NAME_ID_FORMAT VARCHAR(255) NOT NULL,
            CERT_ALIAS VARCHAR(255),
            REQ_SIG_VALIDATION CHAR(1),
            SIGN_RESPONSE CHAR(1) NOT NULL,
            SIGN_ASSERTIONS CHAR(1) NOT NULL,
            SIGNING_ALGO VARCHAR(255) NOT NULL,
            DIGEST_ALGO VARCHAR(255) NOT NULL,
            ENCRYPT_ASSERTION CHAR(1),
            ASSERTION_ENCRYPTION_ALGO VARCHAR(255),
            KEY_ENCRYPTION_ALGO VARCHAR(255),
            ATTR_PROFILE_ENABLED CHAR(1) NOT NULL,
            ATTR_SERVICE_INDEX VARCHAR(255),
            SLO_PROFILE_ENABLED CHAR(1) NOT NULL,
            SLO_METHOD VARCHAR(255),
            SLO_RESPONSE_URL VARCHAR(2048),
            SLO_REQUEST_URL VARCHAR(2048),
            IDP_INIT_SSO_ENABLED CHAR(1),
            IDP_INIT_SLO_ENABLED CHAR(1),
            QUERY_REQUEST_PROFILE_ENABLED CHAR(1) NOT NULL,
            ECP_ENABLED CHAR(1) NOT NULL,
            ARTIFACT_BINDING_ENABLED CHAR(1) NOT NULL,
            ARTIFACT_RESOLVE_REQ_SIG_VALIDATION CHAR(1),
            IDP_ENTITY_ID_ALIAS VARCHAR(255),
            ISSUER_QUALIFIER VARCHAR(255),
            SUPPORTED_ASSERTION_QUERY_REQUEST_TYPES VARCHAR(255),
            TENANT_ID INTEGER NOT NULL,
            VERSION VARCHAR(15) NOT NULL,
            CREATED_AT TIMESTAMP NOT NULL,
            UPDATED_AT TIMESTAMP NOT NULL,
            ATTR_NAME_FORMAT VARCHAR(255),
            PRIMARY KEY (ID),
            CONSTRAINT IDN_SAML2_SERVICE_PROVIDER_CONSTRAINT UNIQUE (ISSUER, TENANT_ID)
        )';
    END IF;

    SELECT COUNT(*) INTO sequence_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_SAML2_SERVICE_PROVIDER_SEQ';

    IF sequence_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_SAML2_SERVICE_PROVIDER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER IDN_SAML2_SERVICE_PROVIDER_TRIG
    BEFORE INSERT
    ON IDN_SAML2_SERVICE_PROVIDER
    REFERENCING NEW AS NEW
    FOR EACH ROW
    BEGIN
        SELECT IDN_SAML2_SERVICE_PROVIDER_SEQ.nextval INTO :NEW.ID FROM dual;
    END;
/

DECLARE
    table_exists NUMBER;
    sequence_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_SAML2_SP_PROPERTIES';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_SAML2_SP_PROPERTIES (
            ID INTEGER NOT NULL,
            PROPERTY_NAME VARCHAR(255) NOT NULL,
            PROPERTY_VALUE VARCHAR(2048) NOT NULL,
            SP_ID INTEGER NOT NULL,
            PRIMARY KEY (ID),
            FOREIGN KEY (SP_ID) REFERENCES IDN_SAML2_SERVICE_PROVIDER(ID) ON DELETE CASCADE
        )';
    END IF;

    SELECT COUNT(*) INTO sequence_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_SAML2_SP_PROPERTIES_SEQ';

    IF sequence_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_SAML2_SP_PROPERTIES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER IDN_SAML2_SP_PROPERTIES_TRIG
    BEFORE INSERT
    ON IDN_SAML2_SP_PROPERTIES
    REFERENCING NEW AS NEW
    FOR EACH ROW
    BEGIN
        SELECT IDN_SAML2_SP_PROPERTIES_SEQ.nextval INTO :NEW.ID FROM dual;
    END;
/

DECLARE
    table_exists NUMBER;
    sequence_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'AUTHORIZATION_DETAILS_TYPES';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE AUTHORIZATION_DETAILS_TYPES (
            ID CHAR(36) NOT NULL,
            TYPE VARCHAR(255) NOT NULL,
            API_ID CHAR(36) NOT NULL,
            CURSOR_KEY INTEGER NOT NULL,
            NAME VARCHAR(255),
            DESCRIPTION VARCHAR(255),
            JSON_SCHEMA CLOB NOT NULL,
            TENANT_ID INTEGER,
            PRIMARY KEY (ID),
            CONSTRAINT AUTHORIZATION_DETAILS_TYPES_UNIQUE_CONSTRAINT UNIQUE (TYPE, TENANT_ID),
            FOREIGN KEY (API_ID) REFERENCES API_RESOURCE(ID) ON DELETE CASCADE
        )';
    END IF;
    SELECT COUNT(*) INTO sequence_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'AUTHORIZATION_DETAILS_TYPES_SEQ';
    IF sequence_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE AUTHORIZATION_DETAILS_TYPES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER AUTHORIZATION_DETAILS_TYPES_TRIG
    BEFORE INSERT
    ON AUTHORIZATION_DETAILS_TYPES
    REFERENCING NEW AS NEW
    FOR EACH ROW
        BEGIN
            SELECT AUTHORIZATION_DETAILS_TYPES_SEQ.nextval INTO :NEW.CURSOR_KEY FROM dual;
        END;
/

DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'AUTHORIZED_AUTHORIZATION_DETAILS_TYPES';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE AUTHORIZED_AUTHORIZATION_DETAILS_TYPES (
            APP_ID CHAR(36) NOT NULL,
            API_ID CHAR(36) NOT NULL,
            TYPE_ID CHAR(36) NOT NULL,
            PRIMARY KEY (APP_ID, API_ID, TYPE_ID),
            FOREIGN KEY (API_ID) REFERENCES API_RESOURCE(ID),
            FOREIGN KEY (TYPE_ID) REFERENCES AUTHORIZATION_DETAILS_TYPES(ID) ON DELETE CASCADE,
            FOREIGN KEY (APP_ID) REFERENCES SP_APP(UUID),
            FOREIGN KEY (APP_ID, API_ID) REFERENCES AUTHORIZED_API(APP_ID, API_ID) ON DELETE CASCADE,
            CONSTRAINT AUTHORIZED_AUTHORIZATION_DETAILS_UNIQUE UNIQUE (APP_ID, TYPE_ID)
        )';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
    sequence_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_OAUTH2_USER_CONSENTED_AUTHORIZATION_DETAILS';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_OAUTH2_USER_CONSENTED_AUTHORIZATION_DETAILS (
            ID INTEGER NOT NULL,
            CONSENT_ID VARCHAR(255) NOT NULL,
            TYPE_ID CHAR(36) NOT NULL,
            AUTHORIZATION_DETAILS CLOB NOT NULL,
            CONSENT CHAR(1) DEFAULT ''0'' NOT NULL,
            TENANT_ID INTEGER NOT NULL,
            PRIMARY KEY (ID, CONSENT_ID, TYPE_ID),
            FOREIGN KEY (TYPE_ID) REFERENCES AUTHORIZATION_DETAILS_TYPES(ID) ON DELETE CASCADE,
            FOREIGN KEY (CONSENT_ID) REFERENCES IDN_OAUTH2_USER_CONSENT(CONSENT_ID) ON DELETE CASCADE
        )';
    END IF;

    SELECT COUNT(*) INTO sequence_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_OAUTH2_USER_CONSENTED_AUTHORIZATION_DETAILS_SEQ';

    IF sequence_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_OAUTH2_USER_CONSENTED_AUTHORIZATION_DETAILS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER IDN_OAUTH2_USER_CONSENTED_AUTHORIZATION_DETAILS_TRIG
    BEFORE INSERT
    ON IDN_OAUTH2_USER_CONSENTED_AUTHORIZATION_DETAILS
    REFERENCING NEW AS NEW
    FOR EACH ROW
        BEGIN
            SELECT IDN_OAUTH2_USER_CONSENTED_AUTHORIZATION_DETAILS_SEQ.nextval INTO :NEW.ID FROM dual;
        END;
/

DECLARE
    table_exists NUMBER;
    sequence_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_OAUTH2_ACCESS_TOKEN_AUTHORIZATION_DETAILS';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_OAUTH2_ACCESS_TOKEN_AUTHORIZATION_DETAILS (
            ID INTEGER NOT NULL,
            TYPE_ID CHAR(36) NOT NULL,
            AUTHORIZATION_DETAILS CLOB NOT NULL,
            TOKEN_ID VARCHAR (255),
            TENANT_ID INTEGER DEFAULT -1,
            PRIMARY KEY (ID, TOKEN_ID, TYPE_ID),
            FOREIGN KEY (TYPE_ID) REFERENCES AUTHORIZATION_DETAILS_TYPES(ID) ON DELETE CASCADE,
            FOREIGN KEY (TOKEN_ID) REFERENCES IDN_OAUTH2_ACCESS_TOKEN(TOKEN_ID) ON DELETE CASCADE
        )';
    END IF;
    SELECT COUNT(*) INTO sequence_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_OAUTH2_ACCESS_TOKEN_AUTHORIZATION_DETAILS_SEQ';
    IF sequence_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_OAUTH2_ACCESS_TOKEN_AUTHORIZATION_DETAILS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER IDN_OAUTH2_ACCESS_TOKEN_AUTHORIZATION_DETAILS_TRIG
    BEFORE INSERT
    ON IDN_OAUTH2_ACCESS_TOKEN_AUTHORIZATION_DETAILS
    REFERENCING NEW AS NEW
    FOR EACH ROW
        BEGIN
            SELECT IDN_OAUTH2_ACCESS_TOKEN_AUTHORIZATION_DETAILS_SEQ.nextval INTO :NEW.ID FROM dual;
        END;
/

DECLARE
    table_exists NUMBER;
    sequence_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_OAUTH2_AUTHZ_CODE_AUTHORIZATION_DETAILS';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_OAUTH2_AUTHZ_CODE_AUTHORIZATION_DETAILS (
            ID INTEGER NOT NULL,
            TYPE_ID CHAR(36) NOT NULL,
            AUTHORIZATION_DETAILS CLOB NOT NULL,
            CODE_ID VARCHAR(255),
            TENANT_ID INTEGER DEFAULT -1,
            PRIMARY KEY (ID, CODE_ID, TYPE_ID),
            FOREIGN KEY (TYPE_ID) REFERENCES AUTHORIZATION_DETAILS_TYPES(ID) ON DELETE CASCADE,
            FOREIGN KEY (CODE_ID) REFERENCES IDN_OAUTH2_AUTHORIZATION_CODE(CODE_ID) ON DELETE CASCADE
        )';
    END IF;

    SELECT COUNT(*) INTO sequence_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_OAUTH2_AUTHZ_CODE_AUTHORIZATION_DETAILS_SEQ';

    IF sequence_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_OAUTH2_AUTHZ_CODE_AUTHORIZATION_DETAILS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER IDN_OAUTH2_AUTHZ_CODE_AUTHORIZATION_DETAILS_TRIG
    BEFORE INSERT
    ON IDN_OAUTH2_AUTHZ_CODE_AUTHORIZATION_DETAILS
    REFERENCING NEW AS NEW
    FOR EACH ROW
    BEGIN
        SELECT IDN_OAUTH2_AUTHZ_CODE_AUTHORIZATION_DETAILS_SEQ.nextval INTO :NEW.ID FROM dual;
    END;
/

DECLARE
    table_exists NUMBER;
    sequence_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_RULE';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_RULE (
            ID INTEGER,
            UUID CHAR(36) NOT NULL,
            CONTENT BLOB NOT NULL,
            IS_ACTIVE CHAR (5) DEFAULT ''1'',
            TENANT_ID INTEGER NOT NULL,
            VERSION VARCHAR(15) NOT NULL,
            PRIMARY KEY (ID),
            UNIQUE (UUID)
        )';
    END IF;

    SELECT COUNT(*) INTO sequence_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_RULE_SEQ';

    IF sequence_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_RULE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER IDN_RULE_TRIGGER
    BEFORE INSERT ON IDN_RULE
    REFERENCING NEW AS NEW FOR EACH ROW
        BEGIN
          SELECT IDN_RULE_SEQ.nextval INTO :NEW.ID FROM dual;
        END;
/

DECLARE
    table_exists NUMBER;
    sequence_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_RULE_REFERENCES';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_RULE_REFERENCES (
            ID INTEGER,
            RULE_ID INTEGER NOT NULL,
            FIELD_NAME VARCHAR(100) NOT NULL,
            FIELD_REFERENCE VARCHAR(255) NOT NULL,
            TENANT_ID INTEGER NOT NULL,
            PRIMARY KEY (ID),
            FOREIGN KEY (RULE_ID) REFERENCES IDN_RULE(ID) ON DELETE CASCADE
        )';
    END IF;
    SELECT COUNT(*) INTO sequence_exists FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_RULE_REFERENCES_SEQ';
    IF sequence_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_RULE_REFERENCES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/
CREATE OR REPLACE TRIGGER IDN_RULE_REFERENCES_TRIGGER
    BEFORE INSERT ON IDN_RULE_REFERENCES
    REFERENCING NEW AS NEW FOR EACH ROW
        BEGIN
          SELECT IDN_RULE_REFERENCES_SEQ.nextval INTO :NEW.ID FROM dual;
        END;
/

DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_PUSH_DEVICE_STORE';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_PUSH_DEVICE_STORE (
            ID VARCHAR(255) NOT NULL,
            USER_ID VARCHAR(255) NOT NULL,
            DEVICE_NAME VARCHAR(45) NOT NULL,
            DEVICE_MODEL VARCHAR(45) NOT NULL,
            DEVICE_TOKEN VARCHAR(255) NOT NULL,
            DEVICE_HANDLE VARCHAR(255),
            PUBLIC_KEY VARCHAR(2048) NOT NULL,
            PROVIDER VARCHAR(45) NOT NULL,
            TENANT_ID INTEGER NOT NULL,
            PRIMARY KEY (ID),
            UNIQUE (USER_ID)
        )';
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE ALTER_IDP_AUTHENTICATOR
IS
  BEGIN
    declare
      column_count INTEGER;
    begin
      -- Add DEFINED_BY column
      select count(*) INTO column_count FROM ALL_TAB_COLUMNS WHERE OWNER = (SELECT USER FROM DUAL) AND TABLE_NAME = 'IDP_AUTHENTICATOR' AND COLUMN_NAME = 'DEFINED_BY';
      IF column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDP_AUTHENTICATOR ADD (DEFINED_BY VARCHAR(25) DEFAULT ''SYSTEM'' NOT NULL)';
      END IF;

      -- Add AUTHENTICATION_TYPE column
      select count(*) INTO column_count FROM ALL_TAB_COLUMNS WHERE OWNER = (SELECT USER FROM DUAL) AND TABLE_NAME = 'IDP_AUTHENTICATOR' AND COLUMN_NAME = 'AUTHENTICATION_TYPE';
      IF column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDP_AUTHENTICATOR ADD (AUTHENTICATION_TYPE VARCHAR(25) DEFAULT ''IDENTIFICATION'' NOT NULL)';
      END IF;

      -- Add IMAGE_URL column
      select count(*) INTO column_count FROM ALL_TAB_COLUMNS WHERE OWNER = (SELECT USER FROM DUAL) AND TABLE_NAME = 'IDP_AUTHENTICATOR' AND COLUMN_NAME = 'IMAGE_URL';
      IF column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDP_AUTHENTICATOR ADD (IMAGE_URL VARCHAR(1024))';
      END IF;

      -- Add DESCRIPTION column
      select count(*) INTO column_count FROM ALL_TAB_COLUMNS WHERE OWNER = (SELECT USER FROM DUAL) AND TABLE_NAME = 'IDP_AUTHENTICATOR' AND COLUMN_NAME = 'DESCRIPTION';
      IF column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDP_AUTHENTICATOR ADD (DESCRIPTION VARCHAR(1024))';
      END IF;
    END;
  END;
/

CALL ALTER_IDP_AUTHENTICATOR()
/
DROP PROCEDURE ALTER_IDP_AUTHENTICATOR
/

CREATE OR REPLACE PROCEDURE ALTER_SP_APP AS
  v_column_count NUMBER;
BEGIN
  SELECT COUNT(*)
  INTO v_column_count
  FROM ALL_TAB_COLUMNS
  WHERE TABLE_NAME = 'SP_APP'
    AND COLUMN_NAME = 'VERSION';

  IF v_column_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE SP_APP ADD (VERSION VARCHAR(255) DEFAULT ''v1.0.0'' NOT NULL)';
  END IF;
END ALTER_SP_APP;
/
CALL ALTER_SP_APP()
/
DROP PROCEDURE ALTER_SP_APP
/

CREATE OR REPLACE PROCEDURE ALTER_IDN_CERTIFICATE AS
  v_column_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_column_count
    FROM ALL_TAB_COLUMNS
    WHERE TABLE_NAME = 'IDN_CERTIFICATE'
        AND COLUMN_NAME = 'UUID';

    IF v_column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_CERTIFICATE ADD (UUID CHAR(36))';
    END IF;
    END ALTER_IDN_CERTIFICATE;
/

CALL ALTER_IDN_CERTIFICATE()
/
DROP PROCEDURE ALTER_IDN_CERTIFICATE
/

INSERT INTO IDN_SECRET_TYPE (ID, NAME, DESCRIPTION)
SELECT '33f0a41b-569d-4ea5-a891-6c0e78a1c3b0', 'ACTION_API_ENDPOINT_AUTH_SECRETS', 'Secret type to uniquely identify secrets relevant to action endpoint authentication properties' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM IDN_SECRET_TYPE WHERE id = '33f0a41b-569d-4ea5-a891-6c0e78a1c3b0')
/

INSERT INTO IDN_SECRET_TYPE (ID, NAME, DESCRIPTION)
SELECT 'b411dafd-e2c4-4d2f-afba-3900d802725a', 'PUSH_PROVIDER_SECRET_PROPERTIES', 'Secret type to uniquely identify secrets relevant to push provider properties' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM IDN_SECRET_TYPE WHERE id = 'b411dafd-e2c4-4d2f-afba-3900d802725a')
/

INSERT INTO IDN_SECRET_TYPE (ID, NAME, DESCRIPTION)
SELECT 'ce234fd5-3fb4-4a40-9911-818be9b4ee10', 'REMOTE_LOGGING_SECRETS', 'Secret type to uniquely identify secrets relevant to remote logging properties' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM IDN_SECRET_TYPE WHERE id = 'ce234fd5-3fb4-4a40-9911-818be9b4ee10')
/

INSERT INTO IDN_CONFIG_TYPE (ID, NAME, DESCRIPTION)
SELECT '3e5b1f91-72d8-4fbc-94d1-1b9a4f8c3b07', 'IMPERSONATION_CONFIGURATION', 'A resource type to keep the tenant impersonation preferences.' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM IDN_CONFIG_TYPE WHERE id = '3e5b1f91-72d8-4fbc-94d1-1b9a4f8c3b07' OR name = 'IMPERSONATION_CONFIGURATION')
/

INSERT INTO IDN_CONFIG_TYPE (ID, NAME, DESCRIPTION)
SELECT '91116e95-ca63-4787-be2d-de13d04d1b55', 'CERTIFICATE_VALIDATOR', 'A resource type to keep the certificate validators.' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM IDN_CONFIG_TYPE WHERE id = '91116e95-ca63-4787-be2d-de13d04d1b55' OR name = 'CERTIFICATE_VALIDATOR')
/
INSERT INTO IDN_CONFIG_TYPE (ID, NAME, DESCRIPTION)
SELECT 'a17952b9-0942-4669-8529-479ca481146b', 'CERTIFICATE_REVOCATION_VALIDATION_CA', 'A resource type to keep the certificate revocation validation related certificate authorities.' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM IDN_CONFIG_TYPE WHERE id = 'a17952b9-0942-4669-8529-479ca481146b' OR name = 'CERTIFICATE_REVOCATION_VALIDATION_CA')
/
INSERT INTO IDN_CONFIG_TYPE (ID, NAME, DESCRIPTION)
SELECT '32360745-9c3e-4391-b563-66f17f0eb93a', 'ADMIN_ADVISORY_BANNER', 'A resource type to store admin advisory banner configurations.' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM IDN_CONFIG_TYPE WHERE id = '32360745-9c3e-4391-b563-66f17f0eb93a' OR name = 'ADMIN_ADVISORY_BANNER')
/
INSERT INTO IDN_CONFIG_TYPE (ID, NAME, DESCRIPTION)
SELECT '82ab7001-fb0e-44da-9169-1f63e4964d9b', 'REMOTE_LOGGING_CONFIG', 'A resource type to store remote server logger configurations.' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM IDN_CONFIG_TYPE WHERE id = '82ab7001-fb0e-44da-9169-1f63e4964d9b' OR name = 'REMOTE_LOGGING_CONFIG')
/

CREATE OR REPLACE PROCEDURE ALTER_IDN_OAUTH2_TOKEN_AUDIT
IS
  BEGIN
    declare
      column_count INTEGER;
    begin
      -- Add TOKEN_BINDING_REF column
      select count(*) INTO column_count FROM ALL_TAB_COLUMNS WHERE OWNER = (SELECT USER FROM DUAL) AND TABLE_NAME = 'IDN_OAUTH2_ACCESS_TOKEN_AUDIT' AND COLUMN_NAME = 'TOKEN_BINDING_REF';
      IF column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_OAUTH2_ACCESS_TOKEN_AUDIT ADD (TOKEN_BINDING_REF VARCHAR2(32) DEFAULT ''NONE'')';
      END IF;

      -- Add CONSENTED_TOKEN column
      select count(*) INTO column_count FROM ALL_TAB_COLUMNS WHERE OWNER = (SELECT USER FROM DUAL) AND TABLE_NAME = 'IDN_OAUTH2_ACCESS_TOKEN_AUDIT' AND COLUMN_NAME = 'CONSENTED_TOKEN';
      IF column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_OAUTH2_ACCESS_TOKEN_AUDIT ADD (CONSENTED_TOKEN VARCHAR(6))';
      END IF;

      -- Add AUTHORIZED_ORGANIZATION column
      select count(*) INTO column_count FROM ALL_TAB_COLUMNS WHERE OWNER = (SELECT USER FROM DUAL) AND TABLE_NAME = 'IDN_OAUTH2_ACCESS_TOKEN_AUDIT' AND COLUMN_NAME = 'AUTHORIZED_ORGANIZATION';
      IF column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_OAUTH2_ACCESS_TOKEN_AUDIT ADD (AUTHORIZED_ORGANIZATION varchar(36) DEFAULT ''NONE'' NOT NULL)';
      END IF;
    end;
  END;
/

CALL ALTER_IDN_OAUTH2_TOKEN_AUDIT()
/
DROP PROCEDURE ALTER_IDN_OAUTH2_TOKEN_AUDIT
/

-- --------------------------- INDEX CREATION -----------------------------

-- ACTIONS --
DECLARE
  v_index_exists NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_index_exists FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_IDN_ACTION_TY_TI';
  IF v_index_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_IDN_ACTION_TY_TI ON IDN_ACTION (TYPE, TENANT_ID)';
  END IF;
END;
/

DECLARE
  v_index_exists NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_index_exists FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_IDN_ACTION_PROPERTIES_AU_TI';
  IF v_index_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_IDN_ACTION_PROPERTIES_AU_TI ON IDN_ACTION_PROPERTIES (ACTION_UUID, TENANT_ID)';
  END IF;
END;
/

-- SAML --
DECLARE
    v_index_exists NUMBER;
BEGIN
    SELECT COUNT(1) INTO v_index_exists FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_SAML2_SP_TENANT_ID';
    IF v_index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_SAML2_SP_TENANT_ID ON IDN_SAML2_SERVICE_PROVIDER (TENANT_ID)';
    END IF;
END;
/

DECLARE
    v_index_exists NUMBER;
BEGIN
    SELECT COUNT(1) INTO v_index_exists FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_SAML2_SP_PROPERTIES';
    IF v_index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_SAML2_SP_PROPERTIES ON IDN_SAML2_SP_PROPERTIES (SP_ID)';
    END IF;
END;
/

-- RULES --
DECLARE
    v_index_exists NUMBER;
BEGIN
    SELECT COUNT(1) INTO v_index_exists FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_IDN_RULE_UUID_TID';
    IF v_index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_IDN_RULE_UUID_TID ON IDN_RULE (UUID, TENANT_ID)';
    END IF;
END;
/

DECLARE
    v_index_exists NUMBER;
BEGIN
    SELECT COUNT(1) INTO v_index_exists FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_IDN_RULE_REF_RID_TID';
    IF v_index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_IDN_RULE_REF_RID_TID ON IDN_RULE_REFERENCES (RULE_ID, TENANT_ID)';
    END IF;
END;
/

-- SP_CLAIM_MAPPING --
DECLARE
    v_index_exists NUMBER;
BEGIN
    SELECT COUNT(1) INTO v_index_exists FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_SPCM_APP';
    IF v_index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_SPCM_APP ON SP_CLAIM_MAPPING (APP_ID)';
    END IF;
END;
/

-- IDP_AUTHENTICATOR --
DECLARE
    v_index_exists NUMBER;
BEGIN
    SELECT COUNT(1) INTO v_index_exists FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_IDP_AUTH_DEFINED_BY';
    IF v_index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_IDP_AUTH_DEFINED_BY ON IDP_AUTHENTICATOR (DEFINED_BY)';
    END IF;
END;
/

DECLARE
    v_index_exists NUMBER;
BEGIN
    SELECT COUNT(1) INTO v_index_exists FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_IDP_AUTH_IDP_ID';
    IF v_index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_IDP_AUTH_IDP_ID ON IDP_AUTHENTICATOR (IDP_ID)';
    END IF;
END;
/


-- IDN_SECRET --
DECLARE
    column_exists NUMBER;
    nullable_flag VARCHAR2(1);
BEGIN
    SELECT COUNT(*) INTO column_exists FROM ALL_TAB_COLUMNS WHERE TABLE_NAME = 'IDN_SECRET' AND COLUMN_NAME = 'SECRET_VALUE_CLOB';
    IF column_exists = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE IDN_SECRET ADD SECRET_VALUE_CLOB CLOB';
    END IF;

    SELECT NULLABLE INTO nullable_flag FROM ALL_TAB_COLUMNS WHERE TABLE_NAME = 'IDN_SECRET' AND COLUMN_NAME = 'SECRET_VALUE';
    IF nullable_flag = 'N' THEN
            EXECUTE IMMEDIATE 'ALTER TABLE IDN_SECRET MODIFY SECRET_VALUE NULL';
    END IF;
END;
/
