CREATE TABLE IF NOT EXISTS UM_ROLE (
			UM_ID INTEGER NOT NULL AUTO_INCREMENT,
            UM_ROLE_UUID VARCHAR(255) NOT NULL,
			UM_ROLE_NAME VARCHAR(255) NOT NULL,
			UM_TENANT_ID INTEGER DEFAULT 0,
			UM_SHARED_ROLE BOOLEAN DEFAULT FALSE,
            UM_CREATED_TIME TIMESTAMP NOT NULL,
            UM_LAST_MODIFIED TIMESTAMP NOT NULL,
			PRIMARY KEY (UM_ID, UM_TENANT_ID),
            UNIQUE(UM_ROLE_UUID),
			UNIQUE(UM_ROLE_NAME, UM_TENANT_ID));

CREATE TABLE IF NOT EXISTS UM_USER (
			UM_ID INTEGER NOT NULL AUTO_INCREMENT,
			UM_USER_ID VARCHAR(255) NOT NULL,
			UM_USER_NAME VARCHAR(255) NOT NULL,
			UM_USER_PASSWORD VARCHAR(255) NOT NULL,
			UM_SALT_VALUE VARCHAR(31),
			UM_REQUIRE_CHANGE BOOLEAN DEFAULT FALSE,
            		UM_CHANGED_TIME TIMESTAMP NOT NULL,
			UM_TENANT_ID INTEGER DEFAULT 0,
			PRIMARY KEY (UM_ID, UM_TENANT_ID),
			UNIQUE(UM_USER_ID),
            		UNIQUE(UM_USER_NAME, UM_TENANT_ID));

CREATE UNIQUE INDEX IF NOT EXISTS INDEX_UM_USERNAME_UM_TENANT_ID ON UM_USER(UM_USER_NAME, UM_TENANT_ID);

CREATE TABLE IF NOT EXISTS UM_USER_ATTRIBUTE (
			UM_ID INTEGER NOT NULL AUTO_INCREMENT,
			UM_ATTR_NAME VARCHAR(255) NOT NULL,
			UM_ATTR_VALUE VARCHAR(1024),
            		UM_PROFILE_ID VARCHAR(255),
            		UM_USER_ID INTEGER,
            		UM_TENANT_ID INTEGER DEFAULT 0,
			PRIMARY KEY (UM_ID, UM_TENANT_ID),
			FOREIGN KEY (UM_USER_ID, UM_TENANT_ID) REFERENCES UM_USER(UM_ID, UM_TENANT_ID));

CREATE INDEX IF NOT EXISTS UM_USER_ID_INDEX ON UM_USER_ATTRIBUTE(UM_USER_ID);
CREATE INDEX IF NOT EXISTS UM_ATTR_NAME_VALUE_INDEX ON UM_USER_ATTRIBUTE(UM_ATTR_NAME, UM_ATTR_VALUE);


CREATE TABLE IF NOT EXISTS UM_USER_ROLE (
			UM_ID INTEGER NOT NULL AUTO_INCREMENT,
			UM_ROLE_ID INTEGER NOT NULL,
			UM_USER_ID INTEGER NOT NULL,
			UM_TENANT_ID INTEGER DEFAULT 0,
			UNIQUE (UM_USER_ID, UM_ROLE_ID, UM_TENANT_ID),
			FOREIGN KEY (UM_ROLE_ID, UM_TENANT_ID) REFERENCES UM_ROLE(UM_ID, UM_TENANT_ID),
			FOREIGN KEY (UM_USER_ID, UM_TENANT_ID) REFERENCES UM_USER(UM_ID, UM_TENANT_ID),
			PRIMARY KEY (UM_ID, UM_TENANT_ID));