CREATE OR REPLACE PROCEDURE ALTER_UM_ORG
BEGIN ATOMIC
    IF EXISTS(SELECT * FROM SYSCAT.TABLES WHERE TABNAME='UM_ORG')
	THEN
	    IF NOT EXISTS(SELECT * FROM SYSCAT.COLUMNS WHERE TABNAME='UM_ORG' AND COLNAME='UM_ORG_VERSION')
        THEN
            EXECUTE IMMEDIATE 'ALTER TABLE UM_ORG ADD COLUMN UM_ORG_VERSION VARCHAR(20) NOT NULL DEFAULT ''v0.0.0''';
        END IF;
    END IF;
END
/
CALL ALTER_UM_ORG
/
DROP PROCEDURE ALTER_UM_ORG
/
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM SYSCAT.INDEXES
    WHERE INDNAME = 'INDEX_UM_ORG_UM_ORG_NAME' AND TABSCHEMA = CURRENT_SCHEMA
  ) THEN
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_UM_ORG_UM_ORG_NAME ON UM_ORG(UM_ORG_NAME)';
  END IF;
END
/
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM SYSCAT.INDEXES
    WHERE INDNAME = 'INDEX_UM_ORG_HIERARCHY_UM_ID' AND TABSCHEMA = CURRENT_SCHEMA
  ) THEN
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_UM_ORG_HIERARCHY_UM_ID ON UM_ORG_HIERARCHY(UM_ID)';
  END IF;
END
/
