IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'UM_ORG' AND COLUMN_NAME = 'UM_ORG_VERSION')
ALTER TABLE UM_ORG ADD UM_ORG_VERSION VARCHAR(20) NOT NULL DEFAULT 'v0.0.0';

IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'INDEX_UM_ORG_UM_ORG_NAME')
DROP INDEX UM_ORG.INDEX_UM_ORG_UM_ORG_NAME
CREATE INDEX INDEX_UM_ORG_UM_ORG_NAME ON UM_ORG(UM_ORG_NAME);

IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'INDEX_UM_ORG_HIERARCHY_UM_ID')
DROP INDEX UM_ORG_HIERARCHY.INDEX_UM_ORG_HIERARCHY_UM_ID
CREATE INDEX INDEX_UM_ORG_HIERARCHY_UM_ID ON UM_ORG_HIERARCHY(UM_ID);
