CREATE OR REPLACE PROCEDURE ALTER_UM_ORG
IS
  BEGIN
    declare
      column_count INTEGER;
    begin
      select count(*) INTO column_count
      FROM ALL_TAB_COLUMNS
      WHERE OWNER = (SELECT USER FROM DUAL)
        AND TABLE_NAME = 'UM_ORG'
        AND COLUMN_NAME = 'UM_ORG_VERSION';
      IF column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE UM_ORG ADD (UM_ORG_VERSION VARCHAR(20) DEFAULT ''v0.0.0'' NOT NULL)';
      END IF;
    end;
  END;
/
CALL ALTER_UM_ORG()
/
DROP PROCEDURE ALTER_UM_ORG
/
DECLARE
   COUNT_INDEXES INTEGER;
   BEGIN
     SELECT COUNT(*) INTO COUNT_INDEXES
       FROM USER_IND_COLUMNS
       WHERE TABLE_NAME = 'UM_ORG' AND COLUMN_NAME = 'UM_ORG_NAME' AND COLUMN_POSITION = 1;

     IF COUNT_INDEXES = 0 THEN
       EXECUTE IMMEDIATE 'CREATE INDEX INDEX_UM_ORG_UM_ORG_NAME ON UM_ORG(UM_ORG_NAME)';
     END IF;
   END;
 /
 DECLARE
    COUNT_INDEXES INTEGER;
    BEGIN
      SELECT COUNT(*) INTO COUNT_INDEXES
        FROM USER_IND_COLUMNS
        WHERE TABLE_NAME = 'UM_ORG_HIERARCHY' AND COLUMN_NAME = 'UM_ID' AND COLUMN_POSITION = 1;

      IF COUNT_INDEXES = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX INDEX_UM_ORG_HIERARCHY_UM_ID ON UM_ORG_HIERARCHY(UM_ID)';
      END IF;
    END;
  /
