CREATE OR REPLACE PROCEDURE ALTER_UM_ORG AS
  v_column_count NUMBER;
BEGIN
  SELECT COUNT(*)
  INTO v_column_count
  FROM ALL_TAB_COLUMNS
  WHERE TABLE_NAME = 'UM_ORG'
    AND COLUMN_NAME = 'UM_ORG_VERSION';

  IF v_column_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE UM_ORG ADD (UM_ORG_VERSION VARCHAR(20) DEFAULT ''v0.0.0'' NOT NULL)';
  END IF;
END ALTER_UM_ORG;
/
CALL ALTER_UM_ORG()
/
DROP PROCEDURE ALTER_UM_ORG
/
CREATE INDEX INDEX_UM_ORG_UM_ORG_NAME ON UM_ORG(UM_ORG_NAME)
/
CREATE INDEX INDEX_UM_ORG_HIERARCHY_UM_ID ON UM_ORG_HIERARCHY(UM_ID)
/
