ALTER TABLE UM_ORG ADD COLUMN IF NOT EXISTS UM_ORG_VERSION VARCHAR(20) NOT NULL DEFAULT 'v0.0.0';

CREATE INDEX IF NOT EXISTS INDEX_UM_ORG_UM_ORG_NAME ON UM_ORG(UM_ORG_NAME);

CREATE INDEX IF NOT EXISTS INDEX_UM_ORG_HIERARCHY_UM_ID ON UM_ORG_HIERARCHY(UM_ID);
