CREATE OR REPLACE PROCEDURE ADD_IDN_OAUTH2_TOKEN_BINDING_PK
BEGIN ATOMIC
-- Add ID column to IDN_OAUTH2_TOKEN_BINDING
IF NOT EXISTS(SELECT *
FROM SYSCAT.COLUMNS
WHERE TABNAME = 'IDN_OAUTH2_TOKEN_BINDING' AND COLNAME = 'ID')
    THEN
EXECUTE IMMEDIATE 'ALTER TABLE IDN_OAUTH2_TOKEN_BINDING ADD COLUMN ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY';
END
IF;

    -- Add primary key to IDN_OAUTH2_TOKEN_BINDING
    IF NOT EXISTS(SELECT *
FROM SYSCAT.TABCONST
WHERE TABNAME = 'IDN_OAUTH2_TOKEN_BINDING' AND TYPE = 'P')
    THEN
EXECUTE IMMEDIATE 'ALTER TABLE IDN_OAUTH2_TOKEN_BINDING ADD CONSTRAINT PK_TOKEN_BINDING PRIMARY KEY (ID)';
END
IF;
END
/

CALL ADD_IDN_OAUTH2_TOKEN_BINDING_PK
/

DROP PROCEDURE ADD_IDN_OAUTH2_TOKEN_BINDING_PK
/
