IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'IDN_OAUTH2_TOKEN_BINDING' AND COLUMN_NAME = 'ID')
BEGIN
    ALTER TABLE IDN_OAUTH2_TOKEN_BINDING ADD ID INTEGER NOT NULL IDENTITY(1,1)
    PRINT 'ID column added to IDN_OAUTH2_TOKEN_BINDING.'
END
ELSE
BEGIN
    PRINT 'ID column already exists on IDN_OAUTH2_TOKEN_BINDING. Skipping.'
END;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'PRIMARY KEY' AND TABLE_NAME = 'IDN_OAUTH2_TOKEN_BINDING')
BEGIN
    ALTER TABLE IDN_OAUTH2_TOKEN_BINDING ADD CONSTRAINT PK_TOKEN_BINDING PRIMARY KEY CLUSTERED (ID)
    PRINT 'Primary key PK_TOKEN_BINDING added to IDN_OAUTH2_TOKEN_BINDING.'
END
ELSE
BEGIN
    PRINT 'Primary key already exists on IDN_OAUTH2_TOKEN_BINDING. Skipping.'
END;
