DROP PROCEDURE IF EXISTS ADD_IDN_OAUTH2_TOKEN_BINDING_PK;

DELIMITER $$

CREATE PROCEDURE ADD_IDN_OAUTH2_TOKEN_BINDING_PK()
BEGIN
    -- Add ID column to IDN_OAUTH2_TOKEN_BINDING
    IF NOT EXISTS(SELECT *
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'IDN_OAUTH2_TOKEN_BINDING' AND COLUMN_NAME = 'ID' AND TABLE_SCHEMA = DATABASE()) THEN
    ALTER TABLE `IDN_OAUTH2_TOKEN_BINDING`
    ADD COLUMN `ID` INTEGER NOT NULL AUTO_INCREMENT,
    ADD PRIMARY KEY
    (`ID`);
ELSE
-- Add primary key if the column exists but PK does not
IF NOT EXISTS(SELECT *
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_NAME = 'IDN_OAUTH2_TOKEN_BINDING' AND CONSTRAINT_TYPE = 'PRIMARY KEY' AND TABLE_SCHEMA = DATABASE()) THEN
ALTER TABLE `IDN_OAUTH2_TOKEN_BINDING`
ADD PRIMARY KEY
(`ID`);
END
IF;
    END
IF;
END $$

DELIMITER ;

CALL ADD_IDN_OAUTH2_TOKEN_BINDING_PK
();
DROP PROCEDURE IF EXISTS ADD_IDN_OAUTH2_TOKEN_BINDING_PK;
