CREATE SEQUENCE IF NOT EXISTS IDN_OAUTH2_TOKEN_BINDING_PK_SEQ;

ALTER TABLE IDN_OAUTH2_TOKEN_BINDING ADD COLUMN IF NOT EXISTS ID INTEGER DEFAULT NEXTVAL('idn_oauth2_token_binding_pk_seq') NOT NULL;

ALTER TABLE IDN_OAUTH2_TOKEN_BINDING DROP CONSTRAINT IF EXISTS PK_TOKEN_BINDING;

ALTER TABLE IDN_OAUTH2_TOKEN_BINDING ADD CONSTRAINT PK_TOKEN_BINDING PRIMARY KEY (ID);
