IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[MIGRATION_STATUS]') AND TYPE IN (N'U'))
CREATE TABLE MIGRATION_STATUS (
    IS_VERSION VARCHAR(255) NOT NULL,
    STATUS VARCHAR(255),
    LOCKED_BY VARCHAR(255),
    LOCK_ACQUIRED_AT DATETIME2,
    EXPIRES_AT DATETIME2,
    PRIMARY KEY (IS_VERSION)
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[MIGRATOR_PROGRESS]') AND TYPE IN (N'U'))
CREATE TABLE MIGRATOR_PROGRESS (
    IS_VERSION VARCHAR(255) NOT NULL,
    STATUS VARCHAR(255),
    CURRENT_MIGRATOR VARCHAR(255),
    CURRENT_TENANT VARCHAR(255),
    LAST_COMPLETED_MIGRATOR VARCHAR(255),
    LAST_COMPLETED_TENANT VARCHAR(255),
    PRIMARY KEY (IS_VERSION)
);

IF NOT EXISTS (SELECT * FROM MIGRATION_STATUS WHERE IS_VERSION = '7.1.0')
BEGIN
    INSERT INTO MIGRATION_STATUS (IS_VERSION, LOCKED_BY, STATUS, LOCK_ACQUIRED_AT, EXPIRES_AT)
    VALUES ('7.1.0', NULL, 'NOT-STARTED', NULL, NULL)
END;

IF NOT EXISTS (SELECT * FROM MIGRATOR_PROGRESS WHERE IS_VERSION = '7.1.0')
BEGIN
    INSERT INTO MIGRATOR_PROGRESS (IS_VERSION, STATUS, CURRENT_MIGRATOR, CURRENT_TENANT, LAST_COMPLETED_MIGRATOR, LAST_COMPLETED_TENANT)
    VALUES ('7.1.0', 'NOT-STARTED', NULL, NULL, NULL, NULL)
END;
