CREATE TABLE IF NOT EXISTS MIGRATION_STATUS (
    IS_VERSION VARCHAR(255) NOT NULL,
    STATUS VARCHAR(255),
    LOCKED_BY VARCHAR(255),
    LOCK_ACQUIRED_AT TIMESTAMP,
    EXPIRES_AT TIMESTAMP,
    PRIMARY KEY (IS_VERSION)
);

CREATE TABLE IF NOT EXISTS MIGRATOR_PROGRESS (
    IS_VERSION VARCHAR(255) NOT NULL,
    STATUS VARCHAR(255),
    CURRENT_MIGRATOR VARCHAR(255),
    CURRENT_TENANT VARCHAR(255),
    LAST_COMPLETED_MIGRATOR VARCHAR(255),
    LAST_COMPLETED_TENANT VARCHAR(255),
    PRIMARY KEY (IS_VERSION)
);

INSERT INTO MIGRATION_STATUS(IS_VERSION, LOCKED_BY, STATUS, LOCK_ACQUIRED_AT, EXPIRES_AT)
VALUES ('7.1.0', NULL, 'NOT-STARTED', NULL, NULL)
ON CONFLICT DO NOTHING;

INSERT INTO MIGRATOR_PROGRESS(IS_VERSION, STATUS, CURRENT_MIGRATOR, CURRENT_TENANT, LAST_COMPLETED_MIGRATOR, LAST_COMPLETED_TENANT)
VALUES ('7.1.0', 'NOT-STARTED', NULL, NULL, NULL, NULL)
ON CONFLICT DO NOTHING;
