DROP SEQUENCE IF EXISTS UM_SHARED_USER_ROLE_PK_SEQ;
CREATE SEQUENCE UM_SHARED_USER_ROLE_PK_SEQ;
ALTER TABLE UM_SHARED_USER_ROLE ADD ID INTEGER DEFAULT NEXTVAL('UM_SHARED_USER_ROLE_PK_SEQ') PRIMARY KEY;
