/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.118
 * Generated at: 2026-08-21 09:29:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.wso2.carbon.base.ServerConfiguration;
import static org.wso2.carbon.identity.core.util.IdentityCoreConstants.PROXY_CONTEXT_PATH;
import static org.wso2.carbon.identity.core.util.IdentityUtil.getServerURL;
import static org.wso2.carbon.identity.core.util.IdentityTenantUtil.isTenantQualifiedUrlsEnabled;
import org.owasp.encoder.Encode;
import static org.wso2.carbon.identity.core.util.IdentityTenantUtil.isSuperTenantRequiredInUrl;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("org.wso2.carbon.base.ServerConfiguration");
    _jspx_imports_classes.add("static org.wso2.carbon.identity.core.util.IdentityCoreConstants.PROXY_CONTEXT_PATH");
    _jspx_imports_classes.add("static org.wso2.carbon.identity.core.util.IdentityUtil.getServerURL");
    _jspx_imports_classes.add("static org.wso2.carbon.identity.core.util.IdentityTenantUtil.isTenantQualifiedUrlsEnabled");
    _jspx_imports_classes.add("org.owasp.encoder.Encode");
    _jspx_imports_classes.add("static org.wso2.carbon.identity.core.util.IdentityTenantUtil.isSuperTenantRequiredInUrl");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--\n");
      out.write("~    Copyright (c) 2022-2025, WSO2 LLC. (https://www.wso2.com). All Rights Reserved.\n");
      out.write("~\n");
      out.write("~    This software is the property of WSO2 LLC. and its suppliers, if any.\n");
      out.write("~    Dissemination of any information or reproduction of any material contained\n");
      out.write("~    herein in any form is strictly forbidden, unless permitted by WSO2 expressly.\n");
      out.write("~    You may not alter or remove any copyright or other notice from copies of this content.\"\n");
      out.write("-->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    var userAccessedPath = window.location.href;\n");
      out.write("    sessionStorage.setItem(\"userAccessedPath\", userAccessedPath.split(window.origin)[1]);\n");
      out.write("</script>\n");
      out.write("\n");

    if(request.getParameter("code") != null && !request.getParameter("code").trim().isEmpty()) {request.getRequestDispatcher("/authenticate?code="+request.getParameter("code")+"&AuthenticatedIdPs="+request.getParameter("AuthenticatedIdPs")+"&session_state="+request.getParameter("session_state")).forward(request, response);}

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE HTML>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <!-- Start of loading application configurations -->\n");
      out.write("        <script type=\"text/javascript\" src=\"/console/update.config.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"/console/config.js\"></script>\n");
      out.write("        <!-- End of loading application configurations -->\n");
      out.write("\n");
      out.write("        <style>\n");
      out.write("            body {\n");
      out.write("                margin: 0;\n");
      out.write("                padding: 0;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            @keyframes alert-success {\n");
      out.write("                0% {\n");
      out.write("                    opacity: 1;\n");
      out.write("                }\n");
      out.write("                100% {\n");
      out.write("                    opacity: 0;\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .pre-loader-wrapper {\n");
      out.write("                background-color: #F5F6F6;\n");
      out.write("                min-height: 100vh;\n");
      out.write("                align-items: center;\n");
      out.write("                justify-content: center;\n");
      out.write("                display: flex;\n");
      out.write("                flex-direction: column;\n");
      out.write("                flex: 1;\n");
      out.write("                background-image: unset;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .pre-loader-logo {\n");
      out.write("                margin-top: -0.1rem;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .content-loader {\n");
      out.write("                display: flex;\n");
      out.write("                flex-direction: column;\n");
      out.write("                justify-content: center;\n");
      out.write("                align-items: center;\n");
      out.write("                user-select: none;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .content-loader .ui.loader {\n");
      out.write("                display: block;\n");
      out.write("                position: relative;\n");
      out.write("                margin-top: 10px;\n");
      out.write("                margin-bottom: 25px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            @keyframes loader {\n");
      out.write("                0% {\n");
      out.write("                    transform: rotate(0)\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                to {\n");
      out.write("                    transform: rotate(1turn)\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .content-loader .ui.loader:before {\n");
      out.write("                content: \"\";\n");
      out.write("                display: block;\n");
      out.write("                height: 26px;\n");
      out.write("                width: 26px;\n");
      out.write("                border: .2em solid rgba(0,0,0,.1);\n");
      out.write("                border-radius: 500rem;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .content-loader .ui.loader:after {\n");
      out.write("                content: \"\";\n");
      out.write("                position: absolute;\n");
      out.write("                height: 26px;\n");
      out.write("                width: 26px;\n");
      out.write("                border-color: #767676 transparent transparent !important;\n");
      out.write("                border: .2em solid transparent;\n");
      out.write("                animation: loader .6s linear;\n");
      out.write("                animation-iteration-count: infinite;\n");
      out.write("                border-radius: 500rem;\n");
      out.write("                box-shadow: 0 0 0 1px transparent;\n");
      out.write("                top: 0;\n");
      out.write("                left: 0;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .trifacta-pre-loader  {\n");
      out.write("                margin-top: -0.1rem;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .trifacta-pre-loader svg #_1 {\n");
      out.write("                animation-name: alert-success;\n");
      out.write("                animation-duration: 3s;\n");
      out.write("                position: relative;\n");
      out.write("                animation-delay: 0s;\n");
      out.write("                animation-iteration-count: infinite;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .trifacta-pre-loader svg #_2 {\n");
      out.write("                animation-name: alert-success;\n");
      out.write("                animation-duration: 3s;\n");
      out.write("                position: relative;\n");
      out.write("                animation-delay: 1s;\n");
      out.write("                animation-iteration-count: infinite;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .trifacta-pre-loader svg #_3 {\n");
      out.write("                animation-name: alert-success;\n");
      out.write("                animation-duration: 3s;\n");
      out.write("                position: relative;\n");
      out.write("                animation-delay: 2s;\n");
      out.write("                animation-iteration-count: infinite;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("        <script\n");
      out.write("            src=\"/console/startup-config.js\"\n");
      out.write("        ></script>\n");
      out.write("\n");
      out.write("        <!-- Start of custom stylesheets -->\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"/console/extensions/stylesheet.css\"/>\n");
      out.write("        <!-- End of custom stylesheets -->\n");
      out.write("\n");
      out.write("        <!-- Start of custom scripts added to the head -->\n");
      out.write("        <script\n");
      out.write("            id=\"head-script\"\n");
      out.write("            type=\"text/javascript\"\n");
      out.write("            src=\"/console/extensions/head-script.js\"\n");
      out.write("            data-page-id=\"preauth\"\n");
      out.write("        ></script>\n");
      out.write("        <!-- End of custom scripts added to the head -->\n");
      out.write("    </head>\n");
      out.write("    <script>\n");
      out.write("\n");
      out.write("        var proxyContextPathGlobal = \"");
      out.print(ServerConfiguration.getInstance().getFirstProperty(PROXY_CONTEXT_PATH));
      out.write("\";\n");
      out.write("        var proxyContextPathConsole = window.__WSO2_IS_RUNTIME_CONFIG__ ? window.__WSO2_IS_RUNTIME_CONFIG__.server.proxyContextPath : null;\n");
      out.write("        if (proxyContextPathConsole) {\n");
      out.write("            proxyContextPathGlobal = proxyContextPathConsole;\n");
      out.write("        }\n");
      out.write("        var isSuperTenantRequiredInUrl = \"");
      out.print(isSuperTenantRequiredInUrl());
      out.write("\";\n");
      out.write("        var userAccessedPath = window.location.href;\n");
      out.write("        var applicationDomain = window.location.origin;\n");
      out.write("\n");
      out.write("        var userTenant = userAccessedPath.split(\"/\" + startupConfig.tenantPrefix + \"/\")[1] ?  userAccessedPath.split(\"/\" + startupConfig.tenantPrefix + \"/\")[1].split(\"/\")[0] : null;\n");
      out.write("        userTenant = userTenant ?  userTenant.split(\"?\")[0] : null;\n");
      out.write("        var utype =  userAccessedPath.split(\"utype=\")[1] ?  userAccessedPath.split(\"utype=\")[1] : null;\n");
      out.write("\n");
      out.write("        var serverOrigin = \"");
      out.print(getServerURL("", true, true));
      out.write("\";\n");
      out.write("        var authorizationCode = \"");
      out.print(Encode.forHtml(request.getParameter("code")));
      out.write("\" != \"null\"\n");
      out.write("            ? \"");
      out.print(Encode.forHtml(request.getParameter("code")));
      out.write("\"\n");
      out.write("            : null;\n");
      out.write("        var authSessionState = \"");
      out.print(Encode.forHtml(request.getParameter("session_state")));
      out.write("\" != \"null\"\n");
      out.write("            ? \"");
      out.print(Encode.forHtml(request.getParameter("session_state")));
      out.write("\"\n");
      out.write("            : null;\n");
      out.write("        var authIdPs = \"");
      out.print(Encode.forHtml(request.getParameter("AuthenticatedIdPs")));
      out.write("\" != \"null\"\n");
      out.write("            ? \"");
      out.print(Encode.forHtml(request.getParameter("AuthenticatedIdPs")));
      out.write("\"\n");
      out.write("            : null;\n");
      out.write("\n");
      out.write("        function authenticateWithSDK() {\n");
      out.write("\n");
      out.write("            if(!authorizationCode) {\n");
      out.write("                function getTenantName() {\n");
      out.write("                    var path = window.location.pathname;\n");
      out.write("                    var pathChunks = path.split(\"/\");\n");
      out.write("                    var tenantPrefixIndex = pathChunks.indexOf(startupConfig.tenantPrefix);\n");
      out.write("                    if (tenantPrefixIndex !== -1) {\n");
      out.write("                        return pathChunks[ tenantPrefixIndex + 1 ];\n");
      out.write("                    }\n");
      out.write("                    return \"\";\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                function getTenantPath(tenantDomain) {\n");
      out.write("                    var _tenantDomain = tenantDomain ? tenantDomain : getTenantName();\n");
      out.write("\n");
      out.write("                    if (!_tenantDomain && isSuperTenantRequiredInUrl === \"true\") {\n");
      out.write("                        if (startupConfig.superTenantProxy) {\n");
      out.write("                            _tenantDomain = startupConfig.superTenantProxy;\n");
      out.write("                        } else {\n");
      out.write("                            _tenantDomain = startupConfig.superTenant;\n");
      out.write("                        }\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                    return _tenantDomain !== \"\"\n");
      out.write("                        ? \"/\" + startupConfig.tenantPrefix + \"/\" + _tenantDomain\n");
      out.write("                        : \"\";\n");
      out.write("                };\n");
      out.write("\n");
      out.write("                function getApiPath(path) {\n");
      out.write("                    var tenantDomain = getTenantName();\n");
      out.write("\n");
      out.write("                    if (!tenantDomain) {\n");
      out.write("                        if (startupConfig.superTenantProxy) {\n");
      out.write("                            tenantDomain = startupConfig.superTenantProxy;\n");
      out.write("                        } else {\n");
      out.write("                            tenantDomain = startupConfig.superTenant;\n");
      out.write("                        }\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                    if (path) {\n");
      out.write("                        return serverOrigin + getTenantPath(tenantDomain) + path;\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                    return serverOrigin + getTenantPath(tenantDomain);\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                /**\n");
      out.write("                 * Get the organization name.\n");
      out.write("                 *\n");
      out.write("                 * @returns {string}\n");
      out.write("                 */\n");
      out.write("                function getOrganizationName() {\n");
      out.write("                    var path = window.location.pathname;\n");
      out.write("                    var pathChunks = path.split(\"/\");\n");
      out.write("\n");
      out.write("                    var orgPrefixIndex = pathChunks.indexOf(startupConfig.orgPrefix);\n");
      out.write("\n");
      out.write("                    if (orgPrefixIndex !== -1) {\n");
      out.write("                        return pathChunks[ orgPrefixIndex + 1 ];\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                    return \"\";\n");
      out.write("                };\n");
      out.write("\n");
      out.write("                /**\n");
      out.write("                 * Get the organization path.\n");
      out.write("                 *\n");
      out.write("                 * @returns {string}\n");
      out.write("                 */\n");
      out.write("                function getOrganizationPath() {\n");
      out.write("                    return getOrganizationName() !== \"\"\n");
      out.write("                        ? \"/\" + startupConfig.orgPrefix + \"/\" + getOrganizationName()\n");
      out.write("                        : \"\";\n");
      out.write("                };\n");
      out.write("\n");
      out.write("                 /**\n");
      out.write("                 * Check if the current tenant is super tenant.\n");
      out.write("                 *\n");
      out.write("                 * @returns {boolean}\n");
      out.write("                 */\n");
      out.write("                function isSuperTenant() {\n");
      out.write("                    const tenantName = getTenantName();\n");
      out.write("                    let superTenant;\n");
      out.write("\n");
      out.write("                    if (startupConfig.superTenantProxy) {\n");
      out.write("                        superTenant = startupConfig.superTenantProxy;\n");
      out.write("                    } else {\n");
      out.write("                        superTenant = startupConfig.superTenant;\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                    return tenantName === \"\" || tenantName === superTenant;\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                /**\n");
      out.write("                 * Get the tenant qualified client id.\n");
      out.write("                 *\n");
      out.write("                 * @returns {string}\n");
      out.write("                 */\n");
      out.write("                function resolveClientId() {\n");
      out.write("                    var enableTenantQualifiedUrls = ");
      out.print(isTenantQualifiedUrlsEnabled());
      out.write(";\n");
      out.write("                    var defaultClientId = \"CONSOLE\";\n");
      out.write("\n");
      out.write("                    if (enableTenantQualifiedUrls === true || isSuperTenant()) {\n");
      out.write("                        return defaultClientId;\n");
      out.write("                    } else {\n");
      out.write("                        return defaultClientId + \"_\" + getTenantName();\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                /**\n");
      out.write("                 * Construct the sign-in redirect URL.\n");
      out.write("                 *\n");
      out.write("                 * @returns {string} Contructed URL.\n");
      out.write("                 */\n");
      out.write("                function signInRedirectURL() {\n");
      out.write("                    // When there's no proxy context path, the IS server returns \"null\".\n");
      out.write("                    var contextPath = (!proxyContextPathGlobal || proxyContextPathGlobal === \"null\") ? \"\" : \"/\" + proxyContextPathGlobal;\n");
      out.write("\n");
      out.write("                    if (getTenantName() === startupConfig.superTenant && isSuperTenantRequiredInUrl !== \"true\") {\n");
      out.write("                        return applicationDomain.replace(/\\/+$/, '') + contextPath\n");
      out.write("                            + \"/console\";\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                    return applicationDomain.replace(/\\/+$/, '') + contextPath + getTenantPath()\n");
      out.write("                        + \"/console\";\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                /**\n");
      out.write("                 * Construct the sign-out redirect URL.\n");
      out.write("                 *\n");
      out.write("                 * @returns {string} Constructed URL.\n");
      out.write("                 */\n");
      out.write("                function getSignOutRedirectURL() {\n");
      out.write("                    if (getTenantName() === startupConfig.superTenant && isSuperTenantRequiredInUrl !== \"true\") {\n");
      out.write("                        return applicationDomain.replace(/\\/+$/, '');\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                    return applicationDomain.replace(/\\/+$/, '') + getTenantPath();\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                /**\n");
      out.write("                 * Construct the auth params for organization login `authorize` requets.\n");
      out.write("                 *\n");
      out.write("                 * @remarks This only applies to the new authz runtime.\n");
      out.write("                 *\n");
      out.write("                 * @returns {string} Contructed auth params.\n");
      out.write("                 */\n");
      out.write("                function getAuthParamsForOrganizationLogins(orginalParams) {\n");
      out.write("                    var authParams = Object.assign({}, orginalParams);\n");
      out.write("\n");
      out.write("                    if (getOrganizationPath()) {\n");
      out.write("                        var initialUserOrgInLocalStorage = localStorage.getItem(\"user-org\");\n");
      out.write("                        var orgIdInLocalStorage = localStorage.getItem(\"org-id\");\n");
      out.write("\n");
      out.write("                        if (orgIdInLocalStorage) {\n");
      out.write("                            if (orgIdInLocalStorage === getOrganizationName() && initialUserOrgInLocalStorage !== \"undefined\") {\n");
      out.write("                                authParams[\"fidp\"] = \"OrganizationSSO\";\n");
      out.write("                                authParams[\"orgId\"] = getOrganizationName();\n");
      out.write("                            }\n");
      out.write("                        } else {\n");
      out.write("                            authParams[\"fidp\"] = \"OrganizationSSO\";\n");
      out.write("                            authParams[\"orgId\"] = getOrganizationName();\n");
      out.write("                        }\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                    return authParams;\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                /**\n");
      out.write("                 * Retrieves the super tenant.\n");
      out.write("                 * If a super tenant proxy is defined in the startup configuration, it is returned;\n");
      out.write("                 * otherwise, the super tenant directly from the startup configuration is returned.\n");
      out.write("                 *\n");
      out.write("                 * @returns {string} The super tenant.\n");
      out.write("                 */\n");
      out.write("                function getSuperTenant() {\n");
      out.write("                    if (startupConfig.superTenantProxy) {\n");
      out.write("                        return startupConfig.superTenantProxy;\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                    startupConfig.superTenant;\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                var auth = AsgardeoAuth.AsgardeoSPAClient.getInstance();\n");
      out.write("\n");
      out.write("                var authConfig = {\n");
      out.write("                    signInRedirectURL: signInRedirectURL(),\n");
      out.write("                    signOutRedirectURL: getSignOutRedirectURL(),\n");
      out.write("                    clientID: resolveClientId(),\n");
      out.write("                    baseUrl: getApiPath(),\n");
      out.write("                    responseMode: \"form_post\",\n");
      out.write("                    scope: [\"openid SYSTEM profile\"],\n");
      out.write("                    storage: \"webWorker\",\n");
      out.write("                    endpoints: {\n");
      out.write("                        authorizationEndpoint: getApiPath(\"/oauth2/authorize\"),\n");
      out.write("                        clockTolerance: 300,\n");
      out.write("                        jwksEndpointURL: undefined,\n");
      out.write("                        logoutEndpointURL: getApiPath(\"/oidc/logout\"),\n");
      out.write("                        oidcSessionIFrameEndpointURL: getApiPath(\"/oidc/checksession\"),\n");
      out.write("                        tokenEndpointURL: undefined,\n");
      out.write("                        tokenRevocationEndpointURL: undefined\n");
      out.write("                    },\n");
      out.write("                    enablePKCE: true\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                var isSilentSignInDisabled = userAccessedPath.includes(\"disable_silent_sign_in\");\n");
      out.write("                var isTenantSwitchPath = userAccessedPath.includes(\"switch_tenant\");\n");
      out.write("                var promptParam = new URL(location.href).searchParams.get(\"prompt\");\n");
      out.write("\n");
      out.write("                // Redirect user to the login page if the prompt parameter is set to login.\n");
      out.write("                if (promptParam && promptParam === 'login') {\n");
      out.write("                    auth.initialize(authConfig);\n");
      out.write("                    auth.signIn(getAuthParamsForOrganizationLogins({ prompt: \"login\" }));\n");
      out.write("\n");
      out.write("                    return;\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                if(isSilentSignInDisabled) {\n");
      out.write("\n");
      out.write("                    if(isTenantSwitchPath) {\n");
      out.write("                        auth.initialize(authConfig);\n");
      out.write("                        auth.signIn();\n");
      out.write("                    } else {\n");
      out.write("                        window.location = applicationDomain+'/authenticate?disable_silent_sign_in=true&invite_user=true';\n");
      out.write("                    }\n");
      out.write("                } else {\n");
      out.write("                    auth.initialize(authConfig);\n");
      out.write("\n");
      out.write("                    if (window.top === window.self) {\n");
      out.write("                        var authCallbackUrl = window.location.pathname + window.location.hash;\n");
      out.write("\n");
      out.write("                        sessionStorage.setItem(\"auth_callback_url_console\", authCallbackUrl);\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                    auth.signIn(getAuthParamsForOrganizationLogins({}));\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("    <script>\n");
      out.write("        if(!authorizationCode) {\n");
      out.write("            var authSPAJS = document.createElement(\"script\");\n");
      out.write("            var authScriptSrc = \"/console/auth-spa-3.1.2.min.js\";\n");
      out.write("\n");
      out.write("            authSPAJS.setAttribute(\"src\", authScriptSrc);\n");
      out.write("            authSPAJS.setAttribute(\"async\", \"false\");\n");
      out.write("\n");
      out.write("            var head = document.head;\n");
      out.write("            head.insertBefore(authSPAJS, head.firstElementChild);\n");
      out.write("\n");
      out.write("            authSPAJS.addEventListener(\"load\", authenticateWithSDK, false);\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("    <body>\n");
      out.write("        <div class=\"pre-loader-wrapper\" data-testid=\"preauth-pre-loader-wrapper\">\n");
      out.write("            <div class=\"content-loader\" id=\"loader\">\n");
      out.write("                <div class=\"ui dimmer\">\n");
      out.write("                    <div class=\"ui loader\"></div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Start of custom scripts added to the body -->\n");
      out.write("        <script type=\"text/javascript\" src=\"/console/extensions/body-script.js\"></script>\n");
      out.write("        <!-- End of custom scripts added to the body -->\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
