CREATE INDEX REG_LOG_IND_BY_P1
    ON REG_LOG(REG_LOGGED_TIME, REG_TENANT_ID)/

CREATE INDEX REG_RESOURCE_IND_3
    ON REG_RESOURCE(REG_UUID)/

CREATE INDEX REG_RESOURCE_IND_4
    ON REG_RESOURCE(REG_TENANT_ID, REG_UUID)/

CREATE INDEX REG_RESOURCE_IND_5
    ON REG_RESOURCE(REG_TENANT_ID, REG_MEDIA_TYPE)/
