CREATE INDEX REG_LOG_IND_BY_REG_LOGTIME USING HASH ON REG_LOG (REG_LOGGED_TIME, REG_TENANT_ID);
CREATE INDEX REG_RESOURCE_IND_BY_UUID USING HASH ON REG_RESOURCE (REG_UUID);
CREATE INDEX REG_RESOURCE_IND_BY_TENANT USING HASH ON REG_RESOURCE (REG_TENANT_ID, REG_UUID);
CREATE INDEX REG_RESOURCE_IND_BY_TYPE USING HASH ON REG_RESOURCE (REG_TENANT_ID, REG_MEDIA_TYPE);
