INSERT INTO IDN_CONFIG_TYPE (ID, NAME, DESCRIPTION)
SELECT temp.ID, temp.NAME, temp.DESCRIPTION
FROM (
    VALUES
        ('8469a176-3e6c-438a-ba01-71e9077072fa', 'APPLICATION_BRANDING_PREFERENCES', 'A resource type to keep the application branding preferences'),
        ('f4e83b8a-d1c4-a0d6-03a7-d48e268c60c5', 'PK_JWT_CONFIGURATION', 'A resource type to keep the tenant private key jwt configuration.'),
        ('9ec61e9d-f0e6-4952-9a09-ab842aeb2db2', 'ATTRIBUTE_CONFIGURATION', 'A resource type to store attribute related configurations.'),
        ('132b0ee6-43e0-462d-8b4b-15b68109d71d', 'ORGANIZATION_CONFIGURATION', 'A resource type to keep the organization configurations.'),
        ('1fc809a0-dc0d-4cb2-82f3-58934d389236', 'CUSTOM_TEXT', 'A resource type to keep the tenant custom text preferences.'),
        ('3e5b1f91-72d8-4fbc-94d1-1b9a4f8c3b07', 'IMPERSONATION_CONFIGURATION', 'A resource type to keep the tenant impersonation preferences.')
    ) AS temp (ID, NAME, DESCRIPTION)
WHERE NOT EXISTS (SELECT 1 FROM IDN_CONFIG_TYPE ict WHERE ict.ID = temp.ID OR ict.NAME = temp.NAME);

ALTER TABLE IF EXISTS IDN_OIDC_JTI ADD COLUMN IF NOT EXISTS TENANT_ID INTEGER NOT NULL DEFAULT -1;

ALTER TABLE IF EXISTS IDN_OIDC_JTI DROP PRIMARY KEY;

ALTER TABLE IF EXISTS IDN_OIDC_JTI ADD PRIMARY KEY (JWT_ID, TENANT_ID);

INSERT INTO IDN_SECRET_TYPE (ID, NAME, DESCRIPTION)
SELECT temp.ID, temp.NAME, temp.DESCRIPTION
FROM(
    VALUES
        ('c508ca28-60c0-4493-a758-77e4173ffdb9', 'IDP_SECRET_PROPERTIES', 'Secret type to uniquely identify secrets relevant to identity providers'),
        ('29d0c37d-139a-4b1e-a343-7b8d26f0a2a9', 'ANDROID_ATTESTATION_CREDENTIALS', 'Secret type to uniquely identify secrets relevant to android client attestation credentials'),
        ('433df096-62b7-4a36-b3eb-1bed9150ed35', 'IDVP_SECRET_PROPERTIES', 'Secret type to uniquely identify secrets relevant to identity verification providers')
    ) AS temp (ID, NAME, DESCRIPTION)
WHERE NOT EXISTS (SELECT 1 FROM IDN_SECRET_TYPE ist WHERE ist.ID = temp.ID OR ist.NAME = temp.NAME);

ALTER TABLE IF EXISTS IDN_SECRET ADD COLUMN IF NOT EXISTS KEY_ID VARCHAR(255) NULL;

ALTER TABLE IF EXISTS IDN_SECRET ALTER COLUMN IF EXISTS SECRET_NAME VARCHAR(1023) NOT NULL;

CREATE INDEX IF NOT EXISTS IDN_SECRET_TYPE_ID ON IDN_SECRET (TYPE_ID);

ALTER TABLE IF EXISTS IDN_OAUTH2_AUTHZ_CODE_SCOPE ALTER COLUMN IF EXISTS SCOPE VARCHAR(255);

ALTER TABLE IF EXISTS IDN_OAUTH2_ACCESS_TOKEN_SCOPE ALTER COLUMN IF EXISTS TOKEN_SCOPE VARCHAR(255);

ALTER TABLE IF EXISTS IDN_FED_AUTH_SESSION_MAPPING ADD COLUMN IF NOT EXISTS IDP_ID INTEGER NOT NULL DEFAULT 1;

ALTER TABLE IF EXISTS IDN_FED_AUTH_SESSION_MAPPING ADD CONSTRAINT IF NOT EXISTS IDP_ID_CONSTRAINT FOREIGN KEY (IDP_ID) REFERENCES IDP(ID) ON DELETE CASCADE;

CREATE ALIAS IF NOT EXISTS DROP_UNIQUE_CONSTRAINT AS $$ void executeSql(Connection conn, String sql) throws SQLException { conn.createStatement().executeUpdate(sql); } $$;

call DROP_UNIQUE_CONSTRAINT('ALTER TABLE IDN_FED_AUTH_SESSION_MAPPING DROP CONSTRAINT ' || (SELECT A.CONSTRAINT_NAME FROM (SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE WHERE TABLE_NAME = 'IDN_FED_AUTH_SESSION_MAPPING' AND COLUMN_NAME = 'IDP_SESSION_ID') A INNER JOIN (SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE WHERE TABLE_NAME = 'IDN_FED_AUTH_SESSION_MAPPING' AND COLUMN_NAME = 'IDP_SESSION_ID') B ON A.CONSTRAINT_NAME = B.CONSTRAINT_NAME));

DROP ALIAS IF EXISTS DROP_UNIQUE_CONSTRAINT;

ALTER TABLE IF EXISTS IDN_FED_AUTH_SESSION_MAPPING ADD UNIQUE (IDP_SESSION_ID, TENANT_ID, IDP_ID);

CREATE TABLE IF NOT EXISTS IDP_GROUP (
	ID INTEGER AUTO_INCREMENT NOT NULL,
	IDP_ID INTEGER NOT NULL,
	TENANT_ID INTEGER NOT NULL,
	GROUP_NAME VARCHAR(255) NOT NULL,
	UUID CHAR(36) NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE (IDP_ID, GROUP_NAME),
	UNIQUE (UUID),
	FOREIGN KEY (IDP_ID) REFERENCES IDP(ID) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS IDVP (
	ID          INTEGER NOT NULL AUTO_INCREMENT,
	UUID        CHAR(36) NOT NULL,
	TENANT_ID   INTEGER NOT NULL,
	IDVP_TYPE   VARCHAR(254),
	NAME        VARCHAR(254),
	DESCRIPTION VARCHAR(1024),
	IS_ENABLED  CHAR(1) NOT NULL DEFAULT '0',
	PRIMARY KEY (ID),
	UNIQUE (TENANT_ID, NAME),
    UNIQUE (UUID)
);

CREATE TABLE IF NOT EXISTS IDVP_CLAIM_MAPPING (
    ID            INTEGER NOT NULL AUTO_INCREMENT,
    IDVP_ID       INTEGER NOT NULL,
    TENANT_ID     INTEGER NOT NULL,
    CLAIM         VARCHAR(254),
    LOCAL_CLAIM   VARCHAR(254),
    PRIMARY KEY (ID),
    UNIQUE (IDVP_ID, CLAIM, TENANT_ID),
    FOREIGN KEY (IDVP_ID) REFERENCES IDVP(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS IDVP_CONFIG (
	ID              INTEGER NOT NULL AUTO_INCREMENT,
	IDVP_ID         INTEGER NOT NULL,
	TENANT_ID       INTEGER NOT NULL,
	PROPERTY_KEY    VARCHAR(254) NOT NULL,
  	PROPERTY_VALUE  VARCHAR(1024),
  	IS_SECRET       CHAR (1) DEFAULT '0',
	PRIMARY KEY (ID),
	UNIQUE (IDVP_ID, PROPERTY_KEY, TENANT_ID),
	FOREIGN KEY (IDVP_ID) REFERENCES IDVP(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS IDV_CLAIM (
	ID          INTEGER NOT NULL AUTO_INCREMENT,
	UUID        CHAR(36) NOT NULL,
	USER_ID     VARCHAR(254) NOT NULL,
	CLAIM_URI   VARCHAR(254),
	IDVP_ID     CHAR(36) NOT NULL,
	TENANT_ID   INTEGER NOT NULL,
	IS_VERIFIED CHAR(1) NOT NULL DEFAULT '0',
	METADATA    BLOB,
	PRIMARY KEY (ID),
	UNIQUE (CLAIM_URI, TENANT_ID, USER_ID, IDVP_ID),
    UNIQUE (UUID),
    FOREIGN KEY (IDVP_ID) REFERENCES IDVP(UUID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_TBR_TS ON IDN_OAUTH2_ACCESS_TOKEN(TOKEN_BINDING_REF, TOKEN_STATE);

CREATE INDEX IF NOT EXISTS IDX_CLAIM_TI_CU ON IDN_CLAIM (TENANT_ID, CLAIM_URI);

CREATE INDEX IF NOT EXISTS IDX_AUTH_PROP_AUTH_ID ON IDP_AUTHENTICATOR_PROPERTY (AUTHENTICATOR_ID);

CREATE INDEX IF NOT EXISTS IDX_CON_FILE_RES_ID ON IDN_CONFIG_FILE (RESOURCE_ID);

CREATE TABLE IF NOT EXISTS IDN_RECOVERY_FLOW_DATA (
  RECOVERY_FLOW_ID VARCHAR(255) NOT NULL,
  CODE VARCHAR(255),
  FAILED_ATTEMPTS INTEGER DEFAULT 0 NOT NULL,
  RESEND_COUNT INTEGER DEFAULT 0 NOT NULL,
  TIME_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(RECOVERY_FLOW_ID)
);

ALTER TABLE IF EXISTS IDN_RECOVERY_DATA ADD COLUMN IF NOT EXISTS RECOVERY_FLOW_ID VARCHAR(255);

ALTER TABLE IF EXISTS IDN_RECOVERY_DATA ADD FOREIGN KEY (RECOVERY_FLOW_ID) REFERENCES IDN_RECOVERY_FLOW_DATA(RECOVERY_FLOW_ID) ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS API_RESOURCE (
    ID CHAR(36) NOT NULL PRIMARY KEY,
    CURSOR_KEY INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    IDENTIFIER VARCHAR(255) NOT NULL,
    TENANT_ID INT,
    DESCRIPTION VARCHAR(255),
    TYPE VARCHAR(255) NOT NULL,
    REQUIRES_AUTHORIZATION BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS API_RESOURCE_PROPERTY (
    ID INTEGER AUTO_INCREMENT,
    API_ID CHAR(36) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    `VALUE` VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT API_RESOURCE_PROPERTY_CONSTRAINT UNIQUE (API_ID, NAME),
    FOREIGN KEY (API_ID) REFERENCES API_RESOURCE(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SCOPE (
    ID CHAR(36) NOT NULL PRIMARY KEY,
    CURSOR_KEY INTEGER NOT NULL AUTO_INCREMENT,
    API_ID CHAR(36) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(255) NOT NULL,
    TENANT_ID INT,
    DESCRIPTION VARCHAR(300),
    FOREIGN KEY (API_ID) REFERENCES API_RESOURCE(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS API_ID_NAME_INDEX ON SCOPE (API_ID, NAME);

CREATE TABLE IF NOT EXISTS AUTHORIZED_API(
    APP_ID CHAR(36) NOT NULL,
    API_ID CHAR(36) NOT NULL,
    POLICY_ID VARCHAR(255) NOT NULL,
    CONSTRAINT PK_APP_API PRIMARY KEY (APP_ID, API_ID),
    FOREIGN KEY (API_ID) REFERENCES API_RESOURCE(ID) ON DELETE CASCADE,
    FOREIGN KEY (APP_ID) REFERENCES SP_APP(UUID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS AUTHORIZED_SCOPE(
    APP_ID CHAR(36) NOT NULL,
    API_ID CHAR(36) NOT NULL,
    SCOPE_ID CHAR(36) NOT NULL,
    CONSTRAINT PK_APP_API_SCOPE PRIMARY KEY (APP_ID, API_ID, SCOPE_ID),
    FOREIGN KEY (API_ID) REFERENCES API_RESOURCE(ID),
    FOREIGN KEY (SCOPE_ID) REFERENCES SCOPE(ID) ON DELETE CASCADE,
    FOREIGN KEY (APP_ID) REFERENCES SP_APP(UUID),
    FOREIGN KEY (APP_ID, API_ID) REFERENCES AUTHORIZED_API(APP_ID, API_ID) ON DELETE CASCADE,
    CONSTRAINT AUTHORIZED_SCOPE_UNIQUE UNIQUE (APP_ID, SCOPE_ID)
);

CREATE TABLE IF NOT EXISTS IDN_OAUTH_PAR (
    REQ_URI_REF VARCHAR(255) PRIMARY KEY,
    CLIENT_ID VARCHAR(255) NOT NULL,
    SCHEDULED_EXPIRY BIGINT NOT NULL,
    PARAMETERS MEDIUMTEXT
);

ALTER TABLE IF EXISTS IDN_OAUTH2_DEVICE_FLOW ADD COLUMN IF NOT EXISTS SUBJECT_IDENTIFIER VARCHAR(255);

CREATE TABLE IF NOT EXISTS IDN_ORG_USER_INVITATION (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    INVITATION_ID VARCHAR(40) NOT NULL,
    CONFIRMATION_CODE VARCHAR(40) NOT NULL,
    USER_NAME VARCHAR(254) NOT NULL,
    DOMAIN_NAME VARCHAR(254) NOT NULL,
    EMAIL VARCHAR(254) NOT NULL,
    USER_ORG_ID VARCHAR(254) NOT NULL,
    INVITED_ORG_ID VARCHAR(254) NOT NULL,
    USER_REDIRECT_URL VARCHAR(1024) NOT NULL,
    STATUS VARCHAR(10) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    EXPIRED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (INVITATION_ID)
);

CREATE TABLE IF NOT EXISTS IDN_ORG_USER_INVITE_ASSIGNMENT(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    INVITATION_ID VARCHAR(40) NOT NULL,
    ASSIGNMENT_ID VARCHAR(255) NOT NULL,
    ASSIGNMENT_TYPE VARCHAR(255) NOT NULL,
    PRIMARY KEY (INVITATION_ID, ASSIGNMENT_ID, ASSIGNMENT_TYPE),
    FOREIGN KEY (INVITATION_ID) REFERENCES IDN_ORG_USER_INVITATION(INVITATION_ID) ON DELETE CASCADE
);

ALTER TABLE IF EXISTS IDN_SCIM_GROUP ADD COLUMN IF NOT EXISTS AUDIENCE_REF_ID INTEGER DEFAULT -1 NOT NULL;

CREATE ALIAS IF NOT EXISTS DROP_IDN_SCIM_GROUP_UNIQUE_CONSTRAINT AS $$ void executeSql(Connection conn, String sql) throws SQLException { conn.createStatement().executeUpdate(sql); } $$;

call DROP_IDN_SCIM_GROUP_UNIQUE_CONSTRAINT('ALTER TABLE IDN_SCIM_GROUP DROP CONSTRAINT ' || (SELECT A.CONSTRAINT_NAME FROM (SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE WHERE TABLE_NAME = 'IDN_SCIM_GROUP' AND COLUMN_NAME = 'ROLE_NAME') A INNER JOIN (SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE WHERE TABLE_NAME = 'IDN_SCIM_GROUP' AND COLUMN_NAME = 'ROLE_NAME') B ON A.CONSTRAINT_NAME = B.CONSTRAINT_NAME));

DROP ALIAS IF EXISTS DROP_IDN_SCIM_GROUP_UNIQUE_CONSTRAINT;

ALTER TABLE IF EXISTS IDN_SCIM_GROUP ADD UNIQUE (TENANT_ID, ROLE_NAME, ATTR_NAME, AUDIENCE_REF_ID);

CREATE TABLE IF NOT EXISTS APP_ROLE_ASSOCIATION (
    APP_ID CHAR(36) NOT NULL,
    ROLE_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY (APP_ID, ROLE_ID),
    FOREIGN KEY (APP_ID) REFERENCES SP_APP(UUID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ROLE_SCOPE (
    ROLE_ID VARCHAR(255) NOT NULL,
    SCOPE_ID CHAR(36) NOT NULL,
    PRIMARY KEY (ROLE_ID, SCOPE_ID),
    FOREIGN KEY (SCOPE_ID) REFERENCES SCOPE(ID) ON DELETE CASCADE
);

ALTER TABLE IF EXISTS IDN_OAUTH2_ACCESS_TOKEN ADD COLUMN IF NOT EXISTS AUTHORIZED_ORGANIZATION varchar(36) NOT NULL DEFAULT('NONE');
ALTER TABLE IF EXISTS IDN_OAUTH2_ACCESS_TOKEN DROP CONSTRAINT CON_APP_KEY;
ALTER TABLE IF EXISTS IDN_OAUTH2_ACCESS_TOKEN ADD CONSTRAINT CON_APP_KEY UNIQUE (CONSUMER_KEY_ID,AUTHZ_USER,TENANT_ID,USER_DOMAIN,USER_TYPE,TOKEN_SCOPE_HASH,TOKEN_STATE,TOKEN_STATE_ID,IDP_ID,TOKEN_BINDING_REF,AUTHORIZED_ORGANIZATION);

ALTER TABLE IF EXISTS FIDO2_DEVICE_STORE DROP PRIMARY KEY;
ALTER TABLE IF EXISTS FIDO2_DEVICE_STORE ADD PRIMARY KEY(CREDENTIAL_ID, USER_HANDLE);

ALTER TABLE IF EXISTS SP_SHARED_APP ADD COLUMN IF NOT EXISTS SHARE_WITH_ALL_CHILDREN BOOLEAN DEFAULT FALSE;
