INSERT INTO IDN_CONFIG_TYPE (ID, NAME, DESCRIPTION)
SELECT '8469a176-3e6c-438a-ba01-71e9077072fa', 'APPLICATION_BRANDING_PREFERENCES', 'A resource type to keep the application branding preferences' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM IDN_CONFIG_TYPE WHERE ID = '8469a176-3e6c-438a-ba01-71e9077072fa')
/
INSERT INTO IDN_CONFIG_TYPE (ID, NAME, DESCRIPTION)
SELECT 'f4e83b8a-d1c4-a0d6-03a7-d48e268c60c5', 'PK_JWT_CONFIGURATION', 'A resource type to keep the tenant private key jwt configuration.' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM IDN_CONFIG_TYPE WHERE ID = 'f4e83b8a-d1c4-a0d6-03a7-d48e268c60c5')
/
INSERT INTO IDN_CONFIG_TYPE (ID, NAME, DESCRIPTION)
SELECT '9ec61e9d-f0e6-4952-9a09-ab842aeb2db2', 'ATTRIBUTE_CONFIGURATION', 'A resource type to store attribute related configurations.' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM IDN_CONFIG_TYPE WHERE ID = '9ec61e9d-f0e6-4952-9a09-ab842aeb2db2')
/
INSERT INTO IDN_CONFIG_TYPE (ID, NAME, DESCRIPTION)
SELECT '132b0ee6-43e0-462d-8b4b-15b68109d71d', 'ORGANIZATION_CONFIGURATION', 'A resource type to keep the organization configurations.' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM IDN_CONFIG_TYPE WHERE ID = '132b0ee6-43e0-462d-8b4b-15b68109d71d')
/
INSERT INTO IDN_CONFIG_TYPE (ID, NAME, DESCRIPTION)
SELECT '1fc809a0-dc0d-4cb2-82f3-58934d389236', 'CUSTOM_TEXT', 'A resource type to keep the tenant custom text preferences.' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM IDN_CONFIG_TYPE WHERE ID = '1fc809a0-dc0d-4cb2-82f3-58934d389236')
/
INSERT INTO IDN_CONFIG_TYPE (ID, NAME, DESCRIPTION)
SELECT '3e5b1f91-72d8-4fbc-94d1-1b9a4f8c3b07', 'IMPERSONATION_CONFIGURATION', 'A resource type to keep the tenant impersonation preferences.' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM IDN_CONFIG_TYPE WHERE ID = '3e5b1f91-72d8-4fbc-94d1-1b9a4f8c3b07')
/

DECLARE
    col_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO col_exists FROM ALL_TAB_COLUMNS WHERE TABLE_NAME = 'IDN_OIDC_JTI' AND COLUMN_NAME = 'TENANT_ID';
    IF col_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_OIDC_JTI ADD TENANT_ID INTEGER DEFAULT -1 NOT NULL';
    END IF;
END;
/

DECLARE
    pk_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO pk_exists FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'IDN_OIDC_JTI' AND CONSTRAINT_TYPE = 'P';
    IF pk_exists > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_OIDC_JTI DROP PRIMARY KEY';
    END IF;
END;
/
DECLARE
    pk_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO pk_exists FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'IDN_OIDC_JTI' AND CONSTRAINT_NAME = 'PK_IDN_OIDC_JTI';
    IF pk_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_OIDC_JTI ADD CONSTRAINT PK_IDN_OIDC_JTI PRIMARY KEY (JWT_ID, TENANT_ID)';
    END IF;
END;
/

INSERT INTO IDN_SECRET_TYPE (ID, NAME, DESCRIPTION)
SELECT 'c508ca28-60c0-4493-a758-77e4173ffdb9', 'IDP_SECRET_PROPERTIES', 'Secret type to uniquely identify secrets relevant to identity providers' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM IDN_SECRET_TYPE WHERE ID = 'c508ca28-60c0-4493-a758-77e4173ffdb9')
/
DECLARE
    col_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO col_exists FROM ALL_TAB_COLUMNS WHERE TABLE_NAME = 'IDN_SECRET' AND COLUMN_NAME = 'KEY_ID';
    IF col_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_SECRET ADD KEY_ID VARCHAR(255) NULL';
    END IF;
END;
/
ALTER TABLE IDN_SECRET MODIFY SECRET_NAME VARCHAR2(1023)
/
DECLARE
    idx_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO idx_exists FROM USER_INDEXES WHERE INDEX_NAME = 'IDN_SECRET_TYPE_ID';
    IF idx_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDN_SECRET_TYPE_ID ON IDN_SECRET (TYPE_ID)';
    END IF;
END;
/

INSERT INTO IDN_SECRET_TYPE (ID, NAME, DESCRIPTION)
SELECT '29d0c37d-139a-4b1e-a343-7b8d26f0a2a9', 'ANDROID_ATTESTATION_CREDENTIALS', 'Secret type to uniquely identify secrets relevant to android client attestation credentials' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM IDN_SECRET_TYPE WHERE ID = '29d0c37d-139a-4b1e-a343-7b8d26f0a2a9')
/

ALTER TABLE IDN_OAUTH2_AUTHZ_CODE_SCOPE MODIFY "SCOPE" VARCHAR2(255)
/
ALTER TABLE IDN_OAUTH2_ACCESS_TOKEN_SCOPE MODIFY TOKEN_SCOPE VARCHAR2(255)
/

DECLARE
    col_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO col_exists FROM ALL_TAB_COLUMNS WHERE TABLE_NAME = 'IDN_FED_AUTH_SESSION_MAPPING' AND COLUMN_NAME = 'IDP_ID';
    IF col_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_FED_AUTH_SESSION_MAPPING ADD IDP_ID INTEGER DEFAULT 1';
    END IF;
END;
/
DECLARE
    con_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO con_exists FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'IDN_FED_AUTH_SESSION_MAPPING' AND CONSTRAINT_NAME = 'IDP_ID_CONSTRAINT';
    IF con_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_FED_AUTH_SESSION_MAPPING ADD CONSTRAINT IDP_ID_CONSTRAINT FOREIGN KEY (IDP_ID) REFERENCES IDP(ID) ON DELETE CASCADE';
    END IF;
END;
/
DECLARE
    con_name VARCHAR2(255);
BEGIN
    BEGIN
        SELECT c.CONSTRAINT_NAME INTO con_name
        FROM USER_CONSTRAINTS c
        WHERE c.TABLE_NAME = 'IDN_FED_AUTH_SESSION_MAPPING'
          AND c.CONSTRAINT_TYPE = 'U'
          AND (SELECT COUNT(*) FROM USER_CONS_COLUMNS cc WHERE cc.CONSTRAINT_NAME = c.CONSTRAINT_NAME) = 2
          AND EXISTS (SELECT 1 FROM USER_CONS_COLUMNS cc WHERE cc.CONSTRAINT_NAME = c.CONSTRAINT_NAME AND cc.COLUMN_NAME = 'IDP_SESSION_ID')
          AND EXISTS (SELECT 1 FROM USER_CONS_COLUMNS cc WHERE cc.CONSTRAINT_NAME = c.CONSTRAINT_NAME AND cc.COLUMN_NAME = 'TENANT_ID')
          AND ROWNUM = 1;
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_FED_AUTH_SESSION_MAPPING DROP CONSTRAINT ' || con_name;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN NULL;
    END;
END;
/
DECLARE
    con_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO con_exists
    FROM USER_CONSTRAINTS c
    WHERE c.TABLE_NAME = 'IDN_FED_AUTH_SESSION_MAPPING'
      AND c.CONSTRAINT_TYPE = 'U'
      AND (SELECT COUNT(*) FROM USER_CONS_COLUMNS cc WHERE cc.CONSTRAINT_NAME = c.CONSTRAINT_NAME) = 3
      AND EXISTS (SELECT 1 FROM USER_CONS_COLUMNS cc WHERE cc.CONSTRAINT_NAME = c.CONSTRAINT_NAME AND cc.COLUMN_NAME = 'IDP_SESSION_ID')
      AND EXISTS (SELECT 1 FROM USER_CONS_COLUMNS cc WHERE cc.CONSTRAINT_NAME = c.CONSTRAINT_NAME AND cc.COLUMN_NAME = 'TENANT_ID')
      AND EXISTS (SELECT 1 FROM USER_CONS_COLUMNS cc WHERE cc.CONSTRAINT_NAME = c.CONSTRAINT_NAME AND cc.COLUMN_NAME = 'IDP_ID');
    IF con_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_FED_AUTH_SESSION_MAPPING ADD UNIQUE (IDP_SESSION_ID, TENANT_ID, IDP_ID)';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDP_GROUP';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDP_GROUP (
            ID INTEGER NOT NULL,
            IDP_ID INTEGER NOT NULL,
            TENANT_ID INTEGER NOT NULL,
            GROUP_NAME VARCHAR(255) NOT NULL,
            UUID CHAR(36) NOT NULL,
            PRIMARY KEY (ID),
            UNIQUE (IDP_ID, GROUP_NAME),
            UNIQUE (UUID),
            FOREIGN KEY (IDP_ID) REFERENCES IDP(ID) ON DELETE CASCADE)';
    END IF;
END;
/
DECLARE
    seq_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO seq_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'IDP_GROUP_SEQ';
    IF seq_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDP_GROUP_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/
CREATE OR REPLACE TRIGGER IDP_GROUP_TRIG
    BEFORE INSERT
    ON IDP_GROUP
    REFERENCING NEW AS NEW
    FOR EACH ROW
        BEGIN
            SELECT IDP_GROUP_SEQ.nextval INTO :NEW.ID FROM dual;
        END;
/
INSERT INTO IDN_SECRET_TYPE (ID, NAME, DESCRIPTION)
SELECT '433df096-62b7-4a36-b3eb-1bed9150ed35', 'IDVP_SECRET_PROPERTIES', 'Secret type to uniquely identify secrets relevant to identity verification providers' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM IDN_SECRET_TYPE WHERE ID = '433df096-62b7-4a36-b3eb-1bed9150ed35')
/
DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDVP';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDVP (
    ID          INTEGER NOT NULL,
    UUID        CHAR(36) NOT NULL,
    TENANT_ID   INTEGER,
    IDVP_TYPE   VARCHAR(254),
    NAME        VARCHAR(254),
    DESCRIPTION VARCHAR(254),
    IS_ENABLED  CHAR(1) DEFAULT ''1'',
    PRIMARY KEY (ID),
    UNIQUE (TENANT_ID, NAME),
    UNIQUE (UUID)
)';
    END IF;
END;
/
DECLARE
    seq_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO seq_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'IDVP_SEQ';
    IF seq_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDVP_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/
CREATE OR REPLACE TRIGGER IDVP_TRIG
            BEFORE INSERT
            ON IDVP
            REFERENCING NEW AS NEW
            FOR EACH ROW
            BEGIN
                SELECT IDVP_SEQ.nextval INTO :NEW.ID FROM dual;
            END;
/
DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDVP_CLAIM_MAPPING';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDVP_CLAIM_MAPPING (
  ID            INTEGER NOT NULL,
  IDVP_ID       INTEGER,
  TENANT_ID     INTEGER,
  CLAIM         VARCHAR(254),
  LOCAL_CLAIM   VARCHAR(254),
  PRIMARY KEY (ID),
  UNIQUE (IDVP_ID, CLAIM),
  FOREIGN KEY (IDVP_ID) REFERENCES IDVP(ID) ON DELETE CASCADE
)';
    END IF;
END;
/
DECLARE
    seq_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO seq_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'IDVP_CLAIM_MAPPING_SEQ';
    IF seq_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDVP_CLAIM_MAPPING_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/
CREATE OR REPLACE TRIGGER IDVP_CLAIM_MAPPING_TRIG
            BEFORE INSERT
            ON IDVP_CLAIM_MAPPING
            REFERENCING NEW AS NEW
            FOR EACH ROW
            BEGIN
                SELECT IDVP_CLAIM_MAPPING_SEQ.nextval INTO :NEW.ID FROM dual;
            END;
/
DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDVP_CONFIG';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDVP_CONFIG (
    ID              INTEGER NOT NULL,
    IDVP_ID         INTEGER,
    TENANT_ID       INTEGER,
    PROPERTY_KEY    VARCHAR(254) NOT NULL,
    PROPERTY_VALUE  VARCHAR(1024),
    IS_SECRET CHAR(1) DEFAULT ''0'',
    PRIMARY KEY (ID),
    UNIQUE (IDVP_ID, PROPERTY_KEY, TENANT_ID),
    FOREIGN KEY (IDVP_ID) REFERENCES IDVP(ID) ON DELETE CASCADE
)';
    END IF;
END;
/
DECLARE
    seq_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO seq_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'IDVP_CONFIG_SEQ';
    IF seq_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDVP_CONFIG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/
CREATE OR REPLACE TRIGGER IDVP_CONFIG_TRIG
            BEFORE INSERT
            ON IDVP_CONFIG
            REFERENCING NEW AS NEW
            FOR EACH ROW
            BEGIN
                SELECT IDVP_CONFIG_SEQ.nextval INTO :NEW.ID FROM dual;
            END;
/
DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDV_CLAIM';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDV_CLAIM (
    ID          INTEGER NOT NULL,
    UUID        CHAR(36) NOT NULL,
    USER_ID     VARCHAR(254) NOT NULL,
    CLAIM_URI   VARCHAR(254),
    IDVP_ID     CHAR(36) NOT NULL,
    TENANT_ID   INTEGER,
    IS_VERIFIED CHAR(1) DEFAULT ''0'',
    METADATA    BLOB,
    PRIMARY KEY (ID),
    UNIQUE (CLAIM_URI, TENANT_ID, USER_ID, IDVP_ID),
    UNIQUE (UUID),
    FOREIGN KEY (IDVP_ID) REFERENCES IDVP(UUID) ON DELETE CASCADE
)';
    END IF;
END;
/
DECLARE
    seq_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO seq_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'IDV_CLAIM_SEQ';
    IF seq_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDV_CLAIM_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/
CREATE OR REPLACE TRIGGER IDV_CLAIM_TRIG
            BEFORE INSERT
            ON IDV_CLAIM
            REFERENCING NEW AS NEW
            FOR EACH ROW
            BEGIN
                SELECT IDV_CLAIM_SEQ.nextval INTO :NEW.ID FROM dual;
            END;
/

DECLARE
  is_index_exists NUMBER := 0;
BEGIN
  SELECT COUNT(*) INTO is_index_exists FROM (
    SELECT INDEX_NAME FROM USER_INDEXES WHERE TABLE_NAME = 'IDN_OAUTH2_ACCESS_TOKEN' AND INDEX_NAME IN (
      SELECT INDEX_NAME FROM USER_IND_COLUMNS WHERE TABLE_NAME = 'IDN_OAUTH2_ACCESS_TOKEN'
        AND COLUMN_NAME = 'TOKEN_BINDING_REF' AND COLUMN_POSITION = 1
      INTERSECT
      SELECT INDEX_NAME FROM USER_IND_COLUMNS WHERE TABLE_NAME = 'IDN_OAUTH2_ACCESS_TOKEN'
        AND COLUMN_NAME = 'TOKEN_STATE' AND COLUMN_POSITION = 2
    )
  );
  IF is_index_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_TBR_TS ON IDN_OAUTH2_ACCESS_TOKEN (TOKEN_BINDING_REF, TOKEN_STATE)';
  END IF;
END;
/

DECLARE
    idx_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO idx_exists FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_CLAIM_TI_CU';
    IF idx_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_CLAIM_TI_CU ON IDN_CLAIM (TENANT_ID, CLAIM_URI)';
    END IF;
END;
/
DECLARE
    idx_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO idx_exists FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_AUTH_PROP_AUTH_ID';
    IF idx_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_AUTH_PROP_AUTH_ID ON IDP_AUTHENTICATOR_PROPERTY (AUTHENTICATOR_ID)';
    END IF;
END;
/
DECLARE
    idx_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO idx_exists FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_CON_FILE_RES_ID';
    IF idx_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_CON_FILE_RES_ID ON IDN_CONFIG_FILE (RESOURCE_ID)';
    END IF;
END;
/
DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_RECOVERY_FLOW_DATA';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_RECOVERY_FLOW_DATA (
    RECOVERY_FLOW_ID VARCHAR2(255) NOT NULL,
    CODE VARCHAR2(255),
    FAILED_ATTEMPTS INTEGER DEFAULT 0 NOT NULL,
    RESEND_COUNT INTEGER DEFAULT 0 NOT NULL,
    TIME_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY(RECOVERY_FLOW_ID)
)';
    END IF;
END;
/
DECLARE
    col_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO col_exists FROM ALL_TAB_COLUMNS WHERE TABLE_NAME = 'IDN_RECOVERY_DATA' AND COLUMN_NAME = 'RECOVERY_FLOW_ID';
    IF col_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_RECOVERY_DATA ADD RECOVERY_FLOW_ID VARCHAR2(255)';
    END IF;
END;
/
DECLARE
    con_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO con_exists
    FROM USER_CONSTRAINTS c
    WHERE c.TABLE_NAME = 'IDN_RECOVERY_DATA'
      AND c.CONSTRAINT_TYPE = 'R'
      AND EXISTS (SELECT 1 FROM USER_CONS_COLUMNS cc WHERE cc.CONSTRAINT_NAME = c.CONSTRAINT_NAME AND cc.COLUMN_NAME = 'RECOVERY_FLOW_ID');
    IF con_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_RECOVERY_DATA ADD FOREIGN KEY (RECOVERY_FLOW_ID) REFERENCES IDN_RECOVERY_FLOW_DATA(RECOVERY_FLOW_ID) ON DELETE CASCADE';
    END IF;
END;
/
DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'API_RESOURCE';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE API_RESOURCE (
  ID CHAR(36) NOT NULL PRIMARY KEY,
  CURSOR_KEY INTEGER NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  IDENTIFIER VARCHAR(255) NOT NULL,
  TENANT_ID INT,
  DESCRIPTION VARCHAR(255),
  TYPE VARCHAR(255) NOT NULL,
  REQUIRES_AUTHORIZATION NUMBER(1,0) NOT NULL
)';
    END IF;
END;
/
DECLARE
    seq_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO seq_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'API_RESOURCE_SEQ';
    IF seq_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE API_RESOURCE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/
DECLARE
    trig_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO trig_exists FROM USER_TRIGGERS WHERE TRIGGER_NAME = 'API_RESOURCE_SEQ';
    IF trig_exists > 0 THEN
        EXECUTE IMMEDIATE 'DROP TRIGGER API_RESOURCE_SEQ';
    END IF;
END;
/
CREATE OR REPLACE TRIGGER API_RESOURCE_TRIG
            BEFORE INSERT
            ON API_RESOURCE
            REFERENCING NEW AS NEW
            FOR EACH ROW
                BEGIN
                    SELECT API_RESOURCE_SEQ.nextval INTO :NEW.CURSOR_KEY FROM dual;
                END;
/
DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'API_RESOURCE_PROPERTY';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE API_RESOURCE_PROPERTY (
    ID INTEGER,
    API_ID CHAR(36) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    VALUE VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT API_RESOURCE_PROPERTY_CONSTRAINT UNIQUE (API_ID, NAME),
    FOREIGN KEY (API_ID) REFERENCES API_RESOURCE(ID) ON DELETE CASCADE
)';
    END IF;
END;
/
DECLARE
    seq_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO seq_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'API_RESOURCE_PROPERTY_SEQ';
    IF seq_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE API_RESOURCE_PROPERTY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/
CREATE OR REPLACE TRIGGER API_RESOURCE_PROPERTY_TRIG
            BEFORE INSERT
            ON API_RESOURCE_PROPERTY
            REFERENCING NEW AS NEW
            FOR EACH ROW
               BEGIN
                   SELECT API_RESOURCE_PROPERTY_SEQ.nextval INTO :NEW.ID FROM dual;
               END;
/
DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'SCOPE';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE SCOPE (
  ID CHAR(36) NOT NULL PRIMARY KEY,
  CURSOR_KEY INTEGER NOT NULL,
  API_ID CHAR(36) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  DISPLAY_NAME VARCHAR(255) NOT NULL,
  TENANT_ID INT,
  DESCRIPTION VARCHAR(300),
  FOREIGN KEY (API_ID) REFERENCES API_RESOURCE(ID) ON DELETE CASCADE
)';
    END IF;
END;
/
DECLARE
    seq_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO seq_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SCOPE_SEQ';
    IF seq_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE SCOPE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/
DECLARE
    trig_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO trig_exists FROM USER_TRIGGERS WHERE TRIGGER_NAME = 'SCOPE_SEQ';
    IF trig_exists > 0 THEN
        EXECUTE IMMEDIATE 'DROP TRIGGER SCOPE_SEQ';
    END IF;
END;
/
CREATE OR REPLACE TRIGGER SCOPE_TRIG
            BEFORE INSERT
            ON SCOPE
            REFERENCING NEW AS NEW
            FOR EACH ROW
            BEGIN
                SELECT SCOPE_SEQ.nextval INTO :NEW.CURSOR_KEY FROM dual;
            END;
/
DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'AUTHORIZED_API';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE AUTHORIZED_API(
    APP_ID CHAR(36) NOT NULL,
    API_ID CHAR(36) NOT NULL,
    POLICY_ID VARCHAR(255) NOT NULL,
    CONSTRAINT PK_APP_API PRIMARY KEY (APP_ID, API_ID),
    FOREIGN KEY (API_ID) REFERENCES API_RESOURCE(ID) ON DELETE CASCADE,
    FOREIGN KEY (APP_ID) REFERENCES SP_APP(UUID) ON DELETE CASCADE
)';
    END IF;
END;
/
DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'AUTHORIZED_SCOPE';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE AUTHORIZED_SCOPE (
  APP_ID CHAR(36) NOT NULL,
  API_ID CHAR(36) NOT NULL,
  SCOPE_ID CHAR(36) NOT NULL,
  CONSTRAINT PK_APP_API_SCOPE PRIMARY KEY (APP_ID, API_ID, SCOPE_ID),
  FOREIGN KEY (API_ID) REFERENCES API_RESOURCE(ID),
  FOREIGN KEY (SCOPE_ID) REFERENCES SCOPE(ID) ON DELETE CASCADE,
  FOREIGN KEY (APP_ID) REFERENCES SP_APP(UUID),
  FOREIGN KEY (APP_ID, API_ID) REFERENCES AUTHORIZED_API(APP_ID, API_ID) ON DELETE CASCADE,
  CONSTRAINT AUTHORIZED_SCOPE_UNIQUE UNIQUE (APP_ID, SCOPE_ID)
)';
    END IF;
END;
/
DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_OAUTH_PAR';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_OAUTH_PAR (
    REQ_URI_REF VARCHAR2(255) PRIMARY KEY,
    CLIENT_ID VARCHAR2(255) NOT NULL,
    SCHEDULED_EXPIRY NUMBER(22,0) NOT NULL,
    PARAMETERS CLOB
)';
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE ALTER_IDN_OAUTH2_DEVICE_FLOW
IS
  BEGIN
    declare
      column_count INTEGER;
    begin
      select count(*) INTO column_count
      FROM ALL_TAB_COLUMNS
      WHERE OWNER = (SELECT USER FROM DUAL)
        AND TABLE_NAME = 'IDN_OAUTH2_DEVICE_FLOW'
        AND COLUMN_NAME = 'SUBJECT_IDENTIFIER';
      IF column_count = 0
      THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_OAUTH2_DEVICE_FLOW ADD (SUBJECT_IDENTIFIER VARCHAR2(255))';
      END IF;
    end;
  END;
/
CALL ALTER_IDN_OAUTH2_DEVICE_FLOW()
/
DROP PROCEDURE ALTER_IDN_OAUTH2_DEVICE_FLOW
/
DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_ORG_USER_INVITATION';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_ORG_USER_INVITATION (
        ID INTEGER NOT NULL,
        INVITATION_ID VARCHAR(40) NOT NULL,
        CONFIRMATION_CODE VARCHAR(40) NOT NULL,
        USER_NAME VARCHAR(255) NOT NULL,
        DOMAIN_NAME VARCHAR(255) NOT NULL,
        EMAIL VARCHAR(255) NOT NULL,
        USER_ORG_ID VARCHAR(255) NOT NULL,
        INVITED_ORG_ID VARCHAR(255) NOT NULL,
        USER_REDIRECT_URL VARCHAR(1024) NOT NULL,
        STATUS VARCHAR(10) NOT NULL,
        CREATED_AT TIMESTAMP NOT NULL,
        EXPIRED_AT TIMESTAMP NOT NULL,
        PRIMARY KEY (INVITATION_ID)
)';
    END IF;
END;
/
DECLARE
    seq_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO seq_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_ORG_USER_INVITATION_SEQ';
    IF seq_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_ORG_USER_INVITATION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/
CREATE OR REPLACE TRIGGER IDN_ORG_USER_INVITATION_TRIG
            BEFORE INSERT
            ON IDN_ORG_USER_INVITATION
            REFERENCING NEW AS NEW
            FOR EACH ROW
            BEGIN
                SELECT IDN_ORG_USER_INVITATION_SEQ.nextval INTO :NEW.ID FROM dual;
            END;
/
DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'IDN_ORG_USER_INVITE_ASSIGNMENT';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_ORG_USER_INVITE_ASSIGNMENT (
        ID INTEGER NOT NULL,
        INVITATION_ID VARCHAR(40) NOT NULL,
        ASSIGNMENT_ID VARCHAR(255) NOT NULL,
        ASSIGNMENT_TYPE VARCHAR(255) NOT NULL,
        PRIMARY KEY (INVITATION_ID, ASSIGNMENT_ID, ASSIGNMENT_TYPE),
        FOREIGN KEY (INVITATION_ID) REFERENCES IDN_ORG_USER_INVITATION(INVITATION_ID) ON DELETE CASCADE
)';
    END IF;
END;
/
DECLARE
    seq_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO seq_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'IDN_ORG_USER_INVITE_ASSIGNMENT_SEQ';
    IF seq_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE IDN_ORG_USER_INVITE_ASSIGNMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/
CREATE OR REPLACE TRIGGER IDN_ORG_USER_INVITE_ASSIGNMENT_TRIG
            BEFORE INSERT
            ON IDN_ORG_USER_INVITE_ASSIGNMENT
            REFERENCING NEW AS NEW
            FOR EACH ROW
            BEGIN
                SELECT IDN_ORG_USER_INVITE_ASSIGNMENT_SEQ.nextval INTO :NEW.ID FROM dual;
            END;
/
DECLARE
    col_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO col_exists FROM ALL_TAB_COLUMNS WHERE TABLE_NAME = 'IDN_SCIM_GROUP' AND COLUMN_NAME = 'AUDIENCE_REF_ID';
    IF col_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_SCIM_GROUP ADD AUDIENCE_REF_ID INTEGER DEFAULT -1 NOT NULL';
    END IF;
END;
/
DECLARE
    con_name VARCHAR2(255);
BEGIN
    BEGIN
        SELECT c.CONSTRAINT_NAME INTO con_name
        FROM USER_CONSTRAINTS c
        WHERE c.TABLE_NAME = 'IDN_SCIM_GROUP'
          AND c.CONSTRAINT_TYPE = 'U'
          AND (SELECT COUNT(*) FROM USER_CONS_COLUMNS cc WHERE cc.CONSTRAINT_NAME = c.CONSTRAINT_NAME) = 3
          AND EXISTS (SELECT 1 FROM USER_CONS_COLUMNS cc WHERE cc.CONSTRAINT_NAME = c.CONSTRAINT_NAME AND cc.COLUMN_NAME = 'TENANT_ID')
          AND EXISTS (SELECT 1 FROM USER_CONS_COLUMNS cc WHERE cc.CONSTRAINT_NAME = c.CONSTRAINT_NAME AND cc.COLUMN_NAME = 'ROLE_NAME')
          AND EXISTS (SELECT 1 FROM USER_CONS_COLUMNS cc WHERE cc.CONSTRAINT_NAME = c.CONSTRAINT_NAME AND cc.COLUMN_NAME = 'ATTR_NAME')
          AND ROWNUM = 1;
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_SCIM_GROUP DROP CONSTRAINT ' || con_name;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN NULL;
    END;
END;
/
DECLARE
    con_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO con_exists
    FROM USER_CONSTRAINTS c
    WHERE c.TABLE_NAME = 'IDN_SCIM_GROUP'
      AND c.CONSTRAINT_TYPE = 'U'
      AND (SELECT COUNT(*) FROM USER_CONS_COLUMNS cc WHERE cc.CONSTRAINT_NAME = c.CONSTRAINT_NAME) = 4
      AND EXISTS (SELECT 1 FROM USER_CONS_COLUMNS cc WHERE cc.CONSTRAINT_NAME = c.CONSTRAINT_NAME AND cc.COLUMN_NAME = 'TENANT_ID')
      AND EXISTS (SELECT 1 FROM USER_CONS_COLUMNS cc WHERE cc.CONSTRAINT_NAME = c.CONSTRAINT_NAME AND cc.COLUMN_NAME = 'ROLE_NAME')
      AND EXISTS (SELECT 1 FROM USER_CONS_COLUMNS cc WHERE cc.CONSTRAINT_NAME = c.CONSTRAINT_NAME AND cc.COLUMN_NAME = 'ATTR_NAME')
      AND EXISTS (SELECT 1 FROM USER_CONS_COLUMNS cc WHERE cc.CONSTRAINT_NAME = c.CONSTRAINT_NAME AND cc.COLUMN_NAME = 'AUDIENCE_REF_ID');
    IF con_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_SCIM_GROUP ADD UNIQUE (TENANT_ID, ROLE_NAME, ATTR_NAME, AUDIENCE_REF_ID)';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'APP_ROLE_ASSOCIATION';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE APP_ROLE_ASSOCIATION (
  APP_ID CHAR(36) NOT NULL,
  ROLE_ID VARCHAR(255) NOT NULL,
  PRIMARY KEY (APP_ID, ROLE_ID),
  FOREIGN KEY (APP_ID) REFERENCES SP_APP(UUID) ON DELETE CASCADE
)';
    END IF;
END;
/
DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE TABLE_NAME = 'ROLE_SCOPE';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE ROLE_SCOPE (
  ROLE_ID VARCHAR(255) NOT NULL,
  SCOPE_ID CHAR(36) NOT NULL,
  PRIMARY KEY (ROLE_ID, SCOPE_ID),
  FOREIGN KEY (SCOPE_ID) REFERENCES SCOPE(ID) ON DELETE CASCADE
)';
    END IF;
END;
/

DECLARE
    col_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO col_exists FROM ALL_TAB_COLUMNS WHERE TABLE_NAME = 'IDN_OAUTH2_ACCESS_TOKEN' AND COLUMN_NAME = 'AUTHORIZED_ORGANIZATION';
    IF col_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_OAUTH2_ACCESS_TOKEN ADD AUTHORIZED_ORGANIZATION varchar(36) DEFAULT(''NONE'') NOT NULL';
    END IF;
END;
/

DECLARE
    con_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO con_exists FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'IDN_OAUTH2_ACCESS_TOKEN' AND CONSTRAINT_NAME = 'CON_APP_KEY';
    IF con_exists > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_OAUTH2_ACCESS_TOKEN DROP CONSTRAINT CON_APP_KEY';
    END IF;
END;
/
DECLARE
    con_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO con_exists FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'IDN_OAUTH2_ACCESS_TOKEN' AND CONSTRAINT_NAME = 'CON_APP_KEY';
    IF con_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IDN_OAUTH2_ACCESS_TOKEN ADD CONSTRAINT CON_APP_KEY UNIQUE (CONSUMER_KEY_ID,AUTHZ_USER,TENANT_ID,USER_DOMAIN,USER_TYPE,TOKEN_SCOPE_HASH,TOKEN_STATE,TOKEN_STATE_ID,IDP_ID,TOKEN_BINDING_REF,AUTHORIZED_ORGANIZATION)';
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE ALTER_SP_SHARED_APP
IS
  BEGIN
    declare
      column_count INTEGER;
    begin
      select count(*) INTO column_count
      FROM ALL_TAB_COLUMNS
      WHERE OWNER = (SELECT USER FROM DUAL)
        AND TABLE_NAME = 'SP_SHARED_APP'
        AND COLUMN_NAME = 'SHARE_WITH_ALL_CHILDREN';
      IF column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE SP_SHARED_APP ADD (SHARE_WITH_ALL_CHILDREN NUMBER(1,0) DEFAULT 0)';
      END IF;
    end;
  END;
/
CALL ALTER_SP_SHARED_APP()
/
DROP PROCEDURE ALTER_SP_SHARED_APP
/


-- IDN_SECRET --
DECLARE
    column_exists NUMBER;
    nullable_flag VARCHAR2(1);
BEGIN
    SELECT COUNT(*) INTO column_exists FROM ALL_TAB_COLUMNS WHERE TABLE_NAME = 'IDN_SECRET' AND COLUMN_NAME = 'SECRET_VALUE_CLOB';
    IF column_exists = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE IDN_SECRET ADD SECRET_VALUE_CLOB CLOB';
    END IF;

    SELECT NULLABLE INTO nullable_flag FROM ALL_TAB_COLUMNS WHERE TABLE_NAME = 'IDN_SECRET' AND COLUMN_NAME = 'SECRET_VALUE';
    IF nullable_flag = 'N' THEN
            EXECUTE IMMEDIATE 'ALTER TABLE IDN_SECRET MODIFY SECRET_VALUE NULL';
    END IF;
END;
/
