CREATE OR REPLACE PROCEDURE ALTER_SP_APP
BEGIN ATOMIC
    IF EXISTS(SELECT * FROM SYSCAT.TABLES WHERE TABNAME='SP_APP')
	THEN
	    IF NOT EXISTS(SELECT * FROM SYSCAT.COLUMNS WHERE TABNAME='SP_APP' AND COLNAME='VERSION')
	    THEN
	        EXECUTE IMMEDIATE 'ALTER TABLE SP_APP ADD COLUMN VERSION VARCHAR(255) NOT NULL DEFAULT ''v1.0.0''';
	    END IF;
    END IF;
END
/
CALL ALTER_SP_APP
/
DROP PROCEDURE ALTER_SP_APP
/
