DROP PROCEDURE IF EXISTS ALTER_SP_APP;

DELIMITER $$
CREATE PROCEDURE ALTER_SP_APP()
BEGIN
     IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SP_APP' AND COLUMN_NAME='VERSION' and TABLE_SCHEMA = (SELECT DATABASE())) THEN
            ALTER TABLE `SP_APP` ADD COLUMN `VERSION` VARCHAR(255) NOT NULL DEFAULT 'v1.0.0';
     END IF;
END $$
DELIMITER ;

CALL ALTER_SP_APP();

DROP PROCEDURE IF EXISTS ALTER_SP_APP;
