CREATE OR REPLACE PROCEDURE ALTER_SP_APP AS
  v_column_count NUMBER;
BEGIN
  SELECT COUNT(*)
  INTO v_column_count
  FROM ALL_TAB_COLUMNS
  WHERE TABLE_NAME = 'SP_APP'
    AND COLUMN_NAME = 'VERSION';

  IF v_column_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE SP_APP ADD (VERSION VARCHAR(255) DEFAULT ''v1.0.0'' NOT NULL)';
  END IF;
END ALTER_SP_APP;
/
CALL ALTER_SP_APP()
/
DROP PROCEDURE ALTER_SP_APP
/
