ALTER TABLE IDN_OAUTH2_ACCESS_TOKEN_AUDIT ADD ID INTEGER NOT NULL IDENTITY PRIMARY KEY;

ALTER TABLE IDN_OAUTH2_SCOPE_BINDING ADD ID INTEGER NOT NULL IDENTITY PRIMARY KEY;

ALTER TABLE IDN_AUTH_USER_SESSION_MAPPING ADD ID INTEGER NOT NULL IDENTITY PRIMARY KEY;

ALTER TABLE IDN_OAUTH2_CIBA_REQUEST_SCOPES ADD ID INTEGER NOT NULL IDENTITY PRIMARY KEY;

-- Check if the column exists.
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'IDN_OAUTH2_ACCESS_TOKEN' AND COLUMN_NAME = 'CONSENTED_TOKEN')
ALTER TABLE IDN_OAUTH2_ACCESS_TOKEN ADD CONSENTED_TOKEN VARCHAR(6);

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'IDN_FED_AUTH_SESSION_MAPPING' AND COLUMN_NAME = 'ID')
BEGIN
    DECLARE @COMMAND NVARCHAR(200)
    SELECT @COMMAND='ALTER TABLE IDN_FED_AUTH_SESSION_MAPPING DROP CONSTRAINT ' + NAME + ';' FROM   sys.key_constraints WHERE  [type] = 'PK' AND [parent_object_id] = Object_id('dbo.IDN_FED_AUTH_SESSION_MAPPING')
    EXEC (@COMMAND)
    ALTER TABLE IDN_FED_AUTH_SESSION_MAPPING ADD ID INTEGER NOT NULL IDENTITY PRIMARY KEY
    ALTER TABLE IDN_FED_AUTH_SESSION_MAPPING ADD TENANT_ID INTEGER DEFAULT 0 NOT NULL
    ALTER TABLE IDN_FED_AUTH_SESSION_MAPPING ADD UNIQUE(IDP_SESSION_ID, TENANT_ID)
END

DROP PROCEDURE IF EXISTS ADD_TENANT_ID_SP;

CREATE PROCEDURE ADD_TENANT_ID_SP
AS
BEGIN
    DECLARE @sessionId VARCHAR(255)
    DECLARE @tenantId INT
    DECLARE curSessionId CURSOR FOR SELECT SESSION_ID FROM IDN_FED_AUTH_SESSION_MAPPING WHERE TENANT_ID = 0
    OPEN curSessionId

    FETCH NEXT FROM curSessionId INTO @sessionId
    WHILE @@FETCH_STATUS = 0
    BEGIN
        SELECT TOP 1 @tenantId = TENANT_ID FROM IDN_AUTH_SESSION_STORE WHERE SESSION_ID = @sessionId
        IF @tenantId IS NOT NULL
        BEGIN
            UPDATE IDN_FED_AUTH_SESSION_MAPPING SET TENANT_ID = @tenantId WHERE SESSION_ID = @sessionId
        END
        FETCH NEXT FROM curSessionId INTO @sessionId
    END
    CLOSE curSessionId
    DEALLOCATE curSessionId
END;

EXEC ADD_TENANT_ID_SP;

DROP PROCEDURE IF EXISTS ADD_TENANT_ID_SP;
